(()=>{
 const $=id=>document.getElementById(id),frame=()=>$('console'),cdoc=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
 function parentUI(){if(!$('afd54Style')){const s=document.createElement('style');s.id='afd54Style';s.textContent=`.head,.row{grid-template-columns:28px minmax(165px,1fr) 72px 45px 48px 52px 52px 46px 30px!important;gap:3px!important}.row button{padding:0 4px!important;font-size:7px!important}.afdAutoBtn{height:25px!important;padding:0 3px!important;font-size:7px!important}.fav{width:28px!important;padding:0!important}.afdBpm{font-size:8px!important}`;document.head.appendChild(s)}const h=document.querySelector('.tracks .head');if(h&&!h.dataset.afd54){h.dataset.afd54='1';const spans=[...h.children];if(spans.length>=7){h.innerHTML='<span>#</span><span>שם</span><span>תיקייה</span><span>סוג</span><span>BPM</span><span>LOAD A</span><span>LOAD B</span><span>AUTO</span><span>★</span>'}}}
 function startIncoming(d,deck){
   if(d.getElementById('afdSP88Deck'+deck)||d.getElementById('afdSP84Deck'+deck))return;
   const panel=d.getElementById('vid'+deck)?.closest('.panel')||d.querySelector('.deck'+deck);
   const b=panel?.querySelector('[data-act="play"],#play'+deck+',.play');
   const v=d.getElementById('vid'+deck);
   const yt=d.getElementById('ytDeck'+deck);
   const already=(v&&!v.paused&&!v.ended)||b?.dataset.afdPlaying==='1';
   if(!already&&(v?.src||yt||b))b?.click();
 }
 function deckUI(){const d=cdoc();if(!d?.head)return;if(!d.getElementById('afd54DeckStyle')){const s=d.createElement('style');s.id='afd54DeckStyle';s.textContent=`.pitch{position:relative!important;min-height:112px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important}.pitch input{appearance:none!important;-webkit-appearance:none!important;writing-mode:horizontal-tb!important;direction:ltr!important;transform:rotate(-90deg)!important;width:82px!important;height:24px!important;margin:29px -29px!important;touch-action:none!important}.pitch input::-webkit-slider-runnable-track{height:6px;border-radius:4px;background:repeating-linear-gradient(90deg,#7c8792 0 2px,#22272d 2px 10px)!important;border:1px solid #050608}.pitch input::-webkit-slider-thumb{-webkit-appearance:none;width:16px;height:27px;margin-top:-11px;border:1px solid #e3e7eb;border-radius:3px;background:linear-gradient(90deg,#252a30,#c7cdd3 45%,#5d6670 55%,#e8ebee 70%,#20252b)}.afdPitchRead{font-size:8px!important;font-weight:900!important;color:#dbe2e9!important}.afdMixBtn{height:36px;border:1px solid #a56cff;border-radius:6px;background:linear-gradient(#7d51b8,#351d59 60%,#13091f);color:#fff;font-size:10px;font-weight:1000;box-shadow:inset 0 1px #fff7,0 0 12px #8d55ff66;cursor:pointer}.afdMixBtn.on{filter:brightness(1.35)}`;d.head.appendChild(s)}
 ['A','B'].forEach(deck=>{const p=d.getElementById('pitch'+deck);if(!p)return;const box=p.closest('.pitch');if(!box)return;p.min='-10';p.max='10';p.step='0.5';if(!p.dataset.afd54){p.dataset.afd54='1';let r=d.getElementById('afdPitchRead'+deck);if(!r){r=d.createElement('div');r.id='afdPitchRead'+deck;r.className='afdPitchRead';box.appendChild(r)}const update=()=>{const v=+p.value||0;r.textContent=(v>0?'+':'')+v.toFixed(1)+'%'};p.addEventListener('input',update);update()}});
 const master=d.querySelector('.master');if(master&&!d.getElementById('afdMixBtn')){const b=d.createElement('button');b.id='afdMixBtn';b.className='afdMixBtn';b.textContent='MIX A ↔ B';const cross=d.getElementById('cross'),video=d.getElementById('videoCross')||d.querySelector('.master input[type=range]');let timer=null;b.onclick=()=>{if(timer)return;b.classList.add('on');const start=performance.now(),dur=8000,from=+(cross?.value||50),to=from<50?100:0,target=to===0?'B':'A';startIncoming(d,target);function tick(now){const t=Math.min(1,(now-start)/dur),ease=t*t*(3-2*t),v=from+(to-from)*ease;if(cross){cross.value=v;cross.dispatchEvent(new Event('input',{bubbles:true}))}if(video&&video!==cross){video.value=v;video.dispatchEvent(new Event('input',{bubbles:true}))}if(t<1)timer=requestAnimationFrame(tick);else{timer=null;b.classList.remove('on')}}timer=requestAnimationFrame(tick)};const cr=master.querySelector('.cross');cr?.insertAdjacentElement('afterend',b)}}
 function run(){parentUI();deckUI()}frame()?.addEventListener('load',()=>setTimeout(deckUI,250));setTimeout(run,450);setTimeout(run,1200);
})();