const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const audio=$('#audio'),canvas=$('#wave'),ctx=canvas.getContext('2d'),status=$('#status');let words=[],current=0,audioBuffer=null,recorder=null,chunks=[],lastTapIndex=-1,lastTapTime=0;
function go(id){$$('.page').forEach(x=>x.classList.toggle('on',x.id===id));$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.page===id))}$$('.tab').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function fmt(t){if(!isFinite(t))t=0;let m=Math.floor(t/60),s=Math.floor(t%60),ms=Math.floor((t%1)*1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}function setStatus(t){status.textContent=t}
$('#audioFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;audio.src=URL.createObjectURL(f);audio.load();try{const ab=await f.arrayBuffer();audioBuffer=await new(window.AudioContext||window.webkitAudioContext)().decodeAudioData(ab);drawWave()}catch(err){setStatus('השיר נטען; waveform לא זמין בקובץ הזה')}setStatus('השיר נטען: '+f.name)};
$('#imageFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#bgVideo').hidden=true;let im=$('#bgImg');im.src=URL.createObjectURL(f);im.hidden=false};$('#videoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#bgImg').hidden=true;let v=$('#bgVideo');v.src=URL.createObjectURL(f);v.hidden=false;v.play().catch(()=>{})};
function drawWave(){if(!audioBuffer)return;const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#45a5e8';ctx.beginPath();const data=audioBuffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/w));for(let x=0;x<w;x++){let min=1,max=-1;for(let j=0;j<step;j++){let v=data[x*step+j]||0;if(v<min)min=v;if(v>max)max=v}ctx.moveTo(x,(1+min)*h/2);ctx.lineTo(x,(1+max)*h/2)}ctx.stroke()}
canvas.addEventListener('pointerdown',e=>{if(!audio.duration)return;let r=canvas.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(audio.duration,((e.clientX-r.left)/r.width)*audio.duration));updateLivePreview()});window.addEventListener('resize',()=>audioBuffer&&drawWave());
function prepare(){let lines=$('#lyricsText').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);words=[];lines.forEach((line,li)=>line.split(/\s+/).filter(Boolean).forEach(t=>words.push({t,time:null,line:li})));current=0;renderWords();updateSyncPreview();updateLivePreview();setStatus(`${words.length} מילים מוכנות — שתי לחיצות על מילה ממשיכות ממנה`);go('sync')}
function renderWords(){let el=$('#wordList');el.innerHTML='';words.forEach((w,i)=>{let r=document.createElement('div');r.className='wordrow '+(i<current?'done':i===current?'current':'');r.innerHTML=`<span>${i+1}</span><span>${w.t}</span><span>${w.time==null?'—':fmt(w.time)}</span>`;r.onclick=()=>selectWord(i,false);r.ondblclick=e=>{e.preventDefault();selectWord(i,true)};r.addEventListener('touchend',e=>{let now=Date.now();if(lastTapIndex===i&&now-lastTapTime<500){e.preventDefault();selectWord(i,true);lastTapIndex=-1}else{lastTapIndex=i;lastTapTime=now}}, {passive:false});el.appendChild(r)})}
function selectWord(i,play){current=i;let w=words[i];if(w&&w.time!=null)audio.currentTime=w.time;renderWords();updateSyncPreview();updateLivePreview();if(play){audio.play().catch(()=>{});setStatus(`ממשיך סנכרון מהמילה: ${w.t}`)}}
function sync(){if(current>=words.length)return;words[current].time=audio.currentTime;current++;renderWords();updateSyncPreview();updateLivePreview();setStatus(`סונכרנה מילה ${current} מתוך ${words.length}`)}function undo(){if(current<=0)return;current--;words[current].time=null;renderWords();updateSyncPreview();updateLivePreview()}function reset(){words.forEach(w=>w.time=null);current=0;renderWords();updateSyncPreview();updateLivePreview()}function start(){audio.pause();audio.currentTime=0;current=0;renderWords();updateSyncPreview();updateLivePreview();setStatus('חזרה להתחלה')}
function fourLinesForWordIndex(idx){if(!words.length)return[];let li=words[Math.min(Math.max(idx,0),words.length-1)].line??0,start=Math.floor(li/4)*4,lines=[];for(let l=start;l<start+4;l++){let text=words.filter(w=>(w.line??0)===l).map(w=>w.t).join(' ');if(text)lines.push(text)}return lines}
function updateSyncPreview(){if(!words.length){$('#lyricsPreview').textContent='טען שיר והכנס מילים';return}$('#lyricsPreview').innerHTML=fourLinesForWordIndex(Math.min(current,words.length-1)).map(x=>`<div>${x}</div>`).join('')}
function liveIndex(){let t=audio.currentTime,best=0,found=false;for(let i=0;i<words.length;i++){if(words[i].time!=null&&words[i].time<=t){best=i;found=true}else if(words[i].time!=null&&words[i].time>t)break}return found?best:0}
function updateLivePreview(){if(!words.length)return;let idx=liveIndex();if(!audio.paused)$('#lyricsPreview').innerHTML=fourLinesForWordIndex(idx).map(x=>`<div>${x}</div>`).join('')}
$('#prepareBtn').onclick=prepare;$('#syncBtn').onclick=sync;$('#syncBtn2').onclick=sync;$('#undoBtn').onclick=undo;$('#resetBtn').onclick=reset;$('#startBtn').onclick=start;$('#startBtn2').onclick=start;$('#playBtn').onclick=()=>{if(!audio.src){setStatus('קודם טען קובץ מוזיקה');return}audio.play().catch(()=>setStatus('Safari חסם את הניגון — לחץ שוב על נגן'));setStatus('תצוגת תוצאה חיה')};$('#stopBtn').onclick=()=>{audio.pause();setStatus('עצור — המיקום נשמר')};$('#clearBtn').onclick=()=>{$('#lyricsText').value='';words=[];current=0;renderWords();updateSyncPreview()};$('#fullBtn').onclick=()=>$('#preview').requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.code==='Space'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();sync()}});audio.ontimeupdate=()=>{$('#clock').textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`;updateLivePreview()};audio.onended=()=>setStatus('הניגון הסתיים');
$('#saveProject').onclick=()=>download('karaoke_project.json',JSON.stringify({lyrics:$('#lyricsText').value,words,current},null,2),'application/json');$('#loadProject').onchange=async e=>{let f=e.target.files[0];if(!f)return;let p=JSON.parse(await f.text());$('#lyricsText').value=p.lyrics||'';words=p.words||[];current=p.current||0;renderWords();updateSyncPreview();setStatus('הפרויקט נטען')};$('#exportLrc').onclick=()=>{let out=words.filter(w=>w.time!=null).map(w=>`[${fmt(w.time).slice(0,-1)}]${w.t}`).join('\n');download('karaoke.lrc',out,'text/plain;charset=utf-8')};function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#recordBtn').onclick=async()=>{try{const stream=$('#preview').captureStream?.(30);if(!stream)throw Error('unsupported');recorder=new MediaRecorder(stream,{mimeType:'video/webm'});chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>download('karaoke.webm',new Blob(chunks,{type:'video/webm'}),'video/webm');recorder.start();setStatus('מקליט וידאו...')}catch(e){setStatus('ייצוא וידאו לא נתמך כרגע בדפדפן הזה')}};$('#recordStopBtn').onclick=()=>{if(recorder&&recorder.state!=='inactive')recorder.stop()};$('#installBtn').onclick=()=>alert('באייפון: Safari → שיתוף → הוסף למסך הבית.');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});updateSyncPreview();