const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const audio=$('#audio'),canvas=$('#wave'),ctx=canvas.getContext('2d'),status=$('#status');
let words=[],current=0,audioBuffer=null,lastTapIndex=-1,lastTapTime=0;
let exportAudioCtx=null,exportSource=null,exportDest=null,exportBusy=false,ffmpegInstance=null;

function go(id){$$('.page').forEach(x=>x.classList.toggle('on',x.id===id));$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.page===id))}
$$('.tab').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function fmt(t){if(!isFinite(t))t=0;let m=Math.floor(t/60),s=Math.floor(t%60),ms=Math.floor((t%1)*1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}
function setStatus(t){status.textContent=t}
function setExportState(t,p){const el=$('#exportState');if(el)el.textContent=t;const pr=$('#exportProgress');if(pr&&Number.isFinite(p))pr.value=Math.max(0,Math.min(100,p));setStatus(t)}

$('#audioFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;audio.src=URL.createObjectURL(f);audio.load();try{const ab=await f.arrayBuffer();const ac=new(window.AudioContext||window.webkitAudioContext)();audioBuffer=await ac.decodeAudioData(ab);drawWave();ac.close?.()}catch(err){setStatus('השיר נטען; waveform לא זמין בקובץ הזה')}setStatus('השיר נטען: '+f.name)};
$('#imageFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#bgVideo').hidden=true;let im=$('#bgImg');im.src=URL.createObjectURL(f);im.hidden=false};
$('#videoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#bgImg').hidden=true;let v=$('#bgVideo');v.src=URL.createObjectURL(f);v.hidden=false;v.load();v.play().catch(()=>{})};
function drawWave(){if(!audioBuffer)return;const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#45a5e8';ctx.beginPath();const data=audioBuffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/w));for(let x=0;x<w;x++){let min=1,max=-1;for(let j=0;j<step;j++){let v=data[x*step+j]||0;if(v<min)min=v;if(v>max)max=v}ctx.moveTo(x,(1+min)*h/2);ctx.lineTo(x,(1+max)*h/2)}ctx.stroke()}
canvas.addEventListener('pointerdown',e=>{if(!audio.duration)return;let r=canvas.getBoundingClientRect();audio.currentTime=Math.max(0,Math.min(audio.duration,((e.clientX-r.left)/r.width)*audio.duration));updateLivePreview()});
window.addEventListener('resize',()=>audioBuffer&&drawWave());

function prepare(){let lines=$('#lyricsText').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);words=[];lines.forEach((line,li)=>line.split(/\s+/).filter(Boolean).forEach(t=>words.push({t,time:null,line:li})));current=0;renderWords();updateSyncPreview();updateLivePreview();setStatus(`${words.length} מילים מוכנות — לחץ התחלה ואז סנכרן לפי השירה`);go('sync')}
function renderWords(){let el=$('#wordList');el.innerHTML='';words.forEach((w,i)=>{let r=document.createElement('div');r.className='wordrow '+(i<current?'done':i===current?'current':'');r.innerHTML=`<span>${i+1}</span><span>${w.t}</span><span>${w.time==null?'—':fmt(w.time)}</span>`;r.onclick=()=>selectWord(i,false);r.ondblclick=e=>{e.preventDefault();selectWord(i,true)};r.addEventListener('touchend',e=>{let now=Date.now();if(lastTapIndex===i&&now-lastTapTime<500){e.preventDefault();selectWord(i,true);lastTapIndex=-1}else{lastTapIndex=i;lastTapTime=now}}, {passive:false});el.appendChild(r)})}
function selectWord(i,play){current=i;let w=words[i];if(w&&w.time!=null)audio.currentTime=w.time;renderWords();updateSyncPreview();updateLivePreview();if(play){audio.play().catch(()=>{});setStatus(`ממשיך סנכרון מהמילה: ${w.t} — לחץ סנכרן בכל מילה`)}}
function sync(){if(current>=words.length)return;if(audio.paused){setStatus('השיר עצור — לחץ נגן/התחלה ואז סנכרן');return}words[current].time=audio.currentTime;current++;renderWords();updateSyncPreview();updateLivePreview();setStatus(`סונכרנה מילה ${current} מתוך ${words.length} — לחץ שוב במילה הבאה`)}
function undo(){if(current<=0)return;current--;words[current].time=null;renderWords();updateSyncPreview();updateLivePreview()}
function reset(){words.forEach(w=>w.time=null);current=0;renderWords();updateSyncPreview();updateLivePreview();setStatus('הסנכרון אופס')}
function start(){if(!audio.src){setStatus('קודם טען קובץ מוזיקה');return}audio.currentTime=0;current=0;renderWords();updateSyncPreview();updateLivePreview();audio.play().then(()=>setStatus('סנכרון מההתחלה — לחץ ◆ סנכרן בדיוק כשכל מילה נשמעת')).catch(()=>setStatus('לחץ ▶ נגן ואז ◆ סנכרן'))}
function fourLinesForWordIndex(idx){if(!words.length)return[];let li=words[Math.min(Math.max(idx,0),words.length-1)].line??0,start=Math.floor(li/4)*4,lines=[];for(let l=start;l<start+4;l++){let text=words.filter(w=>(w.line??0)===l).map(w=>w.t).join(' ');if(text)lines.push(text)}return lines}
function updateSyncPreview(){if(!words.length){$('#lyricsPreview').textContent='טען שיר והכנס מילים';return}$('#lyricsPreview').innerHTML=fourLinesForWordIndex(Math.min(current,words.length-1)).map(x=>`<div>${x}</div>`).join('')}
function liveIndexAt(t){let best=0,found=false;for(let i=0;i<words.length;i++){if(words[i].time!=null&&words[i].time<=t){best=i;found=true}else if(words[i].time!=null&&words[i].time>t)break}return found?best:0}
function liveIndex(){return liveIndexAt(audio.currentTime)}
function updateLivePreview(){if(!words.length)return;let idx=liveIndex();if(!audio.paused)$('#lyricsPreview').innerHTML=fourLinesForWordIndex(idx).map(x=>`<div>${x}</div>`).join('')}

$('#prepareBtn').onclick=prepare;$('#syncBtn').onclick=sync;$('#syncBtn2').onclick=sync;$('#undoBtn').onclick=undo;$('#resetBtn').onclick=reset;$('#startBtn').onclick=start;$('#startBtn2').onclick=start;
$('#playBtn').onclick=()=>{if(!audio.src){setStatus('קודם טען קובץ מוזיקה');return}audio.play().catch(()=>setStatus('לחץ שוב על נגן'));setStatus('ניגון / תצוגת תוצאה חיה')};
$('#stopBtn').onclick=()=>{audio.pause();setStatus('עצור — המיקום נשמר')};
$('#clearBtn').onclick=()=>{$('#lyricsText').value='';words=[];current=0;renderWords();updateSyncPreview()};
$('#fullBtn').onclick=()=>$('#preview').requestFullscreen?.();
document.addEventListener('keydown',e=>{if(e.code==='Space'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();sync()}});
audio.ontimeupdate=()=>{$('#clock').textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`;updateLivePreview()};audio.onended=()=>setStatus('הניגון הסתיים');

$('#saveProject').onclick=()=>download('karaoke_project.json',JSON.stringify({lyrics:$('#lyricsText').value,words,current},null,2),'application/json');
$('#loadProject').onchange=async e=>{let f=e.target.files[0];if(!f)return;let p=JSON.parse(await f.text());$('#lyricsText').value=p.lyrics||'';words=p.words||[];current=p.current||0;renderWords();updateSyncPreview();setStatus('הפרויקט נטען')};
$('#exportLrc').onclick=()=>{let out=words.filter(w=>w.time!=null).map(w=>`[${fmt(w.time).slice(0,-1)}]${w.t}`).join('\n');download('karaoke.lrc',out,'text/plain;charset=utf-8')};
function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}

function exportPreset(){const q=$('#videoQuality').value,a=$('#audioQuality').value;let width=1920,height=1080,videoK='8M';if(q==='1080-master')videoK='12M';if(q==='4k'){width=3840;height=2160;videoK='20M'}return{width,height,videoK,audioK:`${a}k`}}
function fitFont(c,text,maxWidth,start){let size=start;c.font=`800 ${size}px Arial`;while(size>28&&c.measureText(text).width>maxWidth){size-=2;c.font=`800 ${size}px Arial`}return size}
function drawContain(c,media,w,h){const mw=media.videoWidth||media.naturalWidth||w,mh=media.videoHeight||media.naturalHeight||h;if(!mw||!mh)return;const scale=Math.max(w/mw,h/mh),dw=mw*scale,dh=mh*scale;c.drawImage(media,(w-dw)/2,(h-dh)/2,dw,dh)}
function drawExportFrame(c,w,h,t){c.fillStyle='#03080d';c.fillRect(0,0,w,h);const v=$('#bgVideo'),im=$('#bgImg');try{if(!v.hidden&&v.readyState>=2)drawContain(c,v,w,h);else if(!im.hidden&&im.complete)drawContain(c,im,w,h)}catch(e){}
 const lines=fourLinesForWordIndex(liveIndexAt(t));c.textAlign='center';c.textBaseline='middle';c.direction='rtl';const maxW=w*.9,base=Math.round(h*.075),lineGap=Math.round(h*.105),startY=h/2-((Math.max(lines.length,1)-1)*lineGap)/2;c.lineJoin='round';lines.forEach((line,i)=>{const fs=fitFont(c,line,maxW,base);c.font=`800 ${fs}px Arial`;c.lineWidth=Math.max(5,Math.round(fs*.11));c.strokeStyle='#000';c.fillStyle='#fff';c.strokeText(line,w/2,startY+i*lineGap,maxW);c.fillText(line,w/2,startY+i*lineGap,maxW)});
 const bsize=Math.max(20,Math.round(h*.027));c.font=`900 ${bsize}px Arial`;c.lineWidth=Math.max(2,Math.round(bsize*.12));c.strokeStyle='#fff';c.fillStyle='#2584e6';c.textBaseline='top';c.textAlign='left';c.direction='ltr';c.strokeText('Avi Dayan The Show',Math.round(w*.025),Math.round(h*.025));c.fillText('Avi Dayan The Show',Math.round(w*.025),Math.round(h*.025));c.textAlign='right';c.direction='rtl';c.strokeText('אבי דיין ההופעה',Math.round(w*.975),Math.round(h*.025));c.fillText('אבי דיין ההופעה',Math.round(w*.975),Math.round(h*.025));}

async function ensureExportAudio(){if(exportSource&&exportDest)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw new Error('AudioContext אינו נתמך');exportAudioCtx=new AC();exportSource=exportAudioCtx.createMediaElementSource(audio);exportDest=exportAudioCtx.createMediaStreamDestination();exportSource.connect(exportAudioCtx.destination);exportSource.connect(exportDest)}
function chooseRecorderMime(){const types=['video/mp4;codecs="avc1.42E01E,mp4a.40.2"','video/mp4','video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'];for(const t of types){if(window.MediaRecorder?.isTypeSupported?.(t))return t}return''}
async function recordMaster(){if(!window.MediaRecorder)throw new Error('MediaRecorder אינו נתמך ב-Safari הזה');if(!HTMLCanvasElement.prototype.captureStream)throw new Error('Canvas captureStream אינו נתמך במכשיר הזה');await ensureExportAudio();await exportAudioCtx.resume();const preset=exportPreset(),{width,height}=preset;const fps=30,ec=document.createElement('canvas');ec.width=width;ec.height=height;const c=ec.getContext('2d',{alpha:false});const videoStream=ec.captureStream(fps);const mixed=new MediaStream([...videoStream.getVideoTracks(),...exportDest.stream.getAudioTracks()]);const mime=chooseRecorderMime();const rec=mime?new MediaRecorder(mixed,{mimeType:mime,videoBitsPerSecond:Math.max(6000000,parseInt(preset.videoK)*1000000),audioBitsPerSecond:Number($('#audioQuality').value)*1000}):new MediaRecorder(mixed);const chunks=[];rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};const done=new Promise((resolve,reject)=>{rec.onerror=e=>reject(e.error||new Error('שגיאת הקלטה'));rec.onstop=()=>resolve(new Blob(chunks,{type:rec.mimeType||mime||'video/webm'}))});
 audio.pause();audio.currentTime=0;const bv=$('#bgVideo');if(!bv.hidden){try{bv.currentTime=0;await bv.play()}catch(e){}}
 let raf=0,stopDrawing=false;const draw=()=>{drawExportFrame(c,width,height,audio.currentTime);if(!stopDrawing)raf=requestAnimationFrame(draw)};draw();rec.start(1000);await audio.play();setExportState('שלב 1/3 — מקליט את השיר והתצוגה...',5);
 const duration=Number(audio.duration)||0;await new Promise((resolve,reject)=>{const tick=()=>{if(!exportBusy){reject(new Error('הייצוא בוטל'));return}if(audio.ended||audio.currentTime>=duration-.05){resolve();return}const p=duration?5+(audio.currentTime/duration)*30:10;setExportState('שלב 1/3 — מקליט את השיר והתצוגה...',p);setTimeout(tick,400)};tick()});audio.pause();stopDrawing=true;cancelAnimationFrame(raf);if(rec.state!=='inactive')rec.stop();const blob=await done;videoStream.getTracks().forEach(t=>t.stop());if(blob.size<1000)throw new Error('קובץ ההקלטה ריק');return blob}

async function loadFFmpeg(){if(ffmpegInstance)return ffmpegInstance;setExportState('טוען מנוע קידוד FFmpeg...',37);const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import('https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.12.15/+esm'),import('https://cdn.jsdelivr.net/npm/@ffmpeg/util@0.12.2/+esm')]);const ffmpeg=new FFmpeg();ffmpeg.on('log',({message})=>console.log('[ffmpeg]',message));const base='https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/esm';await ffmpeg.load({coreURL:await toBlobURL(`${base}/ffmpeg-core.js`,'text/javascript'),wasmURL:await toBlobURL(`${base}/ffmpeg-core.wasm`,'application/wasm')});ffmpeg._fetchFile=fetchFile;ffmpegInstance=ffmpeg;return ffmpeg}
function setDownloadLink(id,blob,name){const a=$(id);if(a.dataset.url)URL.revokeObjectURL(a.dataset.url);const u=URL.createObjectURL(blob);a.href=u;a.download=name;a.dataset.url=u;a.classList.add('ready')}
async function transcodeDual(master){const ffmpeg=await loadFFmpeg(),fetchFile=ffmpeg._fetchFile,p=exportPreset();await ffmpeg.writeFile('master_input',await fetchFile(master));
 if((master.type||'').includes('mp4')){setDownloadLink('#downloadMp4',master,'karaoke.mp4');setExportState('שלב 2/3 — MP4 מוכן, עובר ל-WMV...',60)}else{setExportState('שלב 2/3 — יוצר MP4...',45);await ffmpeg.exec(['-i','master_input','-c:v','libx264','-preset','veryfast','-pix_fmt','yuv420p','-b:v',p.videoK,'-c:a','aac','-b:a',p.audioK,'-movflags','+faststart','output.mp4']);const mp4Data=await ffmpeg.readFile('output.mp4');const mp4Blob=new Blob([mp4Data.buffer],{type:'video/mp4'});setDownloadLink('#downloadMp4',mp4Blob,'karaoke.mp4');try{await ffmpeg.deleteFile('output.mp4')}catch(e){}}
 setExportState('שלב 3/3 — יוצר WMV...',72);await ffmpeg.exec(['-i','master_input','-c:v','wmv2','-b:v',p.videoK,'-c:a','wmav2','-b:a',p.audioK,'-strict','-2','output.wmv']);const wmvData=await ffmpeg.readFile('output.wmv');const wmvBlob=new Blob([wmvData.buffer],{type:'video/x-ms-wmv'});setDownloadLink('#downloadWmv',wmvBlob,'karaoke.wmv');try{await ffmpeg.deleteFile('master_input');await ffmpeg.deleteFile('output.wmv')}catch(e){}setExportState('הייצוא הסתיים — שני הקבצים מוכנים לשמירה',100)}

async function dualExport(){if(exportBusy)return;if(!audio.src){setExportState('קודם טען קובץ מוזיקה',0);return}if(!words.length||!words.some(w=>w.time!=null)){setExportState('קודם בצע סנכרון למילים',0);return}exportBusy=true;const btn=$('#dualExportBtn');btn.disabled=true;$('#downloadMp4').classList.remove('ready');$('#downloadWmv').classList.remove('ready');try{const master=await recordMaster();await transcodeDual(master)}catch(err){console.error(err);setExportState('הייצוא נעצר: '+(err?.message||err),0)}finally{exportBusy=false;btn.disabled=false}}
$('#dualExportBtn').onclick=dualExport;
$('#installBtn').onclick=()=>alert('באייפון: Safari → שיתוף → הוסף למסך הבית.');
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=15').catch(()=>{});
updateSyncPreview();