const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const audio=$("#audio"), canvas=$("#wave"), ctx=canvas.getContext("2d"), status=$("#status");let words=[],current=0,audioBuffer=null,recorder=null,chunks=[];
function go(id){$$('.page').forEach(x=>x.classList.toggle('on',x.id===id));$$('.tab').forEach(x=>x.classList.toggle('on',x.dataset.page===id))}$$('.tab').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function fmt(t){if(!isFinite(t))t=0;let m=Math.floor(t/60),s=Math.floor(t%60),ms=Math.floor((t%1)*1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}function setStatus(t){status.textContent=t}
$('#audioFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;audio.src=URL.createObjectURL(f);try{const ab=await f.arrayBuffer();audioBuffer=await new (window.AudioContext||window.webkitAudioContext)().decodeAudioData(ab);drawWave()}catch(err){setStatus('השיר נטען; waveform לא זמין בקובץ הזה')}setStatus('השיר נטען: '+f.name)};
$('#imageFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#bgVideo').hidden=true;let im=$('#bgImg');im.src=URL.createObjectURL(f);im.hidden=false};$('#videoFile').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#bgImg').hidden=true;let v=$('#bgVideo');v.src=URL.createObjectURL(f);v.hidden=false;v.play().catch(()=>{})};
function drawWave(){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#45a5e8';ctx.beginPath();const data=audioBuffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/w));for(let x=0;x<w;x++){let min=1,max=-1;for(let j=0;j<step;j++){let v=data[x*step+j]||0;if(v<min)min=v;if(v>max)max=v}ctx.moveTo(x,(1+min)*h/2);ctx.lineTo(x,(1+max)*h/2)}ctx.stroke()}
canvas.addEventListener('pointerdown',e=>{if(!audio.duration)return;let r=canvas.getBoundingClientRect();audio.currentTime=((e.clientX-r.left)/r.width)*audio.duration});window.addEventListener('resize',()=>audioBuffer&&drawWave());
function prepare(){words=$('#lyricsText').value.trim().split(/\s+/).filter(Boolean).map(t=>({t,time:null}));current=0;renderWords();updatePreview();setStatus(`${words.length} מילים מוכנות`);go('sync')}
function renderWords(){let el=$('#wordList');el.innerHTML='';words.forEach((w,i)=>{let r=document.createElement('div');r.className='wordrow '+(i<current?'done':i===current?'current':'');r.innerHTML=`<span>${i+1}</span><span>${w.t}</span><span>${w.time==null?'—':fmt(w.time)}</span>`;r.onclick=()=>{current=i;if(w.time!=null)audio.currentTime=w.time;renderWords();updatePreview()};el.appendChild(r)})}
function sync(){if(current>=words.length)return;words[current].time=audio.currentTime;current++;renderWords();updatePreview();setStatus(`סונכרנה מילה ${current} מתוך ${words.length}`)}function undo(){if(current<=0)return;current--;words[current].time=null;renderWords();updatePreview()}function reset(){words.forEach(w=>w.time=null);current=0;renderWords();updatePreview()}function start(){audio.currentTime=0;current=0;renderWords();updatePreview()}
function updatePreview(){if(!words.length){$('#lyricsPreview').textContent='טען שיר והכנס מילים';return}let lineStart=Math.floor(current/16)*16,group=words.slice(lineStart,lineStart+16),lines=[];for(let i=0;i<group.length;i+=4)lines.push(group.slice(i,i+4).map(x=>x.t).join(' '));$('#lyricsPreview').innerHTML=lines.slice(0,4).map(x=>`<div>${x}</div>`).join('')}
$('#prepareBtn').onclick=prepare;$('#syncBtn').onclick=sync;$('#syncBtn2').onclick=sync;$('#undoBtn').onclick=undo;$('#resetBtn').onclick=reset;$('#startBtn').onclick=start;$('#startBtn2').onclick=start;$('#playBtn').onclick=()=>audio.play();$('#stopBtn').onclick=()=>audio.pause();$('#clearBtn').onclick=()=>{$('#lyricsText').value='';words=[];current=0;renderWords();updatePreview()};$('#fullBtn').onclick=()=>$('#preview').requestFullscreen?.();document.addEventListener('keydown',e=>{if(e.code==='Space'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();sync()}});audio.ontimeupdate=()=>{$('#clock').textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`};
$('#saveProject').onclick=()=>download('karaoke_project.json',JSON.stringify({lyrics:$('#lyricsText').value,words,current},null,2),'application/json');$('#loadProject').onchange=async e=>{let f=e.target.files[0];if(!f)return;let p=JSON.parse(await f.text());$('#lyricsText').value=p.lyrics||'';words=p.words||[];current=p.current||0;renderWords();updatePreview();setStatus('הפרויקט נטען')};$('#exportLrc').onclick=()=>{let out=words.filter(w=>w.time!=null).map(w=>`[${fmt(w.time).slice(0,-1)}]${w.t}`).join('\n');download('karaoke.lrc',out,'text/plain;charset=utf-8')};function download(name,data,type){let a=document.createElement('a');a.href=URL.createObjectURL(data instanceof Blob?data:new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#recordBtn').onclick=async()=>{try{const stream=$('#preview').captureStream?.(30);if(!stream)throw Error('unsupported');recorder=new MediaRecorder(stream,{mimeType:'video/webm'});chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>download('karaoke.webm',new Blob(chunks,{type:'video/webm'}),'video/webm');recorder.start();setStatus('מקליט וידאו...')}catch(e){setStatus('ייצוא וידאו לא נתמך כרגע בדפדפן הזה')}};$('#recordStopBtn').onclick=()=>{if(recorder&&recorder.state!=='inactive')recorder.stop()};$('#installBtn').onclick=()=>alert('באייפון: Safari → שיתוף → הוסף למסך הבית.');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});updatePreview();