// Hebrew Karaoke Studio Web v1.56 — optimized waveform renderer (interaction handled by later patches)
(function(){
  const syncPage=document.getElementById('sync'),wordList=document.getElementById('wordList'),audioEl=document.getElementById('audio');
  if(!syncPage||!wordList||!audioEl)return;
  const style=document.createElement('style');style.textContent=`#hksSyncWaveEditor{margin:8px 0 10px;padding:8px;border:1px solid #31485c;border-radius:10px;background:#08131f}#hksSyncWaveEditor .hksWaveTitle{font-size:12px;font-weight:900;margin-bottom:5px;display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap}#hksSyncWaveCanvas{display:block;width:100%;height:150px;border-radius:8px;background:#050d16;touch-action:none}#hksSyncWaveHelp{font-size:10px;color:#9fb1c3;margin-top:5px}#hksSyncWaveEdit{display:flex;gap:5px;align-items:center;flex-wrap:wrap;margin-top:6px;direction:rtl}#hksSyncWaveEdit button{height:32px;min-width:68px;padding:0 9px;border:1px solid #71889d;border-radius:7px;background:#173047;color:#fff;font-size:12px;font-weight:800}#hksSyncWaveSelected{font-size:12px;font-weight:800;min-width:150px;flex:1}`;document.head.appendChild(style);
  let editor=document.getElementById('hksSyncWaveEditor');if(!editor){editor=document.createElement('div');editor.id='hksSyncWaveEditor';editor.innerHTML='<div class="hksWaveTitle"><span>גל הקול + נקודות הסנכרון</span><span id="hksSyncWaveCount"></span></div><canvas id="hksSyncWaveCanvas"></canvas><div id="hksSyncWaveHelp">הקווים הכתומים הם מילים מסונכרנות. גרור קו ימינה/שמאלה לתיקון. גרור את הסמן הלבן לבחירת נקודת חזרה.</div><div id="hksSyncWaveEdit"><span id="hksSyncWaveSelected">לא נבחרה מילה</span><button type="button" id="hksSyncMinus50">− 0.05 שנ׳</button><button type="button" id="hksSyncPlus50">+ 0.05 שנ׳</button></div>';wordList.parentElement?.insertBefore(editor,wordList)}
  const canvas=document.getElementById('hksSyncWaveCanvas'),ctx=canvas.getContext('2d'),count=document.getElementById('hksSyncWaveCount'),selectedText=document.getElementById('hksSyncWaveSelected'),minus=document.getElementById('hksSyncMinus50'),plus=document.getElementById('hksSyncPlus50');
  let selected=-1,lastDraw=0,scheduled=false,cacheKey='',waveCols=null;
  const timed=w=>!!w&&w.time!=null&&Number.isFinite(Number(w.time));
  const dur=()=>{try{return Number(audioEl.duration)||Number(audioBuffer?.duration)||0}catch(_){return Number(audioEl.duration)||0}};
  function formatTime(t){t=Math.max(0,Number(t)||0);const m=Math.floor(t/60),s=Math.floor(t%60),ms=Math.floor((t%1)*1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}
  function buildWave(cols){
    if(!audioBuffer)return null;const data=audioBuffer.getChannelData(0),out=new Float32Array(cols*2),seg=data.length/cols,samples=32;
    for(let x=0;x<cols;x++){let mn=1,mx=-1,start=Math.floor(x*seg),end=Math.max(start+1,Math.floor((x+1)*seg)),stride=Math.max(1,Math.floor((end-start)/samples));for(let p=start;p<end;p+=stride){const v=data[p]||0;if(v<mn)mn=v;if(v>mx)mx=v}out[x*2]=mn;out[x*2+1]=mx}return out;
  }
  function draw(){
    scheduled=false;lastDraw=performance.now();const r=canvas.getBoundingClientRect(),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height)),dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#050d16';ctx.fillRect(0,0,w,h);
    if(audioBuffer){const cols=Math.min(1200,Math.max(200,Math.round(w)));const key=`${audioBuffer.length}:${cols}`;if(key!==cacheKey){cacheKey=key;waveCols=buildWave(cols)}if(waveCols){ctx.strokeStyle='#45a5e8';ctx.lineWidth=1;ctx.beginPath();for(let x=0;x<cols;x++){const px=(x/(cols-1))*w,mn=waveCols[x*2],mx=waveCols[x*2+1];ctx.moveTo(px,(1+mn)*h/2);ctx.lineTo(px,(1+mx)*h/2)}ctx.stroke()}}
    const d=dur();let marks=0;if(d>0&&Array.isArray(words)){for(let i=0;i<words.length;i++){const mw=words[i];if(!timed(mw))continue;marks++;const x=Math.max(0,Math.min(w,(Number(mw.time)/d)*w));ctx.strokeStyle=i===selected?'#ffd36a':'#ff9f1c';ctx.lineWidth=i===selected?3:1.5;ctx.beginPath();ctx.moveTo(x,5);ctx.lineTo(x,h-5);ctx.stroke();if(i===selected){ctx.fillStyle='#ffd36a';ctx.beginPath();ctx.arc(x,10,6,0,Math.PI*2);ctx.fill()}}const px=Math.max(0,Math.min(w,(Number(audioEl.currentTime||0)/d)*w));ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(px,0);ctx.lineTo(px,h);ctx.stroke()}if(count)count.textContent=marks?`${marks} נקודות מסונכרנות`:'אין עדיין נקודות סנכרון';const sw=Array.isArray(words)?words[selected]:null;if(selectedText)selectedText.textContent=timed(sw)?`מילה: ${sw.t} — ${formatTime(sw.time)}`:'לא נבחרה מילה';if(minus)minus.disabled=!timed(sw);if(plus)plus.disabled=!timed(sw);
  }
  function schedule(){if(scheduled)return;const wait=Math.max(0,70-(performance.now()-lastDraw));scheduled=true;setTimeout(()=>requestAnimationFrame(draw),wait)}
  function clamp(i,t){let min=0,max=dur()||t;for(let p=i-1;p>=0;p--)if(timed(words[p])){min=Number(words[p].time)+.001;break}for(let n=i+1;n<words.length;n++)if(timed(words[n])){max=Math.min(max,Number(words[n].time)-.001);break}return Math.max(min,Math.min(max,Number(t)||0))}
  function nudge(delta){if(selected<0||!timed(words[selected]))return;words[selected].time=clamp(selected,Number(words[selected].time)+delta);audioEl.currentTime=words[selected].time;try{renderWords();updateSyncPreview()}catch(_){}draw()}
  minus?.addEventListener('click',()=>nudge(-.05));plus?.addEventListener('click',()=>nudge(.05));
  audioEl.addEventListener('timeupdate',schedule);audioEl.addEventListener('loadedmetadata',draw);window.addEventListener('resize',()=>setTimeout(draw,60));['syncBtn','syncBtn2','undoBtn','resetBtn','startBtn','startBtn2'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>setTimeout(draw,0)));document.getElementById('audioFile')?.addEventListener('change',()=>setTimeout(()=>{cacheKey='';draw()},500));document.getElementById('loadProject')?.addEventListener('change',()=>setTimeout(draw,700));
  window.__hksDrawSyncWave=draw;window.__hksSelectSyncMarker56=i=>{selected=Number(i);draw()};setTimeout(draw,0);
})();