// Hebrew Karaoke Studio — v1.47 loader
import('./patch-v31.js?v=47')
  .then(()=>import('./patch-v32.js?v=47'))
  .then(()=>import('./patch-v33.js?v=47'))
  .then(()=>import('./patch-v34.js?v=47'))
  .then(()=>import('./patch-v35.js?v=47'))
  .then(()=>import('./patch-v36.js?v=47'))
  .then(()=>import('./patch-v37.js?v=47'))
  .then(()=>import('./patch-v38.js?v=47'))
  .then(()=>import('./patch-v39.js?v=47'))
  .then(()=>import('./patch-v40.js?v=47'))
  .then(()=>import('./patch-v41.js?v=47'))
  .then(()=>import('./patch-v42.js?v=47'))
  .then(()=>import('./patch-v43.js?v=47'))
  .then(()=>import('./patch-v44.js?v=47'))
  .then(()=>import('./patch-v45.js?v=47'))
  .then(()=>import('./patch-v46.js?v=47'))
  .then(()=>import('./patch-v47.js?v=47'))
  .catch(e=>{console.error('[v47]',e);try{setStatus('שגיאה בטעינת עדכון v1.47')}catch(_){} });
