const {app,BrowserWindow,shell,session,ipcMain,protocol,dialog}=require('electron');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const os=require('os');
const {spawn}=require('child_process');
const {Readable}=require('stream');

protocol.registerSchemesAsPrivileged([{scheme:'afdmedia',privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true,corsEnabled:true}}]);
app.commandLine.appendSwitch('autoplay-policy','no-user-gesture-required');
const DESIGN_WIDTH=1600,DESIGN_HEIGHT=950,MIN_ZOOM=.55,MAX_ZOOM=1.40,ZOOM_STEP=.10;
const readRuntime=n=>fs.readFileSync(path.join(__dirname,n),'utf8');
const RUNTIME_BASE_JS=readRuntime('runtime-v167.js'),RUNTIME_FIX_JS=readRuntime('runtime-v168.js'),RUNTIME_PERSIST_JS=readRuntime('runtime-v169.js'),RUNTIME_LIBRARY_JS=readRuntime('runtime-v170.js'),RUNTIME_LIBRARY_FIX_JS=readRuntime('runtime-v171.js'),RUNTIME_TEXT_SCROLL_JS=readRuntime('runtime-v172.js'),RUNTIME_KEY_JS=readRuntime('runtime-v184.js'),RUNTIME_MEDIA_PLAYLIST_JS=readRuntime('runtime-v177.js'),RUNTIME_LOAD_JS=readRuntime('runtime-v185.js'),RUNTIME_EJECT_JS=readRuntime('runtime-v175.js');
const SIGNALSMITH_JS=fs.readFileSync(path.join(__dirname,'node_modules','signalsmith-stretch','SignalsmithStretch.js'),'utf8');
const MEDIA_URLS=new Map(),MEDIA_JOBS=new Map();
const NATIVE_EXT=new Set(['.mp4','.m4v','.webm','.ogv','.ogg','.mp3','.wav','.wave','.m4a','.aac','.flac','.opus']);
const REMUX_FIRST=new Set(['.mov','.mkv','.avi','.ts','.mts','.m2ts']);
const VIDEO_EXT=new Set(['.mp4','.m4v','.mov','.webm','.ogv','.avi','.wmv','.asf','.mkv','.mpg','.mpeg','.m2v','.ts','.mts','.m2ts','.vob','.flv','.f4v','.3gp','.3g2','.rm','.rmvb','.divx','.dv']);
const PIPE='v5';let mediaCacheDir='',keyCacheDir='';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function trustedSender(event){const u=String(event?.sender?.getURL?.()||'');return u.startsWith('https://afd-dj.vercel.app/')}
function cleanPlaylistName(s){return String(s||'AFD Playlist').replace(/[<>:"/\\|?*\x00-\x1F]/g,' ').replace(/\s+/g,' ').trim().slice(0,100)||'AFD Playlist'}
function playlistTracks(raw){return(Array.isArray(raw)?raw:[]).map(x=>({path:String(x?.path||''),name:String(x?.name||''),folder:String(x?.folder||''),kind:String(x?.kind||'music')})).filter(x=>path.isAbsolute(x.path)&&fs.existsSync(x.path))}
function playlistTitle(p,f='AFD Playlist'){return cleanPlaylistName(path.basename(p).replace(/\.afdplaylist$/i,'').replace(/\.json$/i,'')||f)}
function ffmpegExecutable(){let p=require('ffmpeg-static');if(app.isPackaged)p=p.replace('app.asar'+path.sep,'app.asar.unpacked'+path.sep);return p}
function mediaUrl(filePath){const token=crypto.randomBytes(18).toString('hex');MEDIA_URLS.set(token,filePath);return'afdmedia://media/'+token}
function safeUnlink(p){try{if(fs.existsSync(p))fs.unlinkSync(p)}catch(e){}}
function runFfmpeg(args,timeoutMs=600000){return new Promise((resolve,reject)=>{const cp=spawn(ffmpegExecutable(),args,{windowsHide:true,stdio:['ignore','ignore','pipe']});let err='',done=false;try{os.setPriority(cp.pid,os.constants.priority.PRIORITY_IDLE)}catch(e){try{os.setPriority(cp.pid,os.constants.priority.PRIORITY_BELOW_NORMAL)}catch(x){}}const finish=error=>{if(done)return;done=true;clearTimeout(timer);error?reject(error):resolve()};const timer=setTimeout(()=>{try{cp.kill('SIGKILL')}catch(e){}finish(new Error('FFmpeg preparation timed out.'))},timeoutMs);cp.stderr.on('data',b=>{err+=b.toString();if(err.length>16000)err=err.slice(-16000)});cp.on('error',finish);cp.on('close',code=>finish(code===0?null:new Error(err.trim()||('FFmpeg exited '+code))))})}
async function tryRemux(input,output){safeUnlink(output);try{await runFfmpeg(['-hide_banner','-loglevel','error','-nostdin','-y','-i',input,'-map','0:v:0?','-map','0:a:0?','-c','copy','-movflags','+faststart',output],90000);return fs.existsSync(output)&&fs.statSync(output).size>1024}catch(e){safeUnlink(output);return false}}
async function transcodeVideo(input,output){safeUnlink(output);await runFfmpeg(['-hide_banner','-loglevel','error','-nostdin','-y','-threads','1','-filter_threads','1','-filter_complex_threads','1','-i',input,'-map','0:v:0?','-map','0:a:0?','-c:v','libx264','-preset','ultrafast','-tune','fastdecode','-crf','24','-threads','1','-pix_fmt','yuv420p','-c:a','aac','-b:a','192k','-max_muxing_queue_size','2048','-movflags','+faststart',output],900000)}
async function transcodeAudio(input,output,float=false){safeUnlink(output);await runFfmpeg(['-hide_banner','-loglevel','error','-nostdin','-y','-threads','1','-i',input,'-vn','-c:a',float?'pcm_f32le':'pcm_s16le','-ar','48000','-ac','2',output],600000)}
function sourceSignature(input,suffix){const st=fs.statSync(input);return crypto.createHash('sha1').update(PIPE+'|'+input+'|'+st.size+'|'+st.mtimeMs+'|'+suffix).digest('hex')}
async function prepareMedia(meta){
 const input=path.resolve(String(meta?.path||''));if(!input||!fs.existsSync(input)||!fs.statSync(input).isFile())throw Error('Media file was not found.');const ext=path.extname(input).toLowerCase(),force=!!meta?.force,kind=String(meta?.kind||'')==='video'||VIDEO_EXT.has(ext)?'video':'music';if(!force&&NATIVE_EXT.has(ext))return{url:mediaUrl(input),converted:false,remuxed:false,kind,name:path.basename(input)};
 const sig=sourceSignature(input,kind),tag=force?'full':'auto',output=path.join(mediaCacheDir,sig+'-'+tag+(kind==='video'?'.mp4':'.wav')),jobKey=sig+'|'+tag+'|'+kind;let remuxed=false;if(!fs.existsSync(output)||fs.statSync(output).size<1024){if(MEDIA_JOBS.has(jobKey))await MEDIA_JOBS.get(jobKey);else{const job=(async()=>{try{if(kind==='video'&&!force&&REMUX_FIRST.has(ext)){remuxed=await tryRemux(input,output);if(remuxed)return}if(kind==='video')await transcodeVideo(input,output);else await transcodeAudio(input,output,false)}catch(e){safeUnlink(output);throw e}})();MEDIA_JOBS.set(jobKey,job);try{await job}finally{MEDIA_JOBS.delete(jobKey)}}}if(!fs.existsSync(output)||fs.statSync(output).size<1024)throw Error('Prepared media file was not created.');if(!force&&REMUX_FIRST.has(ext)&&!remuxed){const full=path.join(mediaCacheDir,sig+'-full.mp4');if(fs.existsSync(full)&&fs.statSync(full).size>1024)return{url:mediaUrl(full),converted:true,remuxed:false,kind,name:path.basename(input)}}return{url:mediaUrl(output),converted:!remuxed,remuxed,kind,name:path.basename(input)}
}
async function prepareKeyAudio(meta){const input=path.resolve(String(meta?.path||''));if(!input||!fs.existsSync(input)||!fs.statSync(input).isFile())throw Error('Key audio source was not found.');const sig=sourceSignature(input,'hq-key-f32'),output=path.join(keyCacheDir,sig+'.wav'),jobKey='key|'+sig;if(!fs.existsSync(output)||fs.statSync(output).size<2048){if(MEDIA_JOBS.has(jobKey))await MEDIA_JOBS.get(jobKey);else{const job=(async()=>{try{await transcodeAudio(input,output,true)}catch(e){safeUnlink(output);throw e}})();MEDIA_JOBS.set(jobKey,job);try{await job}finally{MEDIA_JOBS.delete(jobKey)}}}return{url:mediaUrl(output),name:path.basename(input)}}
function mimeFor(p){switch(path.extname(p).toLowerCase()){case'.mp4':case'.m4v':return'video/mp4';case'.webm':return'video/webm';case'.mp3':return'audio/mpeg';case'.wav':case'.wave':return'audio/wav';case'.m4a':return'audio/mp4';case'.aac':return'audio/aac';case'.flac':return'audio/flac';case'.ogg':case'.ogv':return'application/ogg';case'.opus':return'audio/ogg';default:return'application/octet-stream'}}
function rangeResponse(request,p){try{const st=fs.statSync(p);if(!st.isFile())throw Error('not file');const size=st.size,type=mimeFor(p),range=request.headers.get('range');const base={'Content-Type':type,'Accept-Ranges':'bytes','Cache-Control':'no-store'};if(request.method==='HEAD')return new Response(null,{status:200,headers:{...base,'Content-Length':String(size)}});if(range){const m=/bytes=(\d*)-(\d*)/.exec(range);if(m){let start=m[1]?Number(m[1]):0,end=m[2]?Number(m[2]):size-1;if(!m[1]&&m[2]){const tail=Number(m[2]);start=Math.max(0,size-tail);end=size-1}start=clamp(start,0,Math.max(0,size-1));end=clamp(end,start,size-1);const stream=fs.createReadStream(p,{start,end});return new Response(Readable.toWeb(stream),{status:206,headers:{...base,'Content-Range':`bytes ${start}-${end}/${size}`,'Content-Length':String(end-start+1)}})}}const stream=fs.createReadStream(p);return new Response(Readable.toWeb(stream),{status:200,headers:{...base,'Content-Length':String(size)}})}catch(e){return new Response('Media not found',{status:404})}}
async function savePlaylistFile(event,payload){if(!trustedSender(event))throw Error('Playlist request blocked.');const tracks=playlistTracks(payload?.tracks);if(!tracks.length)throw Error('Playlist has no available local tracks.');const base=cleanPlaylistName(payload?.defaultName||'AFD Playlist'),result=await dialog.showSaveDialog({title:'Save AFD DJ Playlist',defaultPath:path.join(app.getPath('documents'),base+'.afdplaylist'),buttonLabel:'Save Playlist',filters:[{name:'AFD DJ Playlist',extensions:['afdplaylist']},{name:'JSON',extensions:['json']}],properties:['showOverwriteConfirmation','createDirectory']});if(result.canceled||!result.filePath)return{canceled:true};let filePath=result.filePath;if(!/\.(afdplaylist|json)$/i.test(filePath))filePath+='.afdplaylist';const name=playlistTitle(filePath,base),data={format:'AFD-DJ-PLAYLIST',version:1,name,savedAt:new Date().toISOString(),tracks};fs.writeFileSync(filePath,JSON.stringify(data,null,2),'utf8');return{canceled:false,filePath,name,tracks}}
async function readPlaylistFile(event,filePath){if(!trustedSender(event))throw Error('Playlist request blocked.');const p=path.resolve(String(filePath||''));if(!path.isAbsolute(p)||!fs.existsSync(p)||!fs.statSync(p).isFile())throw Error('Playlist file not found.');const data=JSON.parse(fs.readFileSync(p,'utf8'));if(!Array.isArray(data?.tracks))throw Error('Invalid AFD DJ playlist.');return{name:cleanPlaylistName(data.name||playlistTitle(p)),filePath:p,tracks:data.tracks.map(x=>({path:String(x?.path||''),name:String(x?.name||''),folder:String(x?.folder||''),kind:String(x?.kind||'music')}))}}
function create(){
 const w=new BrowserWindow({width:1600,height:950,minWidth:900,minHeight:600,backgroundColor:'#05070b',title:'AFD DJ',autoHideMenuBar:true,fullscreen:false,fullscreenable:true,show:true,webPreferences:{contextIsolation:true,nodeIntegration:false,webSecurity:true,preload:path.join(__dirname,'preload.js'),autoplayPolicy:'no-user-gesture-required'}});let manualZoom=1,resizeTimer=null,leavingFullScreen=false,spotifyAuthWindow=null;
 const fitForScreen=()=>{const b=w.getContentBounds();return clamp(Math.min(1,b.width/DESIGN_WIDTH,b.height/DESIGN_HEIGHT),MIN_ZOOM,1)};function applyZoom(){w.webContents.setZoomFactor(clamp(fitForScreen()*manualZoom,MIN_ZOOM,MAX_ZOOM));w.webContents.executeJavaScript(`window.dispatchEvent(new Event('resize'));`,true).catch(()=>{})}function changeZoom(d){manualZoom=clamp(Math.round((manualZoom+d)*100)/100,.65,1.55);applyZoom()}function resetZoom(){manualZoom=1;applyZoom()}
 async function inject(){try{await w.webContents.executeJavaScript('window.__afdSignalsmithSource='+JSON.stringify(SIGNALSMITH_JS),true);for(const js of [RUNTIME_BASE_JS,RUNTIME_FIX_JS,RUNTIME_PERSIST_JS,RUNTIME_LIBRARY_JS,RUNTIME_LIBRARY_FIX_JS,RUNTIME_TEXT_SCROLL_JS,RUNTIME_KEY_JS,RUNTIME_MEDIA_PLAYLIST_JS,RUNTIME_LOAD_JS,RUNTIME_EJECT_JS])await w.webContents.executeJavaScript(js,true)}catch(e){console.error('AFD inject',e)}}
 function exitToMaximized(){if(leavingFullScreen)return;leavingFullScreen=true;try{if(w.isFullScreen())w.setFullScreen(false)}catch(e){}setTimeout(()=>{try{w.maximize()}catch(e){}leavingFullScreen=false;applyZoom();inject()},180)}function enterFullScreen(){try{if(!w.isFullScreen())w.setFullScreen(true)}catch(e){}}
 const isSpotifyAuthorize=url=>{try{const u=new URL(url);return u.hostname==='accounts.spotify.com'&&u.pathname.startsWith('/authorize')}catch(e){return false}},isSpotifyCallback=url=>{try{const u=new URL(url),s=u.searchParams.get('state')||'';return u.origin==='https://afd-dj.vercel.app'&&u.pathname.endsWith('/workstation.html')&&s.startsWith('afd168_')}catch(e){return false}};
 function sendSpotifyCallback(url){w.webContents.executeJavaScript(`window.__afdSpotifyCallback168&&window.__afdSpotifyCallback168(${JSON.stringify(url)})`,true).catch(()=>{})}function openSpotifyAuth(authUrl){if(spotifyAuthWindow&&!spotifyAuthWindow.isDestroyed())try{spotifyAuthWindow.close()}catch(e){}const child=new BrowserWindow({parent:w,modal:true,width:540,height:760,minWidth:460,minHeight:620,title:'Spotify Login',autoHideMenuBar:true,backgroundColor:'#121212',show:true,webPreferences:{contextIsolation:true,nodeIntegration:false,webSecurity:true}});spotifyAuthWindow=child;let handled=false;const capture=(event,url)=>{if(handled||!isSpotifyCallback(url))return;handled=true;try{event?.preventDefault?.()}catch(e){}sendSpotifyCallback(url);setTimeout(()=>{try{child.close()}catch(e){}},80)};child.webContents.on('will-navigate',capture);child.webContents.on('will-redirect',capture);child.webContents.on('did-navigate',(_e,u)=>capture(null,u));child.webContents.on('did-navigate-in-page',(_e,u)=>capture(null,u));child.on('closed',()=>{if(spotifyAuthWindow===child)spotifyAuthWindow=null});child.loadURL(authUrl).catch(()=>{})}
 w.webContents.on('will-navigate',(e,u)=>{if(isSpotifyAuthorize(u)){e.preventDefault();openSpotifyAuth(u)}});w.webContents.on('before-input-event',(e,input)=>{const code=input.code||'',key=input.key||'';if(key==='Escape'||code==='Escape'){if(w.isFullScreen()){e.preventDefault();exitToMaximized()}return}if(code==='F11'||key==='F11'){e.preventDefault();w.isFullScreen()?exitToMaximized():enterFullScreen();return}if(!(input.control||input.meta))return;const plus=code==='Equal'||code==='NumpadAdd'||key==='+'||key==='=',minus=code==='Minus'||code==='NumpadSubtract'||key==='-',reset=code==='Digit0'||code==='Numpad0'||key==='0';if(plus){e.preventDefault();changeZoom(ZOOM_STEP)}else if(minus){e.preventDefault();changeZoom(-ZOOM_STEP)}else if(reset){e.preventDefault();resetZoom()}});
 w.webContents.on('dom-ready',inject);w.webContents.on('did-finish-load',()=>{inject();applyZoom()});w.on('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{applyZoom();inject()},90)});w.on('leave-full-screen',()=>{if(leavingFullScreen)setTimeout(()=>{try{w.maximize()}catch(e){}applyZoom();inject()},80)});w.on('ready-to-show',()=>{try{w.maximize()}catch(e){}setTimeout(enterFullScreen,180)});w.loadURL('https://afd-dj.vercel.app/workstation.html?v=185&t='+Date.now());w.webContents.setWindowOpenHandler(({url})=>{if(url.startsWith('spotify:')){shell.openExternal(url).catch(()=>shell.openExternal('https://open.spotify.com/'));return{action:'deny'}}if(isSpotifyAuthorize(url)){openSpotifyAuth(url);return{action:'deny'}}if(url.startsWith('about:blank'))return{action:'allow',overrideBrowserWindowOptions:{width:1280,height:720,autoHideMenuBar:true,backgroundColor:'#000'}};shell.openExternal(url).catch(()=>{});return{action:'deny'}})
}
app.whenReady().then(async()=>{mediaCacheDir=path.join(app.getPath('userData'),'media-cache-v5');keyCacheDir=path.join(app.getPath('userData'),'key-cache-v1');for(const d of [mediaCacheDir,keyCacheDir])try{fs.mkdirSync(d,{recursive:true})}catch(e){}protocol.handle('afdmedia',request=>{try{const u=new URL(request.url),token=decodeURIComponent(u.pathname.replace(/^\/+/,'')),p=MEDIA_URLS.get(token);if(!p)throw Error('Unknown token');return rangeResponse(request,p)}catch(e){return new Response('Media not found',{status:404})}});ipcMain.handle('afd-media-prepare',async(event,meta)=>{if(!trustedSender(event))throw Error('Media request blocked.');return prepareMedia(meta)});ipcMain.handle('afd-key-audio-prepare',async(event,meta)=>{if(!trustedSender(event))throw Error('Key audio request blocked.');return prepareKeyAudio(meta)});ipcMain.handle('afd-playlist-save',savePlaylistFile);ipcMain.handle('afd-playlist-read',readPlaylistFile);await session.defaultSession.clearCache().catch(()=>{});await session.defaultSession.clearStorageData({storages:['serviceworkers','cachestorage']}).catch(()=>{});session.defaultSession.setPermissionRequestHandler((wc,p,cb)=>cb(['media','fullscreen','window-management','display-capture'].includes(p)));create();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)create()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});