(()=>{
if(window.__afdWin184V142){window.__afdWin184V142.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return frame()?.contentWindow||null}catch(e){return null}};
let doc=null,win=null,ctx=null,mix=.5,mixBusy=false,mixRaf=0,lastPublished=-1,signalsmithReady=false;
const key={A:0,B:0},nodes={A:null,B:null},serial={A:0,B:0},syncBusy={A:false,B:false};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const status=t=>{const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD HQ/MIX/SYNC 184.2]',t)};
const value=(id,def)=>{const e=doc?.getElementById(id);return e?Number(e.value):def};
function factor(k){const x=clamp(mix,0,1);return k==='A'?x:1-x}
function baseBpm(k){const e=doc?.getElementById('bpm'+k);let b=Number(e?.dataset?.afdBaseBpm||parseFloat(e?.textContent)||0);return Number.isFinite(b)&&b>20?b:0}
function online(k){return!!(doc?.getElementById('ytDeck'+k)||doc?.getElementById('afdSP105Deck'+k))}
function metaFor(k){return window.AFDLocalDeckMeta?.[k]||null}
function mediaIdentity(k){const n=nodes[k],m=metaFor(k);return String(m?.path||m?.key||m?.name||n?.v?.currentSrc||n?.v?.src||'')}
async function ensureSignalsmith(){
 if(signalsmithReady&&win?.SignalsmithStretch)return true;
 const source=String(window.__afdSignalsmithSource||'');if(!source)return false;
 try{if(!win.SignalsmithStretch)win.Function(source+'\n;window.SignalsmithStretch=SignalsmithStretch;')();signalsmithReady=typeof win.SignalsmithStretch==='function';return signalsmithReady}catch(e){console.warn('Signalsmith load',e);return false}
}
function applyVideo(){if(!doc)return;const a=String(clamp(mix,0,1)),b=String(1-clamp(mix,0,1));['masterA','ytMasterA'].forEach(id=>{const e=doc.getElementById(id);if(e)e.style.setProperty('opacity',a,'important')});['masterB','ytMasterB'].forEach(id=>{const e=doc.getElementById(id);if(e)e.style.setProperty('opacity',b,'important')})}
function publish(force=false){const p=Math.round(mix*1000)/10;if(!force&&p===lastPublished)return;lastPublished=p;try{window.dispatchEvent(new CustomEvent('afd-crossfader',{detail:{value:mix*100,a:factor('A'),b:factor('B')}}))}catch(e){}}
function apply(force=false){
 if(!doc)return;const master=clamp(value('afdMasterVolume',100)/100,0,1);
 for(const k of ['A','B']){const v=doc.getElementById('vid'+k),n=nodes[k];if(!v)continue;const deck=clamp(value('gain'+k,100)/100,0,1),level=clamp(master*deck*factor(k),0,1);try{v.preservesPitch=true;v.webkitPreservesPitch=true}catch(e){}if(n){n.deckGain.gain.value=level;n.lo.gain.value=value('afdEqBass'+k,0);n.mid.gain.value=value('afdEqMid'+k,0);n.hi.gain.value=value('afdEqTreble'+k,0)}else v.volume=level}
 const r=doc.getElementById('afdMasterRead');if(r)r.textContent=Math.round(master*100)+'%';applyVideo();publish(force)
}
function bindMedia(k,n){const v=n.v;if(v.dataset.afd184v2)return;v.dataset.afd184v2='1';v.addEventListener('play',()=>{resume();if(key[k]!==0)activateProcessed(k).catch(e=>{safeGate(k,false);status('HQ KEY ERROR • '+e.message)})});v.addEventListener('pause',()=>{if(key[k]!==0)stopProcessed(k)});v.addEventListener('seeked',()=>{if(key[k]!==0&&!v.paused)activateProcessed(k,true).catch(()=>safeGate(k,false))});v.addEventListener('ratechange',()=>{if(key[k]!==0&&!v.paused)activateProcessed(k,true).catch(()=>safeGate(k,false))});v.addEventListener('ended',()=>stopProcessed(k));v.addEventListener('loadedmetadata',()=>resetDeckProcess(k))}
async function ensureGraph(){
 if(ctx)return;doc=D();win=W();if(!doc||!win)return;doc.documentElement.dataset.afd156='1';const AC=win.AudioContext||win.webkitAudioContext;if(!AC)return;ctx=new AC({latencyHint:'playback'});await ensureSignalsmith();
 for(const k of ['A','B']){const v=doc.getElementById('vid'+k);if(!v)continue;try{const src=ctx.createMediaElementSource(v),nativeGate=ctx.createGain(),processedGate=ctx.createGain(),analyser=ctx.createAnalyser(),lo=ctx.createBiquadFilter(),mid=ctx.createBiquadFilter(),hi=ctx.createBiquadFilter(),deckGain=ctx.createGain();lo.type='lowshelf';lo.frequency.value=250;mid.type='peaking';mid.frequency.value=1000;mid.Q.value=.8;hi.type='highshelf';hi.frequency.value=4000;nativeGate.gain.value=1;processedGate.gain.value=0;analyser.fftSize=256;src.connect(nativeGate).connect(lo);processedGate.connect(lo);lo.connect(mid).connect(hi).connect(deckGain).connect(ctx.destination);nodes[k]={v,src,nativeGate,processedGate,analyser,lo,mid,hi,deckGain,stretch:null,bufferId:'',loading:null,decoded:null,grid:null,processed:false};bindMedia(k,nodes[k])}catch(e){console.warn('Audio graph deck '+k,e)}}apply(true)
}
async function resume(){await ensureGraph();try{await ctx?.resume()}catch(e){}apply()}
function safeGate(k,processed){const n=nodes[k];if(!n||!ctx)return;n.processed=!!processed;const t=ctx.currentTime;n.nativeGate.gain.cancelScheduledValues(t);n.processedGate.gain.cancelScheduledValues(t);n.nativeGate.gain.setValueAtTime(n.nativeGate.gain.value,t);n.processedGate.gain.setValueAtTime(n.processedGate.gain.value,t);n.nativeGate.gain.linearRampToValueAtTime(processed?0:1,t+.055);n.processedGate.gain.linearRampToValueAtTime(processed?1:0,t+.055)}
async function fetchDecoded(k){
 const n=nodes[k],v=n?.v;if(!n||!v)throw Error('Deck audio not ready');if(n.decoded)return n.decoded;const meta=metaFor(k),bridge=window.afdDesktopMedia;
 if(meta&&bridge){try{const res=meta.path?await bridge.prepareKeyPath(meta):await bridge.prepareKey(meta);if(res?.url){const r=await fetch(res.url);if(!r.ok)throw Error('HQ audio '+r.status);const ab=await r.arrayBuffer();n.decoded=await ctx.decodeAudioData(ab.slice(0));return n.decoded}}catch(e){console.warn('Key bridge decode',e)}}
 const direct=String(v.currentSrc||v.src||'');if(!direct)throw Error('Audio source unavailable');const r=await fetch(direct);if(!r.ok)throw Error('Audio fetch '+r.status);const ab=await r.arrayBuffer();n.decoded=await ctx.decodeAudioData(ab.slice(0));return n.decoded
}
async function disposeStretch(k){const n=nodes[k];if(!n)return;safeGate(k,false);if(n.stretch){try{await n.stretch.stop?.()}catch(e){}try{n.stretch.disconnect()}catch(e){}try{await n.stretch.dropBuffers?.()}catch(e){}}n.stretch=null;n.bufferId='';n.loading=null;n.processed=false}
async function prepareBuffer(k){
 await resume();const n=nodes[k];if(!n)throw Error('Deck graph unavailable');const id=mediaIdentity(k);if(!id)throw Error('No local track in Deck '+k);if(n.stretch&&n.bufferId===id)return n.stretch;if(n.loading)return n.loading;const my=serial[k];
 n.loading=(async()=>{status('DECK '+k+' • מכין HQ KEY...');const audio=await fetchDecoded(k);if(my!==serial[k])throw Error('Cancelled');await disposeStretch(k);if(typeof win.SignalsmithStretch!=='function')throw Error('Signalsmith unavailable');const stretch=await win.SignalsmithStretch(ctx);try{await stretch.configure({blockMs:260,intervalMs:65,splitComputation:true})}catch(e){}const arrays=[];for(let c=0;c<Math.min(2,audio.numberOfChannels);c++)arrays.push(new Float32Array(audio.getChannelData(c)));if(arrays.length===1)arrays.push(new Float32Array(arrays[0]));await stretch.addBuffers(arrays,arrays.map(a=>a.buffer));try{stretch.setUpdateInterval?.(.08)}catch(e){}stretch.connect(n.analyser);n.analyser.connect(n.processedGate);n.stretch=stretch;n.bufferId=id;status('DECK '+k+' • HQ KEY READY');return stretch})();
 try{return await n.loading}finally{n.loading=null}
}
function processedHasSignal(k){const n=nodes[k];if(!n?.analyser)return false;const a=new Float32Array(n.analyser.fftSize);n.analyser.getFloatTimeDomainData(a);let s=0;for(const x of a)s+=x*x;return Math.sqrt(s/a.length)>0.00008}
async function stopProcessed(k){const n=nodes[k];if(!n?.stretch)return;try{await n.stretch.schedule({output:ctx.currentTime+.02,active:false},true)}catch(e){try{await n.stretch.stop?.(ctx.currentTime+.02)}catch(x){}}safeGate(k,false)}
async function activateProcessed(k,forceSeek=false){
 const n=nodes[k],v=n?.v;if(!n||!v||key[k]===0||online(k))return false;const st=await prepareBuffer(k);if(!st)return false;const my=serial[k],lat=Math.max(.08,Number(st.latency?.()||.16)),when=ctx.currentTime+lat+.04,rate=clamp(Number(v.playbackRate)||1,.25,4),input=Math.max(0,(Number(v.currentTime)||0)+(when-ctx.currentTime)*rate);
 try{await st.schedule({output:when,active:true,input,rate,semitones:key[k],tonalityHz:10000,formantCompensation:true,formantBaseHz:0},true)}catch(e){safeGate(k,false);throw e}
 if(n.processed&&!forceSeek)return true;
 const deadline=performance.now()+2200;await sleep(Math.max(80,(when-ctx.currentTime)*1000+90));while(performance.now()<deadline&&my===serial[k]&&key[k]!==0&&!v.paused){if(processedHasSignal(k)){safeGate(k,true);return true}await sleep(60)}safeGate(k,false);if(!v.paused)status('HQ KEY • המקור נשאר פעיל כי הערוץ המעובד עדיין לא מוכן');return false
}
async function resetDeckProcess(k){serial[k]++;key[k]=0;const n=nodes[k];if(n){n.decoded=null;n.grid=null;await disposeStretch(k)}const r=doc?.getElementById('afdDeckKeyRead'+k);if(r)r.textContent='0'}
async function setTone(k,n,announce=true){
 n=clamp(Math.round(Number(n)||0),-12,12);key[k]=n;const read=doc?.getElementById('afdDeckKeyRead'+k);if(read)read.textContent=(n>0?'+':'')+n;if(online(k)){if(announce)status('KEY • זמין לקבצים מקומיים בלבד');return false}await resume();if(n===0){await stopProcessed(k);if(announce)status('DECK '+k+' • KEY 0');return true}
 try{const node=nodes[k];if(node?.processed&&node.stretch){const when=ctx.currentTime+Math.max(.08,Number(node.stretch.latency?.()||.15));await node.stretch.schedule({output:when,semitones:n,tonalityHz:10000,formantCompensation:true,formantBaseHz:0},false);if(announce)status('DECK '+k+' • HQ KEY '+(n>0?'+':'')+n);return true}await prepareBuffer(k);if(nodes[k]?.v&&!nodes[k].v.paused)await activateProcessed(k);if(announce)status('DECK '+k+' • HQ KEY '+(n>0?'+':'')+n);return true}catch(e){safeGate(k,false);status('HQ KEY ERROR • '+(e?.message||e)+' • ממשיך באודיו המקורי');return false}
}
function changeTone(k,d){setTone(k,key[k]+d)}
function cleanupKeyLayout(){if(!doc)return;for(const id of ['afdMasterKeyWrap182','afdMasterKeyWrap181']){const wrap=doc.getElementById(id);if(wrap){const s=wrap.querySelector('.masterScreen');if(s&&wrap.parentElement)wrap.parentElement.insertBefore(s,wrap);wrap.remove()}}doc.querySelectorAll('.afdDeckKey184,.afdKeyCtl176,.afdHQKey181,.afdHQKey182').forEach(e=>e.remove());doc.querySelectorAll('.afdKeyRowA184,.afdKeyRowB184').forEach(e=>e.classList.remove('afdKeyRowA184','afdKeyRowB184'))}
function makeSideKey(k){const box=doc.createElement('div');box.id='afdDeckKey'+k;box.className='afdDeckKeySide184';box.innerHTML='<small>KEY</small><button data-d="1">＋</button><strong id="afdDeckKeyRead'+k+'">0</strong><button data-d="-1">−</button>';box.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();changeTone(k,Number(b.dataset.d))}));box.querySelector('strong').addEventListener('click',()=>setTone(k,0));return box}
function keyUI(k){const root=doc?.querySelector('.deck'+k),row=root?.querySelector('.screenRow'),side=row?.querySelector('.side');if(!row||!side)return;let box=doc.getElementById('afdDeckKey'+k);if(!box||!box.classList.contains('afdDeckKeySide184')){box?.remove();box=makeSideKey(k)}const oldKey=[...side.querySelectorAll('.mini')].find(b=>/^KEY$/i.test(b.textContent.trim()));if(oldKey)oldKey.replaceWith(box);else if(!side.contains(box))side.appendChild(box);const r=doc.getElementById('afdDeckKeyRead'+k);if(r)r.textContent=(key[k]>0?'+':'')+key[k]}
function styleLayout(){if(!doc?.head)return;let s=doc.getElementById('afdLayout184v2');if(!s){s=doc.createElement('style');s.id='afdLayout184v2';doc.head.appendChild(s)}s.textContent=`
html body .console{grid-template-columns:minmax(0,1fr) minmax(0,1.38fr) minmax(0,1fr)!important;gap:5px!important}
html body .screenRow{grid-template-columns:48px minmax(0,1fr) 48px!important;gap:5px!important;width:100%!important}
.deckA .screenRow>.side{grid-column:1!important;grid-row:1!important}.deckA .screenRow>.screen{grid-column:2!important;grid-row:1!important}.deckA .screenRow>.eq{grid-column:3!important;grid-row:1!important}
.deckB .screenRow>.eq{grid-column:1!important;grid-row:1!important}.deckB .screenRow>.screen{grid-column:2!important;grid-row:1!important}.deckB .screenRow>.side{grid-column:3!important;grid-row:1!important}
.screenRow>.screen{width:100%!important;min-width:0!important;height:100%!important}.screenRow>.screen video,.screenRow>.screen iframe{width:100%!important;height:100%!important;inset:0!important}
.master{padding-left:5px!important;padding-right:5px!important}.masterScreen{width:100%!important;max-width:none!important;height:310px!important}.masterScreen video,.masterScreen iframe{width:100%!important;height:100%!important;object-fit:contain!important}
.afdDeckKeySide184{flex:1.45;min-height:84px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;border:1px solid #596470;border-radius:9px;background:linear-gradient(#1b2129,#080a0e);box-shadow:inset 0 1px #ffffff22;color:#fff;padding:3px 2px}.afdDeckKeySide184 small{font-size:6px;font-weight:1000;color:#c8d2dc}.afdDeckKeySide184 button{width:31px;height:22px!important;min-height:22px!important;padding:0!important;border:1px solid #7a8591;border-radius:9px!important;background:linear-gradient(#414b56,#151a20);color:#fff;font-size:15px!important;line-height:1;font-weight:1000}.afdDeckKeySide184 strong{width:31px;height:20px;display:grid;place-items:center;border:1px solid #72558a;border-radius:8px;background:#050609;color:#efd8ff;font-size:9px;cursor:pointer}.deckB .afdDeckKeySide184 strong{color:#cbefff;border-color:#47768e}
.side{gap:3px!important}.side>.mini{min-height:25px!important;font-size:6px!important}.pads{margin:4px 0!important}.pad{height:20px!important}.masterScreen{margin-top:5px!important}
@media(max-width:900px){html body .console{grid-template-columns:minmax(0,1fr) minmax(0,1.28fr) minmax(0,1fr)!important}.screenRow{grid-template-columns:40px minmax(0,1fr) 40px!important}.afdDeckKeySide184 button,.afdDeckKeySide184 strong{width:27px!important}.masterScreen{height:275px!important}}
`}
function labelCross(){const c=doc?.getElementById('cross'),wrap=c?.closest('.cross');if(!c||!wrap)return;const labs=[...wrap.children].filter(x=>x!==c&&x.tagName!=='INPUT');if(labs.length>=2){labs[0].textContent='B';labs[labs.length-1].textContent='A'}c.title='שמאל: Deck B • ימין: Deck A'}
function hasSource(k){const v=doc?.getElementById('vid'+k);return!!((v&&(v.currentSrc||v.src))||doc?.getElementById('ytDeck'+k)||doc?.getElementById('afdSP105Deck'+k))}
function playing(k){const v=doc?.getElementById('vid'+k);return!!((v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||window.AFDYouTubeState?.isPlaying?.(k)||window.AFDSpotifyState?.isPlaying?.(k))}
function startDeck(k){if(playing(k))return true;const b=doc?.querySelector('.deck'+k+' [data-act="play"]');if(!b)return false;b.click();return true}
function cancelMix(){if(mixRaf){try{win.cancelAnimationFrame(mixRaf)}catch(e){}mixRaf=0}mixBusy=false;doc?.getElementById('afdMixBtn')?.classList.remove('on')}
function startMix(){if(mixBusy)return;const from=mix>=.5?'A':'B',to=from==='A'?'B':'A',target=to==='A'?1:0;if(!hasSource(to)){status('MIX • אין שיר ב-DECK '+to);return}if(!playing(to))startDeck(to);const start=clamp(mix,0,1);mixBusy=true;const btn=doc.getElementById('afdMixBtn');btn?.classList.add('on');const t0=performance.now(),dur=2200;const tick=t=>{if(!mixBusy)return;const p=Math.min(1,(t-t0)/dur),q=p*p*(3-2*p);mix=start+(target-start)*q;const c=doc.getElementById('cross');if(c)c.value=String(mix*100);const vc=doc.getElementById('videoCross');if(vc)vc.value=String(mix*100);apply(true);if(p<1)mixRaf=win.requestAnimationFrame(tick);else{mix=target;apply(true);mixBusy=false;mixRaf=0;btn?.classList.remove('on');status('MIX • DECK '+to+' פעיל • DECK '+from+' ממשיך לנגן בשקט')}};mixRaf=win.requestAnimationFrame(tick)}
function bindMix(){const c=doc?.getElementById('cross');if(c&&!c.dataset.afd184v2){c.dataset.afd184v2='1';mix=clamp((+c.value||0)/100,0,1);['input','change'].forEach(ev=>c.addEventListener(ev,e=>{e.stopImmediatePropagation();cancelMix();mix=clamp((+c.value||0)/100,0,1);const vc=doc.getElementById('videoCross');if(vc)vc.value=c.value;resume().then(()=>apply(true))},true))}const old=doc?.getElementById('afdMixBtn');if(old&&!old.dataset.afd184v2){const b=old.cloneNode(true);old.replaceWith(b);b.dataset.afd184v2='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();resume().then(startMix)},true)}labelCross()}
function envelope(audio,bpm){const ch=audio.getChannelData(0),sr=audio.sampleRate,step=1024,max=Math.min(ch.length,Math.floor(sr*35)),env=[];let prev=0;for(let i=0;i<max;i+=step){let e=0,c=0;for(let j=i;j<Math.min(i+step,max);j+=4){const x=ch[j];e+=x*x;c++}e=Math.sqrt(e/Math.max(1,c));env.push(Math.max(0,e-prev*.92));prev=e}let b=bpm;if(!(b>20)){let best=-1,bestLag=0;const lo=Math.max(2,Math.round((60/190)*sr/step)),hi=Math.min(env.length-2,Math.round((60/70)*sr/step));for(let lag=lo;lag<=hi;lag++){let s=0;for(let i=lag;i<env.length;i++)s+=env[i]*env[i-lag];if(s>best){best=s;bestLag=lag}}b=bestLag?60*sr/(bestLag*step):120;while(b<70)b*=2;while(b>190)b/=2}const lag=Math.max(2,Math.round((60/b)*sr/step));let bestP=0,bestS=-1;for(let p=0;p<lag;p++){let s=0;for(let i=p;i<env.length;i+=lag)s+=env[i];if(s>bestS){bestS=s;bestP=p}}return{bpm:b,offset:bestP*step/sr}}
async function gridFor(k){await resume();const n=nodes[k];if(!n)throw Error('Deck '+k+' unavailable');const id=mediaIdentity(k);if(n.grid&&n.grid.id===id)return n.grid;status('SYNC • מנתח ביטים של DECK '+k+'...');const audio=await fetchDecoded(k),g=envelope(audio,baseBpm(k));n.grid={...g,id};const bpmEl=doc.getElementById('bpm'+k);if(bpmEl&&!baseBpm(k)){bpmEl.dataset.afdBaseBpm=String(g.bpm);bpmEl.textContent=g.bpm.toFixed(1)}return n.grid}
async function syncDeck(k){
 if(syncBusy[k])return;const master=k==='A'?'B':'A',tv=doc?.getElementById('vid'+k),mv=doc?.getElementById('vid'+master);if(!tv||!mv||!hasSource(k)||!hasSource(master)){status('SYNC • צריך שיר בשני הדקים');return}if(online(k)||online(master)){status('SYNC BEAT • זמין כרגע לקבצים מקומיים');return}syncBusy[k]=true;try{const [tg,mg]=await Promise.all([gridFor(k),gridFor(master)]),masterRate=clamp(Number(mv.playbackRate)||1,.5,2),wanted=(mg.bpm*masterRate)/tg.bpm,rate=clamp(wanted,.84,1.16);tv.playbackRate=rate;const p=doc.getElementById('pitch'+k);if(p)p.value=String((rate-1)*100);const pr=doc.getElementById('afdPitchRead'+k);if(pr)pr.textContent=((rate-1)*100>=0?'+':'')+((rate-1)*100).toFixed(1)+'%';const masterPeriod=60/mg.bpm,targetPeriod=60/tg.bpm,phase=((mv.currentTime-mg.offset)/masterPeriod%1+1)%1;let pos=tg.offset+phase*targetPeriod;const n=Math.max(0,Math.round((tv.currentTime-pos)/targetPeriod));pos+=n*targetPeriod;if(Number.isFinite(tv.duration)&&tv.duration>0)pos=clamp(pos,0,Math.max(0,tv.duration-.05));tv.currentTime=Math.max(0,pos);if(tv.paused)await tv.play().catch(()=>startDeck(k));if(key[k]!==0)await activateProcessed(k,true);status('SYNC • DECK '+k+' נעול ל-BPM ולביט של DECK '+master+(Math.abs(rate-wanted)>.002?' • הוגבל לטווח PITCH':'') )}catch(e){status('SYNC ERROR • '+(e?.message||e))}finally{syncBusy[k]=false}}
function bindSync(){for(const k of ['A','B']){const root=doc?.querySelector('.deck'+k),sync=root?.querySelector('.transport .sync,.transport [data-act="sync"],.afdSync148');if(!sync||sync.dataset.afd184sync)return;const b=sync.cloneNode(true);sync.replaceWith(b);b.dataset.afd184sync='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();syncDeck(k)},true)}}
function onlineHome(){try{window.AFDYouTubeHalfClose?.()}catch(e){}document.body.classList.remove('afdYTHalf113','afdSpotifyResults','afdSpotifyPlaylists');const online=document.getElementById('online');if(online){online.style.setProperty('display','grid','important');[...online.children].forEach(c=>c.style.removeProperty('display'));online.scrollTop=0}const p=document.getElementById('afdPL101Panel');if(p)p.style.display='none';status('ONLINE MUSIC • בחר YouTube או Spotify')}
function onlineButton(){const head=document.getElementById('afdOnlineHead170');if(!head)return;let b=document.getElementById('afdOnlineHome184');if(!b){b=document.createElement('button');b.id='afdOnlineHome184';b.textContent='🌐 ONLINE';b.title='חזרה לבחירת YouTube / Spotify';b.onclick=onlineHome;head.appendChild(b)}let st=document.getElementById('afdOnlineHomeStyle184');if(!st){st=document.createElement('style');st.id='afdOnlineHomeStyle184';st.textContent='#afdOnlineHead170{gap:10px!important}#afdOnlineHome184{margin-left:auto;height:23px;padding:0 12px;border:1px solid #8e7040;border-radius:5px;background:linear-gradient(#7e6227,#302109);color:#ffe4a0;font-size:8px;font-weight:1000}';document.head.appendChild(st)}}
function install(){const d=D(),w=W();if(!d||!w)return;if(doc&&doc!==d){try{ctx?.close()}catch(e){}ctx=null;nodes.A=nodes.B=null;signalsmithReady=false;lastPublished=-1}doc=d;win=w;cleanupKeyLayout();styleLayout();keyUI('A');keyUI('B');bindMix();bindSync();onlineButton();apply()}
function refresh(){install()}
function onLocalLoad(e){const k=e.detail?.deck;if(!['A','B'].includes(k))return;serial[k]++;key[k]=0;if(nodes[k]){nodes[k].decoded=null;nodes[k].grid=null;disposeStretch(k)}const r=doc?.getElementById('afdDeckKeyRead'+k);if(r)r.textContent='0'}
window.addEventListener('afd-local-load',onLocalLoad);window.addEventListener('afd-deck-eject',onLocalLoad);
const api={refresh,setTone,changeTone,getTone:k=>key[k]||0,startMix,syncDeck};window.__afdWin184V142=api;window.__afdWin184=api;window.__afdWin182=api;window.__afdWin181=api;window.__afdWin176=api;
frame()?.addEventListener('load',()=>setTimeout(install,100));install();setTimeout(install,400);setTimeout(install,1300);setInterval(()=>{install();apply()},1000);
})();