(()=>{
if(window.__afdWin192){window.__afdWin192.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const clean=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const HIST='afdPlaybackHistory192v1';
let history={},historyDate=null,spSearchItems=[],spotifyFetchBase=null;
const src={A:null,B:null},watch={A:{was:false,key:'',ts:0},B:{was:false,key:'',ts:0}};
try{const x=JSON.parse(localStorage.getItem(HIST)||'{}');if(x&&typeof x==='object')history=x}catch(e){}
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD HISTORY/SPOTIFY/UI 192]',t)}
function localDay(ts){const d=new Date(ts),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day}
function dayLabel(day){try{return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(day+'T12:00:00'))}catch(e){return day}}
function save(){try{const days=Object.keys(history).sort().slice(-180),o={};for(const d of days)o[d]=(history[d]||[]).slice(-1200);history=o;localStorage.setItem(HIST,JSON.stringify(history))}catch(e){}}
function sanitizeLocal(it){return{path:String(it?.path||''),key:String(it?.key||''),name:String(it?.name||it?.file?.name||''),folder:String(it?.folder||'History'),kind:String(it?.kind||'music')}}
function sanitizeYT(x){return{id:String(x?.id||x?.videoId||''),title:String(x?.title||x?.name||'YouTube'),thumb:String(x?.thumb||'')}}
function sanitizeSP(x){return{id:String(x?.id||''),uri:String(x?.uri||''),name:String(x?.name||'Spotify'),duration_ms:Number(x?.duration_ms)||0,artists:Array.isArray(x?.artists)?x.artists.map(a=>({name:String(a?.name||'')})):[],album:{name:String(x?.album?.name||''),images:Array.isArray(x?.album?.images)?x.album.images.slice(0,3).map(i=>({url:String(i?.url||''),width:i?.width||null,height:i?.height||null})):[]}}}
function itemKey(s,it){if(s==='Local')return'local:'+(it?.path||it?.key||it?.name||'');if(s==='YouTube')return'yt:'+(it?.id||it?.title||'');if(s==='Spotify')return'sp:'+(it?.id||it?.uri||it?.name||'');return s+':'+(it?.name||'')}
function deckPlaying(k){const d=D(),v=d?.getElementById('vid'+k);return!!((v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||window.AFDYouTubeState?.isPlaying?.(k)||window.AFDSpotifyState?.isPlaying?.(k))}
function deckPos(k){const d=D(),v=d?.getElementById('vid'+k);if(window.AFDSpotifyState?.has?.(k))return Number(window.AFDSpotifyState?.getTime?.(k)?.current)||0;if(d?.getElementById('ytDeck'+k))return Number(window.AFDYouTubeState?.getTime?.(k)?.current)||0;return Number(v?.currentTime)||0}
function fallbackSource(k){const d=D(),title=(d?.getElementById('title'+k)?.textContent||'').trim();const sp=window.AFDSpotifyState?.getLoaded?.(k);if(sp)return{source:'Spotify',item:sanitizeSP(sp)};if(d?.getElementById('ytDeck'+k))return{source:'YouTube',item:{id:'',title:title||'YouTube',thumb:''}};const m=window.AFDLocalDeckMeta?.[k];if(m)return{source:'Local',item:sanitizeLocal(m)};return null}
function record(k){const s=src[k]||fallbackSource(k);if(!s)return;const key=itemKey(s.source,s.item),name=s.source==='YouTube'?(s.item.title||'YouTube'):(s.item.name||'Track');if(!key||!name||/Drop a track/i.test(name))return;const now=Date.now(),w=watch[k],pos=deckPos(k);if(w.key===key&&pos>2)return;if(w.key===key&&now-w.ts<1800)return;const day=localDay(now),arr=history[day]||(history[day]=[]);arr.push({ts:now,time:new Date(now).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}),deck:k,name,source:s.source,key,item:s.item,path:s.source==='Local'?String(s.item.path||''):'',kind:s.source==='YouTube'?'video':'music'});w.key=key;w.ts=now;save();if(activeHistory())renderHistory();}
function watchPlay(){for(const k of ['A','B']){const on=deckPlaying(k),w=watch[k];if(on&&!w.was)record(k);w.was=on}}
window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')src[k]={source:'Local',item:sanitizeLocal(e.detail?.item||{})}});
window.addEventListener('afd-youtube-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')src[k]={source:'YouTube',item:sanitizeYT(e.detail||{})}});
window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')src[k]={source:'Spotify',item:sanitizeSP(e.detail?.item||{})}});
window.addEventListener('afd-deck-eject',e=>{const k=e.detail?.deck;if(k==='A'||k==='B'){src[k]=null;watch[k].was=false}});
function oldHistory(){try{const x=JSON.parse(localStorage.getItem('afdPlaybackHistory177v3')||'{}');return x&&typeof x==='object'?x:{}}catch(e){return{}}}
function mergedDay(day){const newer=(history[day]||[]).slice(),old=(oldHistory()[day]||[]);for(const x of old){const dup=newer.some(n=>n.name===x.name&&n.source===x.source&&Math.abs((Number(n.ts)||0)-(Number(x.ts)||0))<2500);if(!dup)newer.push({...x,item:x.source==='Local'?{path:x.path||'',name:x.name||'',folder:'History',kind:x.kind||'music'}:null,key:'legacy:'+(x.source||'')+':'+(x.name||'')+':'+(x.ts||'')})}return newer.sort((a,b)=>(a.ts||0)-(b.ts||0))}
function allDays(){return[...new Set([...Object.keys(oldHistory()),...Object.keys(history)])].filter(d=>mergedDay(d).length).sort().reverse()}
function activeHistory(){const d=D(),cat=d?.querySelector('#afdFolders170 [data-cat="history"]');return!!cat?.classList.contains('active')}
function canReload(x){if(x.source==='Local')return!!(x.item?.path||x.path);if(x.source==='YouTube')return!!x.item?.id;if(x.source==='Spotify')return!!(x.item?.id||x.item?.uri);return false}
async function loadEntry(deck,x){if(!x||!['A','B'].includes(deck))return false;try{if(x.source==='Local'){const it={key:x.item?.key||('history:'+String(x.item?.path||x.path||x.name)),path:x.item?.path||x.path||'',name:x.item?.name||x.name,folder:x.item?.folder||'History',kind:x.item?.kind||x.kind||'music'};if(!it.path)throw Error('אין נתיב לקובץ ההיסטורי');return await window.AFDWindowsLoadItem?.(deck,it)}if(x.source==='YouTube'){const it={id:x.item?.id,title:x.item?.title||x.name,thumb:x.item?.thumb||''};if(!it.id)throw Error('להשמעה ישנה אין מזהה YouTube שמור');return await window.AFDYouTubeState?.load?.(deck,it)}if(x.source==='Spotify'){const it=x.item;if(!it?.id&&!it?.uri)throw Error('להשמעה ישנה אין מזהה Spotify שמור');window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck,item:it}}));return true}}catch(e){status('HISTORY LOAD ERROR • '+(e?.message||e));return false}return false}
function queueItem(x,day){if(x.source==='Local')return{key:'hist192:'+x.key,path:x.item?.path||x.path||'',name:x.item?.name||x.name,folder:'History '+day,kind:x.item?.kind||x.kind||'music',afdHistorySource:'Local',afdHistoryItem:x.item||null};if(x.source==='YouTube'&&x.item?.id)return{key:'hist192:'+x.key,name:x.item.title||x.name,folder:'History '+day,kind:'video',afdHistorySource:'YouTube',afdHistoryItem:x.item};if(x.source==='Spotify'&&(x.item?.id||x.item?.uri))return{key:'hist192:'+x.key,name:x.item.name||x.name,folder:'History '+day,kind:'music',afdHistorySource:'Spotify',afdHistoryItem:x.item};return null}
function addSide(x,day,refresh=true){const q=window.__afdWin170?.queue;if(!q)return false;const it=queueItem(x,day);if(!it)return false;if(!q.some(a=>a.key===it.key))q.push(it);if(refresh)window.__afdWin170?.refresh?.();return true}
function addDay(day){let n=0;for(const x of mergedDay(day))if(addSide(x,day,false))n++;window.__afdWin170?.refresh?.();setTimeout(renderHistory,80);status('HISTORY • הועברו '+n+' שירים מ-'+day+' ל-SIDEVIEW')}
async function loadQueue(deck,it){if(!it?.afdHistorySource)return false;const x={source:it.afdHistorySource,item:it.afdHistoryItem,name:it.name,path:it.path,kind:it.kind,key:it.key};return loadEntry(deck,x)}
function wrapWindowsLoader(){if(!window.AFDWindowsLoadItem||window.AFDWindowsLoadItem.__afd192)return;const base=window.AFDWindowsLoadItem;const fn=async(deck,it)=>it?.afdHistorySource?loadQueue(deck,it):base(deck,it);fn.__afd192=true;fn.__afdBase=base;window.AFDWindowsLoadItem=fn}
function installQueueButtons(){const d=D();if(!d||d.documentElement.dataset.afdHistQueue192)return;d.documentElement.dataset.afdHistQueue192='1';d.addEventListener('click',e=>{const b=e.target?.closest?.('.afdQ170 [data-qdeck]');if(!b)return;const row=b.closest('.afdQ170'),i=Number(row?.dataset.i),it=window.__afdWin170?.queue?.[i];if(!it?.afdHistorySource)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadQueue(b.dataset.qdeck,it)},true)}
function historyStyle(){const d=D();if(!d?.head)return;let s=d.getElementById('afdHistory192Style');if(!s){s=d.createElement('style');s.id='afdHistory192Style';d.head.appendChild(s)}s.textContent=`.afdHist192Head{display:grid;grid-template-columns:95px minmax(0,1fr) 150px 95px;gap:6px;align-items:center;padding:7px;background:#171e26;border-bottom:1px solid #313943;position:sticky;top:0;z-index:5}.afdHist192Head button{height:28px!important;font-size:8px!important}.afdHist192Head b{text-align:center}.afdHist192Day{display:grid;grid-template-columns:34px minmax(0,1fr) 180px;gap:8px;align-items:center;padding:9px;border-bottom:1px solid #202730;cursor:pointer}.afdHist192Day:hover{background:#242d38}.afdHist192Track{display:grid;grid-template-columns:30px 54px minmax(150px,1fr) 105px 38px 38px 52px;gap:5px;align-items:center;padding:6px;border-bottom:1px solid #20262d;direction:ltr}.afdHist192Track b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer}.afdHist192Track small{font-size:7px;color:#9aa6b2}.afdHist192Track button{height:25px!important;font-size:7px!important}.afdHist192Track .disabled{opacity:.4;pointer-events:none}@media(max-width:1000px){.afdHist192Track{grid-template-columns:26px 48px minmax(120px,1fr) 82px 34px 34px 46px}.afdHist192Head{grid-template-columns:80px minmax(0,1fr) 120px 80px}}`}
function renderHistory(){const d=D(),host=d?.getElementById('afdTracks170');if(!d||!host||!activeHistory())return;historyStyle();if(historyDate){const arr=mergedDay(historyDate);host.innerHTML='<div class="afdHist192Head"><button id="afdHist192Back">◀ תאריכים</button><b>'+clean(dayLabel(historyDate))+'</b><button id="afdHist192All">＋ כל היום ל-SIDEVIEW</button><span>'+arr.length+' השמעות</span></div>'+(arr.length?arr.map((x,i)=>'<div class="afdHist192Track" data-i="'+i+'"><span>'+String(i+1).padStart(2,'0')+'</span><time>'+clean(x.time||'')+'</time><b title="דאבל-קליק לטעינה ל-Deck A">'+clean(x.name||'Track')+'</b><small>'+clean(x.source||'')+' • Deck '+clean(x.deck||'')+'</small><button data-hd="A" class="'+(!canReload(x)?'disabled':'')+'">A</button><button data-hd="B" class="'+(!canReload(x)?'disabled':'')+'">B</button><button data-side="1" class="'+(!canReload(x)?'disabled':'')+'">＋SIDE</button></div>').join(''):'<div class="afdEmpty170">אין השמעות ביום הזה.</div>');d.getElementById('afdHist192Back')?.addEventListener('click',()=>{historyDate=null;renderHistory()});d.getElementById('afdHist192All')?.addEventListener('click',()=>addDay(historyDate));host.querySelectorAll('.afdHist192Track').forEach(r=>{const x=arr[+r.dataset.i];r.querySelectorAll('[data-hd]').forEach(b=>b.addEventListener('click',()=>loadEntry(b.dataset.hd,x)));r.querySelector('[data-side]')?.addEventListener('click',()=>{if(addSide(x,historyDate))status('HISTORY • '+x.name+' נוסף ל-SIDEVIEW')});r.querySelector('b')?.addEventListener('dblclick',()=>loadEntry('A',x))});return}const days=allDays();host.innerHTML=days.length?'<div class="afdSavedPLHint177">HISTORY • בחר תאריך • השירים החדשים נשמרים עם קיצור דרך לטעינה חוזרת</div>'+days.map(day=>{const a=mergedDay(day),first=a[0]?.time||'',last=a[a.length-1]?.time||'';return'<div class="afdHist192Day" data-day="'+day+'"><span>🕘</span><b>'+clean(dayLabel(day))+'</b><small>'+a.length+' שירים • '+clean(first)+(last&&last!==first?'–'+clean(last):'')+'</small></div>'}).join(''):'<div class="afdEmpty170">אין עדיין היסטוריית השמעות.</div>';host.querySelectorAll('.afdHist192Day').forEach(r=>r.addEventListener('click',()=>{historyDate=r.dataset.day;renderHistory()}))}
function bindHistoryCategory(){const d=D();if(!d||d.documentElement.dataset.afdHist192)return;d.documentElement.dataset.afdHist192='1';d.addEventListener('click',e=>{if(e.target?.closest?.('#afdFolders170 [data-cat="history"]')){historyDate=null;setTimeout(renderHistory,70)}},true)}
function installSyncUI(){const d=D();if(!d)return;let s=d.getElementById('afdSyncUnder192Style');if(!s){s=d.createElement('style');s.id='afdSyncUnder192Style';d.head.appendChild(s)}s.textContent=`.transport{grid-template-columns:minmax(58px,1.08fr) minmax(48px,.9fr) minmax(66px,1.05fr) minmax(46px,.78fr) minmax(120px,1.9fr)!important;grid-template-rows:32px 32px!important;gap:4px!important;min-height:68px!important}.transport>.afdPlay175{grid-column:1!important;grid-row:1/3!important;height:68px!important}.transport>.afdPause175{grid-column:2!important;grid-row:1/3!important;height:68px!important}.transport>.afdStop175{grid-column:3!important;grid-row:1!important;height:32px!important;min-height:32px!important}.transport>.afdSyncUnder192{grid-column:3!important;grid-row:2!important;height:32px!important;min-height:32px!important;border:1px solid #9d78d1!important;border-radius:5px!important;background:linear-gradient(#8157bc,#382156 65%,#130b1f)!important;color:#fff!important;font-size:9px!important;font-weight:1000!important;box-shadow:inset 0 1px #ffffff55,0 2px #000!important}.deckB .transport>.afdSyncUnder192{border-color:#49aee3!important;background:linear-gradient(#318fc0,#154866 65%,#071b29)!important}.transport>.afdEject175{grid-column:4!important;grid-row:1/3!important;height:68px!important}.transport>.afdPitchInline175{grid-column:5!important;grid-row:1/3!important;height:68px!important}.transport>.afdSync175,.transport>.afdSync190,.transport>.sync[data-act="sync"]{display:none!important}@media(max-width:1000px){.transport{grid-template-columns:minmax(50px,1fr) minmax(43px,.84fr) minmax(58px,1fr) minmax(42px,.74fr) minmax(98px,1.7fr)!important}.transport>.afdSyncUnder192{font-size:8px!important}}`;
 for(const k of ['A','B']){const t=d.querySelector('.deck'+k+' .transport');if(!t)continue;let b=d.getElementById('afdSyncUnder192'+k);if(!b){b=d.createElement('button');b.id='afdSyncUnder192'+k;b.className='afdSyncUnder192';b.textContent='SYNC';b.title='סנכרן את Deck '+k+' ל-Deck השני';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const api=window.__afdWin190;if(api?.syncDeck)api.syncDeck(k);else status('SYNC • מנוע הסנכרון עדיין נטען')},true);t.appendChild(b)}}}
function installSpotifyCapture(){if(window.__afdSPFetch192)return;spotifyFetchBase=window.__afdSpotifyOriginalFetch189||window.fetch.bind(window);window.__afdSPFetch192=spotifyFetchBase;window.__afdSpotifyOriginalFetch189=async(...a)=>{const r=await spotifyFetchBase(...a);try{const raw=typeof a[0]==='string'||a[0] instanceof URL?String(a[0]):a[0]?.url,u=new URL(raw,location.href);if(u.hostname==='api.spotify.com'&&u.pathname==='/v1/search'){r.clone().json().then(j=>{spSearchItems=Array.isArray(j?.tracks?.items)?j.tracks.items:[];setTimeout(bindSpotifyRows,20)}).catch(()=>{})}}catch(e){}return r}}
function bindSpotifyRows(){document.querySelectorAll('#afdSP191Body .afdSP191Card,#afdSP191Body .afdSP191Row').forEach(el=>{if(el.dataset.afdDrag192)return;el.dataset.afdDrag192='1';el.draggable=true;el.title='גרור ל-Deck A או B';el.addEventListener('dragstart',e=>{const it=spSearchItems[Number(el.dataset.i)];if(!it)return;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-afd-spotify-item',JSON.stringify(it));e.dataTransfer.setData('text/plain','spotify:'+String(it.id||it.uri||it.name||''))})})}
function installSpotifyDeckDrop(){const d=D();if(!d||d.documentElement.dataset.afdSPDrop192)return;d.documentElement.dataset.afdSPDrop192='1';for(const k of ['A','B']){const root=d.querySelector('.deck'+k);if(!root)continue;root.addEventListener('dragover',e=>{if([...(e.dataTransfer?.types||[])].includes('application/x-afd-spotify-item')){e.preventDefault();e.dataTransfer.dropEffect='copy'}},true);root.addEventListener('drop',e=>{const raw=e.dataTransfer?.getData('application/x-afd-spotify-item');if(!raw)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{const it=JSON.parse(raw);window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:k,item:it}}));status('Spotify • '+(it.name||'Track')+' → DECK '+k)}catch(x){status('Spotify drag error')}},true)}}
function refresh(){wrapWindowsLoader();installQueueButtons();bindHistoryCategory();installSyncUI();installSpotifyCapture();bindSpotifyRows();installSpotifyDeckDrop();if(activeHistory())renderHistory()}
window.__afdWin192={refresh,renderHistory,loadEntry,addDay};
frame()?.addEventListener('load',()=>setTimeout(refresh,250));refresh();setTimeout(refresh,650);setInterval(()=>{watchPlay();refresh()},350);
})();
