(()=>{
if(window.__afdWin194){window.__afdWin194.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const mod=(n,m)=>((n%m)+m)%m;
const clean=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const HIST='afdPlaybackHistory192v1';
let drag=null,mixBusy=false,mixRaf=0,nextCursor=0,autoMode=false,autoBusy=false;
const syncLocks={A:null,B:null},srcMeta={A:null,B:null},histWatch={A:{playing:false,key:''},B:{playing:false,key:''}};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD UNIFIED 194]',t)}
function Q(){return window.__afdWin170?.queue||[]}
function ITEMS(){return window.__afdWin170?.items||[]}
function BPMAPI(){return window.__afdCore195||window.__afdWin190||null}
function deckMedia(k){return D()?.getElementById('vid'+k)||null}
function hasSP(k){return!!window.AFDSpotifyState?.has?.(k)}
function hasYT(k){return!!D()?.getElementById('ytDeck'+k)}
function hasLocal(k){const v=deckMedia(k);return!!(v&&(v.currentSrc||v.src))&&!hasSP(k)&&!hasYT(k)}
function hasSource(k){return hasSP(k)||hasYT(k)||!!(deckMedia(k)?.currentSrc||deckMedia(k)?.src)}
function isPlaying(k){const v=deckMedia(k),native=!!(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended);return native||!!window.AFDYouTubeState?.isPlaying?.(k)||!!window.AFDSpotifyState?.isPlaying?.(k)}
function crossEl(){return D()?.getElementById('cross')||null}
function crossValue(){return clamp(Number(crossEl()?.value??50)||0,0,100)}
function activeDeck(){const a=isPlaying('A'),b=isPlaying('B'),x=crossValue();if(a&&!b)return'A';if(b&&!a)return'B';return x>=50?'A':'B'}
function sourceEndpoint(k){return k==='A'?100:0}
function directLevels(x){x=clamp(Number(x)||0,0,100);try{window.AFDSpotifyState?.setLevel?.('A',x/100);window.AFDSpotifyState?.setLevel?.('B',1-x/100)}catch(e){}try{window.AFDYouTubeState?.applyCross?.(x)}catch(e){}}
function setCross(x,finish=false){x=clamp(Number(x)||0,0,100);const d=D(),c=d?.getElementById('cross'),vc=d?.getElementById('videoCross');if(c){c.value=String(x);c.dispatchEvent(new Event('input',{bubbles:true}));if(finish)c.dispatchEvent(new Event('change',{bubbles:true}))}if(vc&&vc!==c){vc.value=String(x);vc.dispatchEvent(new Event('input',{bubbles:true}));if(finish)vc.dispatchEvent(new Event('change',{bubbles:true}))}directLevels(x)}
function itemByKey(key){return ITEMS().find(x=>String(x.key)===String(key))||null}
function queueClone(it){const n={...it};n._afdQid='q194:'+Date.now()+':'+Math.random().toString(36).slice(2);return n}
function addQueue(it){if(!it)return false;Q().push(queueClone(it));renderQueue();status('SIDEVIEW • נוסף '+(it.name||'שיר')+' • '+Q().length+' שירים');return true}
function removeQueue(i){const q=Q();if(i<0||i>=q.length)return;q.splice(i,1);if(nextCursor>=q.length)nextCursor=Math.max(0,q.length-1);renderQueue()}
function moveQueue(from,to){const q=Q();if(!Number.isInteger(from)||!Number.isInteger(to)||from===to||!q[from]||to<0||to>=q.length)return;const [it]=q.splice(from,1);q.splice(to,0,it);if(nextCursor===from)nextCursor=to;else if(from<nextCursor&&to>=nextCursor)nextCursor--;else if(from>nextCursor&&to<=nextCursor)nextCursor++;renderQueue();status('SIDEVIEW • הסדר עודכן')}
async function loadHistorySource(deck,it){const s=it?.afdHistorySource,x=it?.afdHistoryItem||{};if(s==='Local'){const local={...x,key:x.key||it.key,path:x.path||it.path||'',name:x.name||it.name,folder:x.folder||it.folder||'History',kind:x.kind||it.kind||'music'};return typeof window.AFDWindowsLoadItem==='function'?(await window.AFDWindowsLoadItem(deck,local))!==false:false}if(s==='Spotify'){if(!x.id&&!x.uri)return false;window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck,item:x}}));return true}if(s==='YouTube'){const yt={id:x.id||x.videoId||'',title:x.title||x.name||it.name,thumb:x.thumb||''};if(!yt.id)return false;return (await window.AFDYouTubeState?.load?.(deck,yt))!==false}return false}
async function loadItem(deck,it){if(!it||!['A','B'].includes(deck))return false;try{if(it.afdHistorySource)return await loadHistorySource(deck,it);if(it.afdSpotifyItem||it.spotifyItem){const sp=it.afdSpotifyItem||it.spotifyItem;window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck,item:sp}}));return true}if(it.afdYouTubeItem||it.youtubeItem){const yt=it.afdYouTubeItem||it.youtubeItem;return await window.AFDYouTubeState?.load?.(deck,yt)}if(typeof window.AFDWindowsLoadItem==='function')return (await window.AFDWindowsLoadItem(deck,it))!==false;return false}catch(e){status('LOAD ERROR • '+(e?.message||e));return false}}
async function waitSource(deck,ms=12000){const end=performance.now()+ms;while(performance.now()<end){if(hasSource(deck))return true;await sleep(70)}return hasSource(deck)}
async function waitPlaying(deck,ms=9000){const end=performance.now()+ms;while(performance.now()<end){if(isPlaying(deck))return true;await sleep(70)}return isPlaying(deck)}
async function startTarget(deck){if(isPlaying(deck))return true;try{if(hasSP(deck)){window.AFDSpotifyState?.setLevel?.(deck,0);window.AFDSpotifyState?.play?.(deck);return await waitPlaying(deck,9000)}if(hasLocal(deck)){const v=deckMedia(deck);try{v.volume=0}catch(e){}try{await v.play()}catch(e){}if(await waitPlaying(deck,1800))return true}const d=D(),b=d?.querySelector('.deck'+deck+' [data-act="play"],.deck'+deck+' .afdPlay175,.deck'+deck+' .transport .play');if(b){b.click();return await waitPlaying(deck,9000)}}catch(e){}return false}
async function mixTo(to,duration=5600){if(mixBusy)return false;const from=to==='A'?'B':'A';if(!hasSource(to)){status('MIX • אין שיר ב-DECK '+to);return false}mixBusy=true;try{const start=sourceEndpoint(from),target=sourceEndpoint(to);setCross(start,true);try{if(hasSP(to))window.AFDSpotifyState?.setLevel?.(to,0);else{const v=deckMedia(to);if(v)v.volume=0}}catch(e){}status('MIX • מפעיל DECK '+to+' בשקט...');const ok=await startTarget(to);if(!ok){setCross(start,true);status('MIX • DECK '+to+' לא התחיל');return false}await sleep(220);const w=frame()?.contentWindow||window,t0=performance.now();await new Promise(resolve=>{const tick=t=>{if(!mixBusy)return resolve();const p=Math.min(1,(t-t0)/duration),q=p*p*(3-2*p),x=start+(target-start)*q;setCross(x,false);if(p<1)mixRaf=w.requestAnimationFrame(tick);else{mixRaf=0;setCross(target,true);resolve()}};mixRaf=w.requestAnimationFrame(tick)});status('MIX • '+from+' → '+to+' הושלם');return true}finally{mixBusy=false}}
async function doMix(){return mixTo(activeDeck()==='A'?'B':'A')}
function cancelMix(){mixBusy=false;const w=frame()?.contentWindow||window;if(mixRaf){try{w.cancelAnimationFrame(mixRaf)}catch(e){}mixRaf=0}}
function itemName(it){return String(it?.name||it?.afdHistoryItem?.name||'Track')}
async function mixQueueIndex(i){const q=Q(),it=q[i];if(!it||autoBusy)return false;autoBusy=true;try{if(window.__afdWin170?.stopAuto)window.__afdWin170.stopAuto();const from=activeDeck(),to=from==='A'?'B':'A';status('SIDEVIEW • מכין '+itemName(it)+' ל-DECK '+to+'...');const ok=await loadItem(to,it);if(!ok)return false;if(!(await waitSource(to,12000)))return false;nextCursor=i+1;if(nextCursor>=q.length)nextCursor=0;return await mixTo(to)}finally{autoBusy=false}}
async function startFirst(){const q=Q();if(!q.length){status('SIDEVIEW • הרשימה ריקה');return false}const it=q[0],deck='A';setCross(sourceEndpoint(deck),true);const ok=await loadItem(deck,it);if(!ok)return false;await waitSource(deck,12000);const started=await startTarget(deck);if(started){setCross(sourceEndpoint(deck),true);nextCursor=q.length>1?1:0;status('SIDEVIEW • START • '+itemName(it))}return started}
async function startNext(){const q=Q();if(!q.length){status('SIDEVIEW • הרשימה ריקה');return false}if(!isPlaying('A')&&!isPlaying('B'))return startFirst();let i=clamp(nextCursor,0,Math.max(0,q.length-1));return mixQueueIndex(i)}
function renderQueue(){const d=D(),host=d?.getElementById('afdQueue170');if(!host)return;const q=Q();host.innerHTML=q.length?q.map((it,i)=>'<div class="afdQ170 afdQ194" data-afd193="1" data-i="'+i+'"><span>'+(i+1)+'</span><span class="afdDrag193" style="display:none"></span><span class="afdDrag194" title="גרור לשינוי סדר">☰</span><b title="דאבל־קליק = MIX מיידי">'+clean(itemName(it))+'</b><button data-qdeck="A">A</button><button data-qdeck="B">B</button><button data-rm="1">×</button></div>').join(''):'<div class="afdDropText170">גרור או הוסף לכאן שירים • אין מגבלת 3 שירים</div>';host.querySelectorAll('.afdQ194').forEach(r=>{r.querySelectorAll('[data-qdeck]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();loadItem(b.dataset.qdeck,Q()[Number(r.dataset.i)])}));r.querySelector('[data-rm]')?.addEventListener('click',e=>{e.stopPropagation();removeQueue(Number(r.dataset.i))});r.querySelector('b')?.addEventListener('dblclick',e=>{e.preventDefault();e.stopPropagation();mixQueueIndex(Number(r.dataset.i))});r.querySelector('.afdDrag194')?.addEventListener('pointerdown',e=>{e.preventDefault();drag={index:Number(r.dataset.i),pointerId:e.pointerId};r.classList.add('afdDragging194');try{r.setPointerCapture(e.pointerId)}catch(x){}})})}
function installPointerReorder(){const d=D();if(!d||d.documentElement.dataset.afdPtr194)return;d.documentElement.dataset.afdPtr194='1';d.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();const rows=[...d.querySelectorAll('#afdQueue170 .afdQ194')];const target=rows.find(r=>{const b=r.getBoundingClientRect();return e.clientY>=b.top&&e.clientY<=b.bottom});if(!target)return;const to=Number(target.dataset.i);if(Number.isInteger(to)&&to!==drag.index){const from=drag.index;moveQueue(from,to);drag.index=to}}, {capture:true,passive:false});const end=()=>{drag=null;d.querySelectorAll('.afdQ194').forEach(r=>r.classList.remove('afdDragging194'))};d.addEventListener('pointerup',end,true);d.addEventListener('pointercancel',end,true)}
function bindUnifiedLibrary(){const d=D();if(!d||d.documentElement.dataset.afdUnifiedLoad194)return;d.documentElement.dataset.afdUnifiedLoad194='1';d.addEventListener('click',e=>{const side=e.target?.closest?.('#afdTracks170 .afdLocalRow170 [data-side]');if(side){const row=side.closest('.afdLocalRow170'),it=itemByKey(row?.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addQueue(it)}return}const b=e.target?.closest?.('#afdTracks170 .afdLocalRow170 [data-a]');if(b){const row=b.closest('.afdLocalRow170'),it=itemByKey(row?.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadItem(b.dataset.a,it)}return}},true);d.addEventListener('dblclick',e=>{const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(!row)return;const it=itemByKey(row.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadItem('A',it)}},true);for(const k of ['A','B']){const root=d.querySelector('.deck'+k);if(!root)continue;root.addEventListener('dragover',e=>{if([...(e.dataTransfer?.types||[])].includes('application/x-afd-local-key'))e.preventDefault()},true);root.addEventListener('drop',e=>{const key=e.dataTransfer?.getData('application/x-afd-local-key');if(!key)return;const it=itemByKey(key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadItem(k,it)}},true)}}
function installQueueControls(){const d=D(),ctl=d?.querySelector('.afdAutoCtl170');if(!d||!ctl)return;let st=d.getElementById('afdUnified194Style');if(!st){st=d.createElement('style');st.id='afdUnified194Style';d.head.appendChild(st)}st.textContent=`#afdQueue170{overflow:auto!important;min-height:0!important;max-height:none!important}.afdQ194{display:grid!important;grid-template-columns:22px 20px minmax(0,1fr) 27px 27px 25px!important;gap:4px!important;align-items:center!important;padding:5px!important}.afdDrag194{display:grid;place-items:center;font-size:14px;color:#b8c1cb;cursor:grab;touch-action:none;user-select:none}.afdQ194.afdDragging194{opacity:.65;outline:1px solid #ba7cff;background:#2e223b!important}.afdAutoCtl170{grid-template-columns:1fr 1fr 1fr auto!important}.afdSync195{margin-top:3px!important;height:27px!important;min-height:27px!important}.browser{display:block!important;visibility:visible!important;opacity:1!important}.library{display:grid!important;visibility:visible!important;opacity:1!important;min-height:245px!important}`;const start=d.getElementById('afdAutoStart170');if(start&&!start.dataset.afd194){start.dataset.afd194='1';start.textContent='▶ START';start.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();autoMode=true;startNext()},true)}let next=d.getElementById('afdStartNext194');if(!next){next=d.createElement('button');next.id='afdStartNext194';next.textContent='▶ START NEXT';next.title='הפעל / ערבב לשיר הבא ב-SIDEVIEW';const stop=d.getElementById('afdAutoStop170');ctl.insertBefore(next,stop||ctl.children[1]||null);next.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();autoMode=false;startNext()},true)}const stop=d.getElementById('afdAutoStop170');if(stop&&!stop.dataset.afd194){stop.dataset.afd194='1';stop.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();autoMode=false;window.__afdWin170?.stopAuto?.();status('SIDEVIEW • AUTO STOP • השיר ממשיך')},true)}}
function bpmEl(k){const d=D();if(!d)return null;let e=d.getElementById('bpm'+k);if(!e){e=d.querySelector('.deck'+k+' .bpm strong');if(e)e.id='bpm'+k}return e}
function showAnalyzing(k){const e=bpmEl(k),api=BPMAPI();if(e&&!api?.getInfo?.(k))e.textContent='…'}
function ensureBpmLater(k){showAnalyzing(k);setTimeout(()=>{const api=BPMAPI();if(!api?.getInfo?.(k)){const p=api?.analyze?.(k);if(p?.catch)p.catch(()=>{})}},1400)}
function normalizeBase(base,leaderEff){let best={base,m:1,rate:leaderEff/base,score:Infinity};for(const m of [.5,1,2]){const b=base*m,r=leaderEff/b;if(r<.55||r>1.8)continue;const score=Math.abs(Math.log(r));if(score<best.score)best={base:b,m,rate:r,score}}return best}
async function waitBpm(k,ms=9000){const end=performance.now()+ms;while(performance.now()<end){const i=BPMAPI()?.getInfo?.(k);if(i?.bpm>20)return i;await sleep(90)}return BPMAPI()?.getInfo?.(k)||null}
function updatePitchUi(k,rate){const d=D(),pct=(rate-1)*100,p=d?.getElementById('pitch'+k),ui=d?.querySelector('#afdPitchInline'+k+' input'),read=d?.getElementById('afdPitchInlineRead'+k);for(const x of [p,ui])if(x)x.value=String(pct);if(read)read.textContent=(pct>0?'+':'')+pct.toFixed(1)+'%'}
async function syncFixed(k){const leader=k==='A'?'B':'A';if(!hasLocal(k)||!hasLocal(leader)){status('SYNC • זמין כרגע לקבצים מקומיים בשני הדקים');return false}status('SYNC • ממתין ל-BPM של שני הדקים...');const [ti,li]=await Promise.all([waitBpm(k),waitBpm(leader)]);if(!(ti?.bpm>20&&li?.bpm>20)){status('SYNC • BPM עדיין לא מוכן');return false}const tv=deckMedia(k),lv=deckMedia(leader);if(!tv||!lv)return false;const leaderEff=li.bpm*(Number(lv.playbackRate)||1),norm=normalizeBase(ti.bpm,leaderEff),rate=leaderEff/norm.base;if(!(rate>=.55&&rate<=1.8)){status('SYNC • פער BPM גדול מדי');return false}try{tv.preservesPitch=true;tv.webkitPreservesPitch=true}catch(e){}tv.playbackRate=rate;updatePitchUi(k,rate);const lPer=60/li.bpm,tPer=60/ti.bpm,lPhase=mod((Number(lv.currentTime)||0)-Number(li.offset||0),lPer)/lPer,base=Number(ti.offset||0)+lPhase*tPer,cur=Number(tv.currentTime)||0,n=Math.round((cur-base)/tPer),dest=base+n*tPer;try{tv.volume=0}catch(e){}if(tv.paused){try{await tv.play()}catch(e){}}if(Number.isFinite(tv.duration)&&tv.duration>0){try{tv.currentTime=clamp(dest,0,Math.max(0,tv.duration-.04))}catch(e){}}syncLocks[k]={leader,base:norm.base};const e=bpmEl(k);if(e){e.dataset.afdBaseBpm=String(norm.base);e.dataset.afdEffectiveBpm=String(leaderEff);e.dataset.afdSyncLocked='194';e.textContent=leaderEff.toFixed(1)}const le=bpmEl(leader);if(le)le.textContent=leaderEff.toFixed(1);status('SYNC • DECK '+k+' = '+leaderEff.toFixed(1)+' BPM • מיושר ל-DECK '+leader);return true}
function installSyncCapture(){const d=D();if(!d||d.documentElement.dataset.afdSync194)return;d.documentElement.dataset.afdSync194='1';d.addEventListener('click',e=>{const b=e.target?.closest?.('.afdSync195,.afdSyncUnder192,.afdSync190,.transport [data-act="sync"]');if(!b)return;let k=b.id?.endsWith('A')?'A':b.id?.endsWith('B')?'B':b.closest('.deckA')?'A':b.closest('.deckB')?'B':null;if(!k)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();syncFixed(k)},true)}
function historyData(){try{const h=JSON.parse(localStorage.getItem(HIST)||'{}');return h&&typeof h==='object'?h:{}}catch(e){return{}}}
function saveHistory(h){try{const days=Object.keys(h).sort().slice(-180),o={};for(const d of days)o[d]=(h[d]||[]).slice(-1500);localStorage.setItem(HIST,JSON.stringify(o))}catch(e){}}
function localDay(ts){const d=new Date(ts);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dayLabel(day){try{return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(day+'T12:00:00'))}catch(e){return day}}
function sourceNow(k){const sp=window.AFDSpotifyState?.getLoaded?.(k);if(sp)return{source:'Spotify',item:sp,name:sp.name||'Spotify'};if(srcMeta[k]?.source==='YouTube')return srcMeta[k];const m=window.AFDLocalDeckMeta?.[k]||srcMeta[k]?.item;if(m?.name)return{source:'Local',item:{...m},name:m.name};return null}
function sourceKey(s){return s?s.source+':'+String(s.item?.path||s.item?.id||s.item?.uri||s.item?.key||s.name||''):''}
function recordHistory(k){const on=isPlaying(k),w=histWatch[k];if(!on){w.playing=false;return}const s=sourceNow(k);if(!s)return;const key=sourceKey(s);if(w.playing&&w.key===key)return;w.playing=true;w.key=key;const now=Date.now(),day=localDay(now),h=historyData(),arr=h[day]||(h[day]=[]),item=s.item||{};arr.push({ts:now,time:new Date(now).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}),deck:k,source:s.source,name:s.name||item.name||item.title||'Track',key,item,path:s.source==='Local'?String(item.path||''):'',kind:s.source==='YouTube'?'video':String(item.kind||'music')});saveHistory(h)}
function histCan(x){return x?.source==='Local'?!!(x.item?.path||x.path):x?.source==='Spotify'?!!(x.item?.id||x.item?.uri):x?.source==='YouTube'?!!(x.item?.id||x.item?.videoId):false}
function histQueue(x,day){if(!histCan(x))return null;if(x.source==='Local')return queueClone({key:'h194:'+day+':'+x.ts,path:x.item?.path||x.path||'',name:x.item?.name||x.name,folder:'History '+day,kind:x.item?.kind||x.kind||'music',afdHistorySource:'Local',afdHistoryItem:x.item||{path:x.path,name:x.name}});if(x.source==='Spotify')return queueClone({key:'h194:'+day+':'+x.ts,name:x.item?.name||x.name,folder:'History '+day,kind:'music',afdHistorySource:'Spotify',afdHistoryItem:x.item});if(x.source==='YouTube')return queueClone({key:'h194:'+day+':'+x.ts,name:x.item?.title||x.name,folder:'History '+day,kind:'video',afdHistorySource:'YouTube',afdHistoryItem:x.item});return null}
function showHistory(day=null){const d=D(),tracks=d?.querySelector('.library>.tracks');if(!d||!tracks)return;const base=d.getElementById('afdTracks170');if(base)base.style.setProperty('display','none','important');let ov=d.getElementById('afdHistory194');if(!ov){ov=d.createElement('div');ov.id='afdHistory194';ov.style.cssText='height:100%;overflow:auto;background:#090d12';tracks.appendChild(ov)}ov.style.display='block';const h=historyData(),days=Object.keys(h).filter(x=>Array.isArray(h[x])&&h[x].length).sort().reverse();if(!day){ov.innerHTML=days.length?'<div style="padding:8px;font-weight:900">HISTORY • בחר תאריך</div>'+days.map(x=>'<div class="h194day" data-day="'+x+'" style="display:grid;grid-template-columns:30px 1fr 100px;padding:9px;border-bottom:1px solid #252d36;cursor:pointer"><span>🕘</span><b>'+clean(dayLabel(x))+'</b><span>'+h[x].length+' שירים</span></div>').join(''):'<div class="afdEmpty170">אין היסטוריה.</div>';ov.querySelectorAll('.h194day').forEach(r=>r.onclick=()=>showHistory(r.dataset.day));return}const arr=h[day]||[];ov.innerHTML='<div style="display:flex;gap:6px;align-items:center;padding:7px;position:sticky;top:0;background:#151b23;z-index:3"><button id="h194back">◀ תאריכים</button><b style="flex:1;text-align:center">'+clean(dayLabel(day))+'</b><button id="h194all">＋ כל היום ל-SIDEVIEW</button></div>'+arr.map((x,i)=>'<div class="h194row" data-i="'+i+'" style="display:grid;grid-template-columns:28px 52px minmax(140px,1fr) 85px 34px 34px 52px;gap:5px;align-items:center;padding:6px;border-bottom:1px solid #202730"><span>'+(i+1)+'</span><time>'+clean(x.time||'')+'</time><b>'+clean(x.name||'Track')+'</b><small>'+clean(x.source||'')+'</small><button data-h="A" '+(!histCan(x)?'disabled':'')+'>A</button><button data-h="B" '+(!histCan(x)?'disabled':'')+'>B</button><button data-side="1" '+(!histCan(x)?'disabled':'')+'>＋SIDE</button></div>').join('');ov.querySelector('#h194back').onclick=()=>showHistory();ov.querySelector('#h194all').onclick=()=>{let n=0;for(const x of arr){const it=histQueue(x,day);if(it){Q().push(it);n++}}renderQueue();status('HISTORY • '+n+' שירים הועברו ל-SIDEVIEW')};ov.querySelectorAll('.h194row').forEach(r=>{const x=arr[Number(r.dataset.i)],it=histQueue(x,day);r.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>it&&loadItem(b.dataset.h,it));r.querySelector('[data-side]')?.addEventListener('click',()=>{if(it){Q().push(queueClone(it));renderQueue()}});r.querySelector('b')?.addEventListener('dblclick',()=>it&&loadItem('A',it))})}
function hideHistory(){const d=D(),ov=d?.getElementById('afdHistory194'),base=d?.getElementById('afdTracks170');if(ov)ov.style.display='none';if(base)base.style.removeProperty('display')}
function installHistory(){const d=D();if(!d||d.documentElement.dataset.afdHist194)return;d.documentElement.dataset.afdHist194='1';d.addEventListener('click',e=>{const cat=e.target?.closest?.('#afdFolders170 [data-cat]');if(!cat)return;if(cat.dataset.cat==='history'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();d.querySelectorAll('#afdFolders170 [data-cat]').forEach(x=>x.classList.toggle('active',x===cat));showHistory()}else hideHistory()},true)}
function restoreLayout(){const d=D();if(!d)return;const browser=d.querySelector('.browser'),lib=d.querySelector('.library');if(browser){browser.style.setProperty('display','block','important');browser.style.setProperty('visibility','visible','important');browser.style.setProperty('opacity','1','important')}if(lib){lib.style.setProperty('display','grid','important');lib.style.setProperty('visibility','visible','important');if(lib.getBoundingClientRect().height<180)lib.style.setProperty('height','270px','important')}const fr=frame();if(fr){fr.style.display='block';fr.style.visibility='visible';fr.style.opacity='1'}}
function installMixCapture(){const d=D();if(!d||d.documentElement.dataset.afdMix194)return;d.documentElement.dataset.afdMix194='1';d.addEventListener('click',e=>{const b=e.target?.closest?.('#afdMixBtn');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();doMix()},true)}
function autoPoll(){if(!autoMode||autoBusy||!Q().length)return;const k=activeDeck(),v=deckMedia(k);let cur=0,dur=0;if(hasSP(k)){const t=window.AFDSpotifyState?.getTime?.(k);cur=Number(t?.current)||0;dur=Number(t?.duration)||0}else if(hasYT(k)){const t=window.AFDYouTubeState?.getTime?.(k);cur=Number(t?.current)||0;dur=Number(t?.duration)||0}else if(v){cur=Number(v.currentTime)||0;dur=Number(v.duration)||0}if(dur>5&&dur-cur<1.2)startNext()}
function refresh(){restoreLayout();bindUnifiedLibrary();installPointerReorder();installQueueControls();installSyncCapture();installHistory();installMixCapture();renderQueue()}
window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B'){srcMeta[k]={source:'Local',item:e.detail?.item||window.AFDLocalDeckMeta?.[k]||null};histWatch[k].playing=false;ensureBpmLater(k)}});window.addEventListener('afd-youtube-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B'){srcMeta[k]={source:'YouTube',item:{id:e.detail?.id||e.detail?.videoId||'',title:e.detail?.title||e.detail?.name||'YouTube',thumb:e.detail?.thumb||''},name:e.detail?.title||e.detail?.name||'YouTube'};histWatch[k].playing=false}});window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B'){srcMeta[k]={source:'Spotify',item:e.detail?.item||null,name:e.detail?.item?.name||'Spotify'};histWatch[k].playing=false}});window.addEventListener('afd-deck-eject',e=>{const k=e.detail?.deck;if(k==='A'||k==='B'){srcMeta[k]=null;histWatch[k]={playing:false,key:''}}});window.addEventListener('resize',()=>{setTimeout(restoreLayout,60);setTimeout(restoreLayout,350);setTimeout(restoreLayout,900)});frame()?.addEventListener('load',()=>setTimeout(refresh,320));window.__afdWin194={refresh,renderQueue,addQueue,moveQueue,startNext,mixQueueIndex,doMix,mixTo,syncFixed,loadItem};refresh();setTimeout(refresh,850);setInterval(()=>{restoreLayout();autoPoll();recordHistory('A');recordHistory('B')},450);
})();