(()=>{
if(window.__afdWin185V148)return;
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const VIDEO=new Set('mp4 m4v mov webm ogv avi wmv asf mkv mpg mpeg m2v ts mts m2ts vob flv f4v 3gp 3g2 rm rmvb divx dv'.split(' '));
const serial={A:0,B:0};window.AFDLocalDeckMeta=window.AFDLocalDeckMeta||{A:null,B:null};
const extOf=it=>{const n=String(it?.name||it?.path||'').toLowerCase(),m=n.match(/\.([a-z0-9]+)$/);return m?m[1]:''};
const status=t=>{const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD SAFE LOAD 185.8]',t)};
function clearOnline(deck,it){try{window.AFDYouTubeState?.clear?.(deck,it||null)}catch(e){}try{window.AFDSpotifyState?.clear?.(deck)}catch(e){}}
function isVideo(it,res){return(res?.kind||it?.kind)==='video'||VIDEO.has(extOf(it))}
async function resolveItem(it){const x={...(it||{})},bridge=window.afdDesktopMedia;if(!x.path&&x.key&&bridge?.getPath)try{x.path=String(await bridge.getPath(x.key)||'')}catch(e){}return x}
function validateVideo(url,timeout=9000){return new Promise((resolve,reject)=>{const d=D();if(!d)return reject(Error('Deck document unavailable'));const p=d.createElement('video');let done=false,t=null;const finish=err=>{if(done)return;done=true;clearTimeout(t);try{p.pause();p.removeAttribute('src');p.load();p.remove()}catch(e){}err?reject(err):resolve(true)};p.muted=true;p.preload='metadata';p.style.cssText='position:fixed;width:1px;height:1px;left:-9999px;top:-9999px;opacity:0;pointer-events:none';p.addEventListener('loadedmetadata',()=>finish(),{once:true});p.addEventListener('canplay',()=>finish(),{once:true});p.addEventListener('error',()=>finish(Error('Media codec is not playable by Chromium')),{once:true});d.body.appendChild(p);t=setTimeout(()=>finish(Error('Media probe timed out')),timeout);p.src=url;try{p.load()}catch(e){finish(e)}})}
function commit(deck,it,res){const d=D(),v=d?.getElementById('vid'+deck),m=d?.getElementById('master'+deck);if(!d||!v)throw Error('Deck not ready');const video=isVideo(it,res);clearOnline(deck,it);try{v.pause()}catch(e){}try{v.removeAttribute('src');v.load()}catch(e){}v.src=res.url;v.preload='auto';v.style.display=video?'block':'none';if(m){try{m.pause();m.removeAttribute('src');m.load()}catch(e){}m.style.setProperty('display','none','important');m.muted=true}const post=d.getElementById('post'+deck);if(post)post.style.display=video?'none':'grid';const title=d.getElementById('title'+deck);if(title)title.textContent=it?.name||res?.name||'Track';try{v.load();v.currentTime=0}catch(e){}const meta={key:it?.key||'',path:it?.path||'',name:it?.name||res?.name||'',kind:video?'video':'music'};window.AFDLocalDeckMeta[deck]=meta;try{window.dispatchEvent(new CustomEvent('afd-local-load',{detail:{deck,item:meta,afd185:true}}))}catch(e){}return true}
async function prepare(it,force=false){const bridge=window.afdDesktopMedia;if(!bridge)throw Error('Windows media engine unavailable');const meta={key:it?.key||'',path:it?.path||'',name:it?.name||'',kind:it?.kind||'',force:!!force};return it?.path?bridge.preparePath(meta):bridge.prepare(meta)}
async function bridgeLoad(deck,raw,force=false){const my=++serial[deck],it=await resolveItem(raw);if(my!==serial[deck])return false;if(!it.path&&!it.key)throw Error('Local media path is unavailable');try{window.dispatchEvent(new CustomEvent('afd-local-preload',{detail:{deck,item:{key:it.key||'',path:it.path||'',name:it.name||'',kind:it.kind||''}}}))}catch(e){}status('MEDIA • מכין '+(it?.name||'קובץ')+' ל-DECK '+deck+' • הדק השני ממשיך...');let res=await prepare(it,force);if(my!==serial[deck])return false;if(!res?.url)throw Error('Media preparation returned no file');if(isVideo(it,res)){try{await validateVideo(res.url,res.converted?10000:6000)}catch(e){if(!force){status('MEDIA • הקודק דורש התאמה, מכין גרסה תואמת...');res=await prepare(it,true);if(my!==serial[deck])return false;if(!res?.url)throw Error('Full transcode returned no file');await validateVideo(res.url,14000)}else throw e}}if(my!==serial[deck])return false;commit(deck,it,res);status((res.remuxed?'REMUXED':res.converted?'CONVERTED':'LOADED')+' • '+(it?.name||'Track')+' → DECK '+deck+' • לחץ PLAY');return true}
async function load(deck,it){if(!['A','B'].includes(deck)||!it)return false;try{return await bridgeLoad(deck,it,false)}catch(e){status('MEDIA ERROR • '+(e?.message||e)+' • הדק הקיים נשמר');return false}}
window.AFDWindowsLoadItem=load;window.AFDWindowsLoadState={cancel:deck=>{if(['A','B'].includes(deck))serial[deck]++}};window.__afdWin185V148={load};window.__afdWin185=window.__afdWin185V148;window.__afdWin183=window.__afdWin185V148;window.__afdWin179=window.__afdWin185V148;
})();