(()=>{
if(window.__afdSpotify189){window.__afdSpotify189.refresh();return;}
const $=id=>document.getElementById(id),CID='d1b255796dbd444995e8f6e29d4ce2cd';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let items=[],nextUrl='',prevUrl='',total=0,lastQuery='',searching=false;
const token=()=>sessionStorage.getItem('afdSPToken')||localStorage.getItem('afdSPAccess169')||'';
const redirect=()=>location.origin+location.pathname;
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const rand=(n=64)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return b64(a)};
const sha=s=>crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));
function status(t){const e=$('status');if(e)e.textContent=t;console.log('[AFD Spotify 189]',t)}
function sanitizeUrl(raw){try{const u=new URL(String(raw),location.href);if(u.hostname==='api.spotify.com'&&u.pathname==='/v1/search'){u.searchParams.delete('limit');let off=Number(u.searchParams.get('offset')||0);if(!Number.isFinite(off)||off<0)off=0;if(off>1000)off=1000;if(off)u.searchParams.set('offset',String(Math.floor(off)));else u.searchParams.delete('offset')}return u.toString()}catch(e){return String(raw)}}
if(!window.__afdSpotifyFetchSanitized189){window.__afdSpotifyFetchSanitized189=true;const orig=window.fetch.bind(window);window.fetch=(input,init)=>{try{const raw=typeof input==='string'||input instanceof URL?String(input):input?.url;if(raw){const clean=sanitizeUrl(raw);if(clean!==raw){if(typeof Request!=='undefined'&&input instanceof Request)return orig(new Request(clean,input),init);return orig(clean,init)}}}catch(e){}return orig(input,init)};window.__afdSpotifyOriginalFetch189=orig}
function mark(el){['win167','win168','afd84','afd84v2','afd83','afdSP103','bound166','bound167','bound168','afd187','afd187bound','afd189'].forEach(k=>el.dataset[k]='1')}
function style(){let s=$('afdSP189Style');if(s)return;s=document.createElement('style');s.id='afdSP189Style';s.textContent='#afdSP167Results,#afdSP168Results,#afdSPResults,#afdSP187Results{display:none!important}#afdSP189Results{margin-top:7px;overflow:auto;min-height:72px;max-height:390px;border:1px solid #313944;border-radius:6px;background:#05070a}.afdSP189Row{display:grid;grid-template-columns:54px minmax(0,1fr) 66px 66px;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #20262d;direction:ltr}.afdSP189Row img{width:54px;height:54px;object-fit:cover;border-radius:5px}.afdSP189Meta{min-width:0}.afdSP189Meta b,.afdSP189Meta span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdSP189Meta span{font-size:9px;color:#9ca8b5}.afdSP189Row button{height:30px!important;font-size:8px!important;font-weight:900!important}.afdSP189Pager{display:grid;grid-template-columns:90px 1fr 90px;gap:8px;align-items:center;padding:8px}.afdSP189Pager span{text-align:center;font-size:9px;color:#b6c0cb}.afdSP189Msg{padding:16px;text-align:center;color:#aeb8c3;font-size:10px}';document.head.appendChild(s)}
function clearOld(){['afdSP167Results','afdSP168Results','afdSPResults','afdSP187Results'].forEach(id=>{const e=$(id);if(e)e.style.setProperty('display','none','important')})}
function claim(){style();clearOld();let b=$('spBtn'),i=$('spSearch');if(!b||!i)return null;if(b.dataset.afd189!=='1'){const n=b.cloneNode(true);n.id='spBtn';n.textContent='חיפוש Spotify';n.onclick=null;n.removeAttribute('onclick');mark(n);b.replaceWith(n);b=n}else mark(b);if(i.dataset.afd189!=='1'){const val=i.value,n=i.cloneNode(true);n.id='spSearch';n.value=val;n.placeholder='חפש שיר או אמן ב-Spotify';n.onkeydown=null;n.removeAttribute('onkeydown');mark(n);i.replaceWith(n);i=n}else mark(i);let r=$('afdSP189Results');if(!r){r=document.createElement('div');r.id='afdSP189Results';b.closest('.card')?.appendChild(r)}if(!b.dataset.afd189bound){b.dataset.afd189bound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();search(i.value)},true);i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();search(i.value)}},true)}return{b,i,r}}
async function login(q){sessionStorage.setItem('afdSPPendingQ189',q||'');const verifier=rand(64),state='afd168_'+rand(18);sessionStorage.setItem('afdSPVerifier168',verifier);sessionStorage.setItem('afdSPState168',state);sessionStorage.setItem('afdSPAuthBusy168','1');const challenge=b64(await sha(verifier)),u=new URL('https://accounts.spotify.com/authorize');u.search=new URLSearchParams({client_id:CID,response_type:'code',redirect_uri:redirect(),code_challenge_method:'S256',code_challenge:challenge,state,scope:'streaming user-read-email user-read-private user-modify-playback-state user-read-playback-state playlist-read-private playlist-read-collaborative'});status('Spotify • פותח חלון התחברות…');location.href=u.toString()}
async function api(url){const t=token();if(!t)throw Error('SPOTIFY_LOGIN');const clean=sanitizeUrl(url);let r=await window.__afdSpotifyOriginalFetch189(clean,{headers:{Authorization:'Bearer '+t}});if(r.status===401){sessionStorage.removeItem('afdSPToken');throw Error('SPOTIFY_LOGIN')}let j=await r.json().catch(()=>({}));if(!r.ok&&/invalid\s+limit/i.test(String(j?.error?.message||''))){const u=new URL(clean);u.searchParams.set('limit','5');r=await window.__afdSpotifyOriginalFetch189(u.toString(),{headers:{Authorization:'Bearer '+t}});j=await r.json().catch(()=>({}))}if(!r.ok)throw Error(j?.error?.message||('Spotify HTTP '+r.status));return j}
function pageUrl(u){return u?sanitizeUrl(u):''}
function render(){const U=claim();if(!U)return;if(!items.length){U.r.innerHTML='<div class="afdSP189Msg">לא נמצאו תוצאות</div>';return}U.r.innerHTML=items.map((it,n)=>'<div class="afdSP189Row" data-i="'+n+'"><img src="'+esc(it.album?.images?.[1]?.url||it.album?.images?.[0]?.url||'')+'"><div class="afdSP189Meta"><b>'+esc(it.name)+'</b><span>'+esc((it.artists||[]).map(a=>a.name).join(', '))+' • '+esc(it.album?.name||'')+'</span></div><button data-d="A" style="background:#382153">LOAD A</button><button data-d="B" style="background:#123f5a">LOAD B</button></div>').join('')+'<div class="afdSP189Pager"><button id="afdSP189Prev" '+(!prevUrl?'disabled':'')+'>◀ הקודם</button><span>'+items.length+' תוצאות • '+total+' בסך הכול</span><button id="afdSP189Next" '+(!nextUrl?'disabled':'')+'>הבא ▶</button></div>';U.r.querySelectorAll('.afdSP189Row').forEach(row=>row.querySelectorAll('[data-d]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const it=items[+row.dataset.i];window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:b.dataset.d,item:it}}))})));$('afdSP189Prev')?.addEventListener('click',()=>page(prevUrl));$('afdSP189Next')?.addEventListener('click',()=>page(nextUrl))}
async function runUrl(url,q=''){const U=claim();if(!U)return;U.r.innerHTML='<div class="afdSP189Msg">מחפש ב-Spotify…</div>';try{const j=await api(url),t=j.tracks||{};items=t.items||[];nextUrl=pageUrl(t.next);prevUrl=pageUrl(t.previous);total=Number(t.total)||0;if(q)lastQuery=q;render();status('Spotify • נמצאו '+total+' תוצאות')}catch(e){if(e.message==='SPOTIFY_LOGIN'){await login(q||lastQuery);return}U.r.innerHTML='<div class="afdSP189Msg" style="color:#ffaaaa">'+esc(e.message)+'</div>';status('Spotify ERROR • '+e.message)}finally{searching=false}}
async function search(q){q=String(q||'').trim();if(!q||searching)return;searching=true;lastQuery=q;const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q',q);u.searchParams.set('type','track');await runUrl(u.toString(),q)}
async function page(url){if(!url||searching)return;searching=true;await runUrl(pageUrl(url),lastQuery)}
function resumePending(){const q=sessionStorage.getItem('afdSPPendingQ189')||sessionStorage.getItem('afdSPPendingQ187')||'';if(q&&token()&&!searching){sessionStorage.removeItem('afdSPPendingQ189');sessionStorage.removeItem('afdSPPendingQ187');const U=claim();if(U)U.i.value=q;search(q)}}
function refresh(){claim();clearOld();resumePending()}
window.__afdSpotify189={refresh,search,sanitizeUrl};refresh();setTimeout(refresh,350);setInterval(refresh,500);
})();