(()=>{
if(window.__afdCore205){window.__afdCore205.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return frame()?.contentWindow||null}catch(e){return null}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const HIST='afdPlaybackHistory192v1';
let queue=[],nextIndex=0,busy=false,mixBusy=false,rendering=false,queueObserver=null,keyObservers=[],lastClock={A:'',B:''};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD CORE 205]',t)}
function items(){return Array.from(window.__afdWin170?.items||[])}
function findItem(key){return items().find(x=>String(x?.key)===String(key))||null}
function qClone(it){if(!it)return null;return{...it,_q205:'q205:'+Date.now()+':'+Math.random().toString(36).slice(2)}}
function addQueue(it,announce=true){const x=qClone(it);if(!x)return false;queue.push(x);renderQueue();if(announce)status('SIDE VIEW • נוסף '+(x.name||'שיר')+' • '+queue.length+' שירים');return true}
function removeQueue(i){if(i<0||i>=queue.length)return;queue.splice(i,1);if(nextIndex>=queue.length)nextIndex=Math.max(0,queue.length-1);renderQueue()}
function moveQueue(from,to){if(from===to||from<0||to<0||from>=queue.length||to>=queue.length)return;const [x]=queue.splice(from,1);queue.splice(to,0,x);if(nextIndex===from)nextIndex=to;else if(from<nextIndex&&to>=nextIndex)nextIndex--;else if(from>nextIndex&&to<=nextIndex)nextIndex++;renderQueue();status('SIDE VIEW • הסדר עודכן')}
function deckMedia(k){return D()?.getElementById('vid'+k)||null}
function hasSP(k){return!!window.AFDSpotifyState?.has?.(k)}
function hasYT(k){return!!window.AFDYouTubeState?.isLoaded?.(k)||!!D()?.getElementById('ytDeck'+k)}
function hasLocal(k){const v=deckMedia(k);return!!(v&&(v.currentSrc||v.src))&&!hasSP(k)&&!hasYT(k)}
function hasSource(k){return hasSP(k)||hasYT(k)||!!(deckMedia(k)?.currentSrc||deckMedia(k)?.src)}
function isPlaying(k){const v=deckMedia(k);return!!(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||!!window.AFDSpotifyState?.isPlaying?.(k)||!!window.AFDYouTubeState?.isPlaying?.(k)}
function activeDeck(){const a=isPlaying('A'),b=isPlaying('B');if(a&&!b)return'A';if(b&&!a)return'B';const x=Number(D()?.getElementById('cross')?.value??50);return x>=50?'A':'B'}
function quickDeck(){const a=isPlaying('A'),b=isPlaying('B');if(a&&!b)return'B';if(b&&!a)return'A';return'A'}
function crossFor(k){return k==='A'?100:0}
function setCross(x,finish=false){x=clamp(Number(x)||0,0,100);const d=D(),c=d?.getElementById('cross'),vc=d?.getElementById('videoCross');for(const el of [c,vc])if(el){el.value=String(x);el.dispatchEvent(new Event('input',{bubbles:true}));if(finish)el.dispatchEvent(new Event('change',{bubbles:true}))}try{window.AFDSpotifyState?.applyCross?.(x)}catch(e){}try{window.AFDYouTubeState?.applyCross?.(x)}catch(e){}}
async function waitSource(k,ms=15000){const end=performance.now()+ms;while(performance.now()<end){if(hasSource(k))return true;await sleep(70)}return hasSource(k)}
async function waitPlaying(k,ms=9000){const end=performance.now()+ms;while(performance.now()<end){if(isPlaying(k))return true;await sleep(70)}return isPlaying(k)}
function clearOnline(k){try{window.AFDSpotifyState?.clear?.(k)}catch(e){}try{window.AFDYouTubeState?.clear?.(k)}catch(e){}}
async function loadLocal(k,it){if(!it)return false;status('LOCAL • טוען '+(it.name||it.file?.name||'Track')+' → DECK '+k+'…');clearOnline(k);try{if(typeof window.AFDWindowsLoadItem==='function'){const ok=await window.AFDWindowsLoadItem(k,it);if(ok){status('LOCAL • '+(it.name||'Track')+' מוכן ב-DECK '+k);return true}}}catch(e){console.warn('AFDWindowsLoadItem',e)}try{if(it.file&&typeof W()?.load==='function'){W().load(k,it.file);window.dispatchEvent(new CustomEvent('afd-local-load',{detail:{deck:k,item:it,afd205Fallback:true}}));status('LOCAL • '+(it.name||'Track')+' נטען ישירות ל-DECK '+k);return true}}catch(e){console.warn('native load fallback',e)}status('LOCAL ERROR • לא ניתן לטעון '+(it.name||'הקובץ')+' ל-DECK '+k);return false}
async function loadSpotify(k,it){if(!it)return false;status('SPOTIFY • '+(it.name||'Track')+' → DECK '+k);try{window.AFDYouTubeState?.clear?.(k)}catch(e){}const v=deckMedia(k);if(v){try{v.pause();v.removeAttribute('src');v.load()}catch(e){}}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[k]=null;window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:k,item:it}}));const end=performance.now()+3500;while(performance.now()<end){if(hasSP(k))return true;await sleep(60)}return hasSP(k)}
async function loadYouTube(k,it){if(!it)return false;try{window.AFDSpotifyState?.clear?.(k)}catch(e){}return (await window.AFDYouTubeState?.load?.(k,it))!==false}
async function loadAny(k,it){if(!it||!['A','B'].includes(k))return false;if(it.afdHistorySource==='Local')return loadLocal(k,{...(it.afdHistoryItem||{}),path:it.afdHistoryItem?.path||it.path||'',key:it.afdHistoryItem?.key||it.key,name:it.afdHistoryItem?.name||it.name,folder:it.afdHistoryItem?.folder||it.folder||'History',kind:it.afdHistoryItem?.kind||it.kind||'music'});if(it.afdHistorySource==='Spotify')return loadSpotify(k,it.afdHistoryItem||it);if(it.afdHistorySource==='YouTube')return loadYouTube(k,it.afdHistoryItem||it);if(it.__source==='spotify'||it.afdSpotifyItem||it.spotifyItem)return loadSpotify(k,it.afdSpotifyItem||it.spotifyItem||it);if(it.afdYouTubeItem||it.youtubeItem)return loadYouTube(k,it.afdYouTubeItem||it.youtubeItem);return loadLocal(k,it)}
async function startDeck(k){if(isPlaying(k))return true;if(hasSP(k)){window.AFDSpotifyState?.setLevel?.(k,0);window.AFDSpotifyState?.play?.(k);return waitPlaying(k,9000)}if(hasLocal(k)){const v=deckMedia(k);try{v.volume=0;await v.play()}catch(e){}if(await waitPlaying(k,2500))return true}if(hasYT(k)){try{await window.AFDYouTubeState?.play?.(k)}catch(e){}if(await waitPlaying(k,4500))return true}const d=D(),btn=d?.querySelector('.deck'+k+' [data-act="play"],.deck'+k+' .transport .play');if(btn){btn.click();return waitPlaying(k,9000)}return false}
async function mixTo(k,duration=5600){if(mixBusy)return false;const from=k==='A'?'B':'A';if(!hasSource(k)){status('MIX • אין מקור ב-DECK '+k);return false}mixBusy=true;try{const start=crossFor(from),target=crossFor(k);setCross(start,true);try{window.AFDSpotifyState?.setLevel?.(k,0)}catch(e){}const v=deckMedia(k);if(v&&!hasSP(k))try{v.volume=0}catch(e){}status('MIX • מפעיל DECK '+k+' בשקט…');if(!(await startDeck(k))){status('MIX • DECK '+k+' לא התחיל');return false}await sleep(220);const win=W()||window,t0=performance.now();await new Promise(resolve=>{const tick=t=>{const p=Math.min(1,(t-t0)/duration),q=p*p*(3-2*p);setCross(start+(target-start)*q,false);if(p<1)win.requestAnimationFrame(tick);else{setCross(target,true);resolve()}};win.requestAnimationFrame(tick)});status('MIX • '+from+' → '+k+' הושלם');return true}finally{mixBusy=false}}
async function startFirst(){if(!queue.length){status('SIDE VIEW • הרשימה ריקה');return false}const it=queue[0];setCross(100,true);if(!(await loadAny('A',it)))return false;if(!(await waitSource('A',15000))){status('SIDE VIEW • השיר לא הגיע ל-DECK A');return false}if(!(await startDeck('A'))){status('SIDE VIEW • DECK A לא התחיל');return false}setCross(100,true);nextIndex=queue.length>1?1:0;status('SIDE VIEW • START • '+(it.name||'Track'));return true}
async function mixQueue(i){if(busy||!queue[i])return false;busy=true;try{const to=activeDeck()==='A'?'B':'A',it=queue[i];status('SIDE VIEW • מכין '+(it.name||'Track')+' ל-DECK '+to+'…');if(!(await loadAny(to,it)))return false;if(!(await waitSource(to,15000))){status('SIDE VIEW • השיר לא הגיע ל-DECK '+to);return false}nextIndex=queue.length?(i+1)%queue.length:0;return await mixTo(to)}finally{busy=false}}
async function startNext(){if(!queue.length){status('SIDE VIEW • הרשימה ריקה');return false}if(!isPlaying('A')&&!isPlaying('B'))return startFirst();return mixQueue(clamp(nextIndex,0,queue.length-1))}
function renderQueue(){const d=D(),h=d?.getElementById('afdQueue170');if(!h)return;rendering=true;h.dataset.afdOwner='205';h.innerHTML=queue.length?queue.map((it,i)=>'<div class="afdQ205" data-i="'+i+'"><span class="afdGrip205" draggable="true" title="גרור לשינוי סדר">☰</span><span>'+String(i+1).padStart(2,'0')+'</span><b title="דאבל-קליק = MIX עכשיו">'+esc(it.name||it.afdHistoryItem?.name||'Track')+'</b><button data-load="A">A</button><button data-load="B">B</button><button data-up="1">▲</button><button data-down="1">▼</button><button data-rm="1">×</button></div>').join(''):'<div class="afdEmpty205">SIDE VIEW ריק • הוסף שירים מהספרייה או מה-History</div>';rendering=false}
function historyStores(){let a={},b={};try{a=JSON.parse(localStorage.getItem(HIST)||'{}')||{}}catch(e){}try{b=JSON.parse(localStorage.getItem('afdPlaybackHistory177v3')||'{}')||{}}catch(e){}return{a,b}}
function dayLabel(day){try{return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(day+'T12:00:00'))}catch(e){return day}}
function mergedDay(day){const {a,b}=historyStores(),n=(a[day]||[]).slice();for(const x of (b[day]||[])){const dup=n.some(y=>y.name===x.name&&y.source===x.source&&Math.abs((Number(y.ts)||0)-(Number(x.ts)||0))<2500);if(!dup)n.push({...x,item:x.item||null})}return n.sort((x,y)=>(x.ts||0)-(y.ts||0))}
function currentHistoryDay(){const d=D(),txt=(d?.querySelector('.afdHist192Head b')?.textContent||'').trim(),{a,b}=historyStores(),days=[...new Set([...Object.keys(a),...Object.keys(b)])];return days.find(x=>dayLabel(x)===txt)||null}
function historyEntry(row){const day=currentHistoryDay();if(!day||!row)return null;const i=Number(row.dataset.i),arr=mergedDay(day);return Number.isInteger(i)?{day,x:arr[i]||null}:null}
function historyQueueItem(x,day){if(!x)return null;if(x.source==='Local')return{key:'hist205:'+String(x.key||x.ts||Math.random()),path:x.item?.path||x.path||'',name:x.item?.name||x.name,folder:'History '+day,kind:x.item?.kind||x.kind||'music',afdHistorySource:'Local',afdHistoryItem:x.item||{path:x.path||'',name:x.name||'',kind:x.kind||'music'}};if(x.source==='Spotify'&&(x.item?.id||x.item?.uri))return{key:'hist205:'+String(x.key||x.ts||Math.random()),name:x.item?.name||x.name,folder:'History '+day,kind:'music',afdHistorySource:'Spotify',afdHistoryItem:x.item};if(x.source==='YouTube'&&x.item?.id)return{key:'hist205:'+String(x.key||x.ts||Math.random()),name:x.item?.title||x.name,folder:'History '+day,kind:'video',afdHistorySource:'YouTube',afdHistoryItem:x.item};return null}
async function loadHistory(k,x){const it=historyQueueItem(x,currentHistoryDay()||'');return it?loadAny(k,it):false}
function addHistoryDay(day){let n=0;for(const x of mergedDay(day)){const it=historyQueueItem(x,day);if(it&&addQueue(it,false))n++}renderQueue();status('HISTORY • נוספו '+n+' שירים ל-SIDE VIEW')}
function fmtSec(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function paintSpotifyClock(k){if(!hasSP(k))return;const d=D(),t=window.AFDSpotifyState?.getTime?.(k)||{},cur=Math.max(0,Number(t.current)||0),dur=Math.max(0,Number(t.duration)||0),sig=Math.floor(cur)+'|'+Math.floor(dur);const a=d?.getElementById('time'+k),b=d?.getElementById('remain'+k),r=d?.getElementById('seek'+k);const at=fmtSec(cur),bt='-'+fmtSec(Math.max(0,dur-cur));if(a&&a.textContent!==at)a.textContent=at;if(b&&b.textContent!==bt)b.textContent=bt;if(r&&dur>0){const val=String(clamp(cur/dur*1000,0,1000));if(r.value!==val)r.value=val}lastClock[k]=sig}
function clearNativeForSpotify(k){const v=deckMedia(k);if(v){try{v.pause();v.removeAttribute('src');v.load()}catch(e){}}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[k]=null;try{window.AFDYouTubeState?.clear?.(k)}catch(e){}}
function style(){const d=D();if(!d?.head)return;let s=d.getElementById('afd205Style');if(!s){s=d.createElement('style');s.id='afd205Style';d.head.appendChild(s)}s.textContent=`#afdQueue170{overflow:auto!important;min-height:0!important}.afdQ205{display:grid!important;grid-template-columns:24px 24px minmax(0,1fr) 28px 28px 24px 24px 24px!important;gap:4px;align-items:center;padding:5px;border-bottom:1px solid #222a33;font-size:8px}.afdQ205 b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:pointer}.afdQ205 button{height:23px!important;padding:0!important;font-size:7px!important}.afdGrip205{cursor:grab;user-select:none;text-align:center;font-size:15px;color:#dcc9ff}.afdEmpty205{padding:18px;text-align:center;color:#8d99a6}.afdAutoCtl170{gap:5px!important}.afdAutoCtl170 button{min-width:66px!important}#afdSP196{z-index:2147483000!important}#afdSP196 .sp196acts{display:grid!important;grid-template-columns:1fr 1fr!important;gap:5px!important}#afdSP196 [data-d]{display:block!important;visibility:visible!important;opacity:1!important;min-width:52px!important}.deckA .screenRow{grid-template-columns:48px minmax(0,1fr) 34px 48px!important}.deckA .screenRow>.side{grid-column:1!important}.deckA .screenRow>.screen{grid-column:2!important}.deckA .screenRow>#afdDeckKeyA{grid-column:3!important}.deckA .screenRow>.eq{grid-column:4!important}.deckB .screenRow{grid-template-columns:48px 34px minmax(0,1fr) 48px!important}.deckB .screenRow>.eq{grid-column:1!important}.deckB .screenRow>#afdDeckKeyB{grid-column:2!important}.deckB .screenRow>.screen{grid-column:3!important}.deckB .screenRow>.side{grid-column:4!important}.screenRow>#afdDeckKeyA,.screenRow>#afdDeckKeyB{grid-row:1!important;width:34px!important;min-width:34px!important;height:100%!important;min-height:72px!important;align-self:stretch!important;flex:none!important;padding:2px 1px!important;gap:2px!important;border-radius:8px!important}.screenRow>#afdDeckKeyA button,.screenRow>#afdDeckKeyB button{width:27px!important;height:22px!important;min-height:22px!important}.screenRow>#afdDeckKeyA strong,.screenRow>#afdDeckKeyB strong{width:27px!important;height:20px!important}@media(max-width:900px){.deckA .screenRow{grid-template-columns:40px minmax(0,1fr) 30px 40px!important}.deckB .screenRow{grid-template-columns:40px 30px minmax(0,1fr) 40px!important}.screenRow>#afdDeckKeyA,.screenRow>#afdDeckKeyB{width:30px!important;min-width:30px!important}}`}
function positionKeys(){const d=D();if(!d)return;if(!d.getElementById('afdDeckKeyA')||!d.getElementById('afdDeckKeyB'))try{window.__afdWin184?.refresh?.()}catch(e){}for(const k of ['A','B']){const row=d.querySelector('.deck'+k+' .screenRow'),eq=row?.querySelector('.eq'),screen=row?.querySelector('.screen'),box=d.getElementById('afdDeckKey'+k);if(!row||!eq||!screen||!box)continue;box.classList.add('afdKeyEq205');if(k==='A'){if(box.parentNode!==row||box.nextElementSibling!==eq)row.insertBefore(box,eq)}else{if(box.parentNode!==row||box.previousElementSibling!==eq)row.insertBefore(box,screen)}}}
function observeKeys(){keyObservers.forEach(o=>o.disconnect());keyObservers=[];const d=D();if(!d)return;for(const k of ['A','B']){const row=d.querySelector('.deck'+k+' .screenRow'),side=row?.querySelector('.side');for(const target of [row,side])if(target){const o=new MutationObserver(()=>queueMicrotask(positionKeys));o.observe(target,{childList:true});keyObservers.push(o)}}}
function installControls(){const d=D(),ctl=d?.querySelector('.afdAutoCtl170');if(!d||!ctl)return;const start=d.getElementById('afdAutoStart170');if(start)start.textContent='▶ START';let next=d.getElementById('afdStartNext205');if(!next){d.getElementById('afdStartNext194')?.remove();next=d.createElement('button');next.id='afdStartNext205';next.textContent='▶ START NEXT';const stop=d.getElementById('afdAutoStop170');ctl.insertBefore(next,stop||null)}const stop=d.getElementById('afdAutoStop170');if(stop)stop.textContent='■ STOP AUTO'}
function bindDoc(){const d=D();if(!d||d.documentElement.dataset.afdCore205)return;d.documentElement.dataset.afdCore205='1';
 d.addEventListener('click',e=>{const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(row){const it=findItem(row.dataset.key);const side=e.target.closest('[data-side]'),b=e.target.closest('[data-a]');if(side&&it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addQueue(it);return}if(b&&it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadLocal(b.dataset.a,it);return}}
 const hr=e.target?.closest?.('.afdHist192Track');if(hr){const h=historyEntry(hr);if(h?.x){const hd=e.target.closest('[data-hd]'),hs=e.target.closest('[data-side]');if(hd){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadHistory(hd.dataset.hd,h.x);return}if(hs){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const it=historyQueueItem(h.x,h.day);if(it)addQueue(it);return}}}
 if(e.target?.closest?.('#afdHist192All')){const day=currentHistoryDay();if(day){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addHistoryDay(day);return}}
 const q=e.target?.closest?.('#afdQueue170 .afdQ205');if(q){const i=Number(q.dataset.i),b=e.target.closest('[data-load]');if(b){e.preventDefault();e.stopImmediatePropagation();loadAny(b.dataset.load,queue[i]);return}if(e.target.closest('[data-rm]')){e.preventDefault();e.stopImmediatePropagation();removeQueue(i);return}if(e.target.closest('[data-up]')){e.preventDefault();e.stopImmediatePropagation();moveQueue(i,Math.max(0,i-1));return}if(e.target.closest('[data-down]')){e.preventDefault();e.stopImmediatePropagation();moveQueue(i,Math.min(queue.length-1,i+1));return}}
 if(e.target?.closest?.('#afdAutoStart170')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();startNext();return}if(e.target?.closest?.('#afdStartNext205,#afdStartNext194')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();startNext();return}if(e.target?.closest?.('#afdAutoStop170')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();busy=false;status('SIDE VIEW • AUTO STOP • השיר הנוכחי ממשיך');return}},true);
 d.addEventListener('dblclick',e=>{const q=e.target?.closest?.('#afdQueue170 .afdQ205 b');if(q){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();mixQueue(Number(q.closest('.afdQ205').dataset.i));return}const h=e.target?.closest?.('.afdHist192Track b');if(h){const x=historyEntry(h.closest('.afdHist192Track'));if(x?.x){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadHistory(quickDeck(),x.x)}return}const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(row){const it=findItem(row.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadLocal(quickDeck(),it)}}},true);
 d.addEventListener('dragstart',e=>{const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(row){const it=findItem(row.dataset.key);if(it){e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-afd-local-key',it.key)}return}const grip=e.target?.closest?.('#afdQueue170 .afdGrip205');if(grip){const i=Number(grip.closest('.afdQ205').dataset.i);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('application/x-afd-q205',String(i))}},true);
 d.addEventListener('dragover',e=>{if(e.target?.closest?.('.deckA,.deckB,#afdQueue170')){const types=[...(e.dataTransfer?.types||[])];if(types.includes('application/x-afd-local-key')||types.includes('application/x-afd-spotify-item')||types.includes('application/x-afd-q205')){e.preventDefault();e.dataTransfer.dropEffect=types.includes('application/x-afd-q205')?'move':'copy'}}},true);
 d.addEventListener('drop',e=>{const qrow=e.target?.closest?.('#afdQueue170 .afdQ205');const qhost=e.target?.closest?.('#afdQueue170');const from=Number(e.dataTransfer?.getData('application/x-afd-q205'));if(Number.isInteger(from)&&qhost){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const to=qrow?Number(qrow.dataset.i):queue.length-1;if(Number.isInteger(to))moveQueue(from,to);return}const root=e.target?.closest?.('.deckA,.deckB');const localKey=e.dataTransfer?.getData('application/x-afd-local-key');const sp=e.dataTransfer?.getData('application/x-afd-spotify-item');if(root){const k=root.classList.contains('deckA')?'A':'B';if(sp){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{loadSpotify(k,JSON.parse(sp))}catch(x){}return}const it=findItem(localKey);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadLocal(k,it);return}}if(qhost&&localKey){const it=findItem(localKey);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addQueue(it)}}},true);
 const host=d.getElementById('afdQueue170');if(host){queueObserver?.disconnect?.();queueObserver=new MutationObserver(()=>{if(rendering)return;if(host.dataset.afdOwner!=='205'||(queue.length&&!host.querySelector('.afdQ205')))queueMicrotask(renderQueue)});queueObserver.observe(host,{childList:true,subtree:true,attributes:true,attributeFilter:['data-afd-owner']})}}
function bindOuter(){if(document.documentElement.dataset.afdOuter205)return;document.documentElement.dataset.afdOuter205='1';document.addEventListener('click',e=>{if(e.target?.closest?.('#spBtn')&&window.__afdSpotify196?.search){const q=String(document.getElementById('spSearch')?.value||'').trim();if(q){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.__afdSpotify196.search(q,0);setTimeout(forceSpotifyUI,40)}}},true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='spSearch'&&window.__afdSpotify196?.search){const q=String(e.target.value||'').trim();if(q){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.__afdSpotify196.search(q,0);setTimeout(forceSpotifyUI,40)}}},true);window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')setTimeout(()=>{clearNativeForSpotify(k);paintSpotifyClock(k)},0)})}
function forceSpotifyUI(){try{window.__afdSpotify196?.refresh?.()}catch(e){}const p=document.getElementById('afdSP196');if(p&&p.style.display!=='none'){p.style.setProperty('display','flex','important');p.querySelectorAll('[data-d]').forEach(b=>{b.style.setProperty('display','block','important');b.style.setProperty('visibility','visible','important');b.style.setProperty('opacity','1','important')})}for(const id of ['afdSP168Results','afdSP191','afdSP191Panel','spRows166']){const x=document.getElementById(id);if(x&&p&&p.style.display!=='none')x.style.setProperty('display','none','important')}}
function refresh(){style();installControls();bindDoc();bindOuter();renderQueue();positionKeys();observeKeys();forceSpotifyUI();status('AFD CORE 1.5.5 READY')}
window.__afdCore205={refresh,addQueue,renderQueue,startNext,startFirst,mixQueue,loadAny,loadLocal,loadSpotify,mixTo,get queue(){return queue}};
frame()?.addEventListener('load',()=>setTimeout(refresh,220));refresh();setTimeout(refresh,700);setInterval(()=>{style();installControls();bindDoc();positionKeys();forceSpotifyUI();paintSpotifyClock('A');paintSpotifyClock('B');const h=D()?.getElementById('afdQueue170');if(h&&(h.dataset.afdOwner!=='205'||(queue.length&&!h.querySelector('.afdQ205'))))renderQueue()},180);
})();
