(()=>{
if(window.__afdWin177V142){window.__afdWin177V142.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const clean=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const PL_KEY='afdSavedPlaylistFiles177';
const VIDEO=new Set('mp4 m4v mov webm ogv avi wmv asf mkv mpg mpeg m2v ts mts m2ts vob flv f4v 3gp 3g2 rm rmvb divx dv'.split(' '));
const AUDIO=new Set('mp3 wav wave m4a aac flac ogg oga opus wma aiff aif ape ac3 dts amr mka mp2'.split(' '));
let playlists={};try{const x=JSON.parse(localStorage.getItem(PL_KEY)||'{}');if(x&&typeof x==='object')playlists=x}catch(e){}
const extOf=x=>{const n=String(x?.name||x?.path||'').toLowerCase(),m=n.match(/\.([a-z0-9]+)$/);return m?m[1]:''};
const isMedia=f=>VIDEO.has(extOf(f))||AUDIO.has(extOf(f));
const kindOf=x=>VIDEO.has(extOf(x))?'video':'music';
const keyOf=f=>(f.webkitRelativePath||f.name)+'|'+f.size+'|'+f.lastModified;
const folderOf=f=>{const p=f.webkitRelativePath||'';return p.includes('/')?p.split('/').slice(0,-1).join('/'):'Files'};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD PLAYLIST 177.2]',t)}
function saveRegistry(){try{localStorage.setItem(PL_KEY,JSON.stringify(playlists))}catch(e){}}
function broadenInputs(){['folderInput','filesInput'].forEach(id=>document.getElementById(id)?.removeAttribute('accept'));D()?.getElementById('file')?.removeAttribute('accept')}
function captureAllMedia(e){const input=e.target;if(input?.tagName!=='INPUT'||input?.type!=='file'||!input.files?.length)return;const api=window.__afdWin170;if(!api?.items)return;let n=0;[...input.files].forEach(f=>{if(!isMedia(f))return;const k=keyOf(f);if(api.items.some(x=>x.key===k))return;api.items.push({key:k,file:f,folder:folderOf(f),name:f.name,kind:kindOf(f)});n++});if(n)setTimeout(()=>{api.refresh();status('LOCAL LIBRARY • נוספו '+n+' קבצי מדיה')},0)}
if(!window.__afdCaptureMedia177){window.__afdCaptureMedia177=true;document.addEventListener('change',captureAllMedia,true)}
async function loadItem(deck,it){if(!it)return false;if(typeof window.AFDWindowsLoadItem==='function')return window.AFDWindowsLoadItem(deck,it);const w=frame()?.contentWindow;if(!w||typeof w.load!=='function'||!it.file)return false;w.load(deck,it.file);window.dispatchEvent(new CustomEvent('afd-local-load',{detail:{deck,item:it}}));return true}
function installSideDrag(d){if(!d||d.documentElement.dataset.afdSideDrag177v2)return;d.documentElement.dataset.afdSideDrag177v2='1';d.addEventListener('drop',e=>{const root=e.target?.closest?.('.deckA,.deckB');if(!root)return;const raw=e.dataTransfer?.getData('application/x-afd-q-index');if(raw===''||raw==null)return;const i=Number(raw),q=window.__afdWin170?.queue||[],it=q[i];if(!Number.isInteger(i)||!it)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadItem(root.classList.contains('deckB')?'B':'A',it).catch(x=>status('LOAD ERROR • '+x.message))},true)}
async function pathFor(it){let p=it.path||'';const bridge=window.afdDesktopMedia;if(!p&&bridge?.getPath)try{p=await bridge.getPath(it.key)}catch(e){}return p}
async function saveCurrentPlaylist(){const q=window.__afdWin170?.queue||[];if(!q.length){status('PLAYLIST • אין שירים ב-SIDEVIEW');return}const bridge=window.afdDesktopMedia;if(!bridge?.savePlaylist){status('PLAYLIST • שמירה לקובץ זמינה ב-Windows בלבד');return}const tracks=[];for(const it of q){const p=await pathFor(it);if(!p)continue;tracks.push({path:p,name:it.name||p.split(/[\\/]/).pop(),folder:it.folder||'Saved Playlist',kind:it.kind||kindOf(it)})}if(!tracks.length){status('PLAYLIST • לא נמצאו נתיבי קבצים לשמירה');return}try{const res=await bridge.savePlaylist({defaultName:'AFD Playlist',tracks});if(!res||res.canceled)return;playlists[res.name]={name:res.name,path:res.filePath,tracks:res.tracks||tracks};saveRegistry();renderPlaylistBrowser();status('PLAYLIST SAVED • '+res.name+' • '+tracks.length+' שירים')}catch(e){status('PLAYLIST ERROR • '+(e?.message||e))}}
function restoreItem(x){const kind=x.kind==='video'||VIDEO.has(extOf(x))?'video':'music',mime=kind==='video'?'video/mp4':'audio/mpeg',f=new File([],x.name||'Track',{type:mime,lastModified:0});return{key:'saved:'+x.path,file:f,path:x.path,name:x.name||'Track',folder:x.folder||'Saved Playlist',kind}}
async function loadPlaylist(name){let entry=playlists[name];if(!entry)return;let tracks=Array.isArray(entry)?entry:entry.tracks||[];if(entry.path&&window.afdDesktopMedia?.readPlaylist){try{const fresh=await window.afdDesktopMedia.readPlaylist(entry.path);if(fresh?.tracks?.length){tracks=fresh.tracks;entry={...entry,name:fresh.name||name,tracks};playlists[name]=entry;saveRegistry()}}catch(e){status('PLAYLIST ERROR • לא ניתן לפתוח '+name);return}}if(!tracks.length){status('PLAYLIST • '+name+' ריק');return}const api=window.__afdWin170,q=api?.queue;if(!q)return;q.splice(0,q.length,...tracks.map(restoreItem));api.refresh();setTimeout(renderPlaylistBrowser,60);status('PLAYLIST • '+name+' • נטען ל-SIDEVIEW • אפשר START MIX')}
function playlistActive(){const d=D(),cat=d?.querySelector('#afdFolders170 [data-cat="playlist"]');return!!cat?.classList.contains('active')}
function renderPlaylistBrowser(){const d=D(),host=d?.getElementById('afdTracks170');if(!d||!host||!playlistActive())return;const names=Object.keys(playlists).sort((a,b)=>a.localeCompare(b));host.innerHTML=names.length?'<div class="afdSavedPLHint177">PLAYLISTS SAVED • לחץ פעמיים על שם פלייליסט כדי לטעון ל-SIDEVIEW</div>'+names.map(n=>'<div class="afdSavedPLRow177" data-pl="'+clean(n)+'"><span>♫</span><b>'+clean(n)+'</b></div>').join(''):'<div class="afdEmpty170">אין עדיין פלייליסטים שמורים.<br>הוסף שירים ל-SIDEVIEW ולחץ SAVE.</div>';host.querySelectorAll('.afdSavedPLRow177').forEach(r=>{r.addEventListener('click',()=>{host.querySelectorAll('.afdSavedPLRow177').forEach(x=>x.classList.toggle('selected',x===r))});r.addEventListener('dblclick',e=>{e.preventDefault();loadPlaylist(r.dataset.pl)})})}
function bindPlaylistCategory(d){if(!d||d.documentElement.dataset.afdPlaylistCat177v2)return;d.documentElement.dataset.afdPlaylistCat177v2='1';d.addEventListener('click',e=>{if(e.target?.closest?.('#afdFolders170 [data-cat="playlist"]'))setTimeout(renderPlaylistBrowser,20)},true)}
function installPlaylistUI(d){const tabs=d?.querySelector('.afdSideTabs170');if(!tabs)return;let b=d.getElementById('afdSavePlaylist174')||d.getElementById('afdSavePlaylist177');if(b&&!b.dataset.afd177v2){const n=b.cloneNode(true);b.replaceWith(n);b=n}if(!b){b=d.createElement('button');b.id='afdSavePlaylist177';tabs.appendChild(b)}if(!b.dataset.afd177v2){b.dataset.afd177v2='1';b.textContent='💾 SAVE';b.title='שמור את SIDEVIEW כקובץ Playlist במחשב';b.addEventListener('click',saveCurrentPlaylist)}}
function patchRows(d){d?.querySelectorAll('.afdLocalRow170 [data-side]').forEach(b=>{b.textContent='＋SIDEVIEW';b.title='הוסף ל-Side View / Automix'});d?.querySelectorAll('.afdQ170').forEach(r=>{if(r.dataset.afdDrag177v2)return;r.dataset.afdDrag177v2='1';r.addEventListener('dragstart',e=>{const i=Number(r.dataset.i),it=window.__afdWin170?.queue?.[i];if(it)e.dataTransfer.setData('application/x-afd-local-key',it.key||'')},true)})}
function style(d){if(!d?.head)return;d.querySelector('.afdSavedWrap177')?.remove();let s=d.getElementById('afdPlaylistStyle177v2');if(!s){s=d.createElement('style');s.id='afdPlaylistStyle177v2';d.head.appendChild(s)}s.textContent='.afdDeckStrip131{display:none!important}.afdSavedWrap174,.afdSavedWrap177{display:none!important}.afdSideTabs170{grid-template-columns:1fr auto auto!important}.afdSavedPLHint177{position:sticky;top:0;z-index:3;padding:8px 10px;background:#171d25;border-bottom:1px solid #343c47;color:#aeb9c6;font-size:8px;font-weight:900}.afdSavedPLRow177{display:grid;grid-template-columns:28px minmax(0,1fr);gap:8px;align-items:center;padding:10px 12px;border-bottom:1px solid #20262d;font-size:10px;cursor:default}.afdSavedPLRow177:hover{background:#171d25}.afdSavedPLRow177.selected{background:#3b2858;color:#fff}.afdSavedPLRow177 b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px}'}
function refresh(){broadenInputs();const d=D();if(!d)return;style(d);installSideDrag(d);bindPlaylistCategory(d);installPlaylistUI(d);patchRows(d);if(playlistActive())renderPlaylistBrowser()}
const api={refresh,saveCurrentPlaylist,loadPlaylist,renderPlaylistBrowser};window.__afdWin177V142=api;window.__afdWin177=api;frame()?.addEventListener('load',()=>setTimeout(refresh,220));refresh();setTimeout(refresh,700);setInterval(refresh,1200);
})();