(()=>{
if(window.__afdCore195){window.__afdCore195.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return frame()?.contentWindow||null}catch(e){return null}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));const mod=(n,m)=>((n%m)+m)%m;
const info={A:null,B:null},jobs={A:0,B:0},locks={A:null,B:null},meta={A:null,B:null};let mixBusy=false,programPitch=false;
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD CORE 195]',t)}
function media(k){return D()?.getElementById('vid'+k)||null}
function hasSP(k){return!!window.AFDSpotifyState?.has?.(k)}function hasYT(k){return!!D()?.getElementById('ytDeck'+k)}function online(k){return hasSP(k)||hasYT(k)}
function hasSource(k){const v=media(k);return!!((v&&(v.currentSrc||v.src))||online(k))}
function playing(k){const v=media(k);return!!((v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||window.AFDYouTubeState?.isPlaying?.(k)||window.AFDSpotifyState?.isPlaying?.(k))}
function bpmEl(k){const d=D();if(!d)return null;let e=d.getElementById('bpm'+k);if(!e){e=d.querySelector('.deck'+k+' .bpm strong');if(e)e.id='bpm'+k}return e}
function base(k){return Number(info[k]?.bpm||bpmEl(k)?.dataset.afdBaseBpm||0)||0}
function eff(k){const b=locks[k]?.base||base(k),v=media(k);return b>20&&v?b*(Number(v.playbackRate)||1):b}
function paint(k){const e=bpmEl(k),v=media(k),b=locks[k]?.base||base(k);if(!e||!v||!(b>20))return;const n=b*(Number(v.playbackRate)||1);e.dataset.afdBaseBpm=String(b);e.dataset.afdEffectiveBpm=String(n);e.textContent=n.toFixed(1)}
function resetBpm(k,txt='…'){const e=bpmEl(k);if(e){e.textContent=txt;delete e.dataset.afdBaseBpm;delete e.dataset.afdEffectiveBpm;delete e.dataset.afdSync195}}
async function analyze(k,item=null){if(online(k))return null;const m=item||meta[k]||window.AFDLocalDeckMeta?.[k],bridge=window.afdDesktopMedia;if(!m||!bridge)return null;const id=String(m.path||m.key||m.name||'');if(!id)return null;if(info[k]?.id===id&&info[k]?.bpm>20){paint(k);return info[k]}const token=++jobs[k];resetBpm(k,'…');status('BPM • מנתח DECK '+k+'...');try{const r=m.path?await bridge.analyzeBpmPath(m):await bridge.analyzeBpm(m);if(token!==jobs[k])return null;const n=Number(r?.bpm||0);if(!(n>20&&n<260))throw Error('BPM detection failed');info[k]={id,bpm:n,offset:Number(r?.offset)||0,confidence:Number(r?.confidence)||0};const e=bpmEl(k);if(e){e.dataset.afdBaseBpm=String(n);e.dataset.afdBeatOffset=String(info[k].offset)}paint(k);status('BPM • DECK '+k+' = '+eff(k).toFixed(1));return info[k]}catch(e){if(token===jobs[k])resetBpm(k,'—');status('BPM ERROR • DECK '+k+' • '+(e?.message||e));return null}}
function normalizeBase(b,target){let best={base:b,score:1e9};for(const m of [.5,1,2]){const x=b*m,r=target/x;if(r<.55||r>1.8)continue;const s=Math.abs(Math.log(r));if(s<best.score)best={base:x,score:s}}return best.base}
function phase(k,b=null){const v=media(k),i=info[k],bb=b||base(k);if(!v||!i||!(bb>20))return 0;const p=60/bb;return mod((Number(v.currentTime)||0)-i.offset,p)/p}
async function align(k,leader,targetBase){const tv=media(k),li=info[leader],ti=info[k],lb=base(leader);if(!tv||!li||!ti||!(lb>20)||!(targetBase>20))return;const lp=60/lb,tp=60/targetBase,lph=mod((Number(media(leader)?.currentTime)||0)-li.offset,lp)/lp,cur=Number(tv.currentTime)||0,anchor=ti.offset+lph*tp,n=Math.round((cur-anchor)/tp),dest=anchor+n*tp;if(Number.isFinite(tv.duration)&&tv.duration>0)try{tv.currentTime=clamp(dest,0,Math.max(0,tv.duration-.05))}catch(e){}await sleep(45)}
function updatePitch(k,rate){const d=D(),orig=d?.getElementById('pitch'+k),ui=d?.querySelector('#afdPitchInline'+k+' input'),read=d?.getElementById('afdPitchInlineRead'+k),pct=(rate-1)*100;programPitch=true;try{for(const x of [orig,ui])if(x)x.value=String(pct);if(read)read.textContent=(pct>=0?'+':'')+pct.toFixed(1)+'%'}finally{setTimeout(()=>programPitch=false,0)}}
async function syncDeck(k){const leader=k==='A'?'B':'A';if(online(k)||online(leader)){status('SYNC • זמין כרגע לקבצים מקומיים');return false}if(!hasSource(k)||!hasSource(leader)){status('SYNC • צריך שיר בשני הדקים');return false}let a=info[k],b=info[leader];if(!a||!b){status('SYNC • מחכה ל-BPM של שני הדקים...');[a,b]=await Promise.all([a||analyze(k),b||analyze(leader)])}if(!a||!b)return false;const lv=media(leader),tv=media(k),leaderEff=b.bpm*(Number(lv.playbackRate)||1),targetBase=normalizeBase(a.bpm,leaderEff),rate=leaderEff/targetBase;if(!(rate>=.55&&rate<=1.8)){status('SYNC • פער המהירות גדול מדי');return false}try{tv.preservesPitch=true;tv.webkitPreservesPitch=true}catch(e){}tv.playbackRate=rate;locks[k]={leader,base:targetBase};updatePitch(k,rate);await align(k,leader,targetBase);if(!playing(k)){try{tv.volume=0;await tv.play()}catch(e){}}const e=bpmEl(k);if(e)e.dataset.afdSync195='1';paint(leader);paint(k);status('SYNC • DECK '+k+' '+eff(k).toFixed(1)+' BPM = DECK '+leader+' '+eff(leader).toFixed(1)+' BPM');return true}
function follow(){for(const k of ['A','B']){const l=locks[k];if(!l)continue;const leader=l.leader,lv=media(leader),tv=media(k),bi=info[leader];if(!lv||!tv||!bi)continue;const want=bi.bpm*(Number(lv.playbackRate)||1)/l.base;if(want>=.55&&want<=1.8&&Math.abs((Number(tv.playbackRate)||1)-want)>.0001){try{tv.preservesPitch=true;tv.webkitPreservesPitch=true}catch(e){}tv.playbackRate=want;updatePitch(k,want)}paint(leader);paint(k)}}
function setCross(v,finish=false){v=clamp(Number(v)||0,0,100);const d=D(),c=d?.getElementById('cross'),vc=d?.getElementById('videoCross');if(c){c.value=String(v);c.dispatchEvent(new Event('input',{bubbles:true}));if(finish)c.dispatchEvent(new Event('change',{bubbles:true}))}if(vc&&vc!==c){vc.value=String(v);vc.dispatchEvent(new Event('input',{bubbles:true}))}try{window.AFDSpotifyState?.applyCross?.(v)}catch(e){}try{window.AFDYouTubeState?.applyCross?.(v)}catch(e){}try{window.dispatchEvent(new CustomEvent('afd-crossfader',{detail:{value:v}}))}catch(e){}}
async function startDeck(k){if(playing(k))return true;if(hasSP(k)){try{window.AFDSpotifyState?.setLevel?.(k,0);window.AFDSpotifyState?.play?.(k)}catch(e){}}else{const d=D(),b=d?.querySelector('.deck'+k+' [data-act="play"],.deck'+k+' .afdPlay175,.deck'+k+' .play');try{b?.click()}catch(e){}}
 const end=performance.now()+9000;while(performance.now()<end){if(playing(k))return true;await sleep(80)}return playing(k)}
function activeDeck(){const d=D(),x=Number(d?.getElementById('cross')?.value??50),a=playing('A'),b=playing('B');if(a&&!b)return'A';if(b&&!a)return'B';return x>=50?'A':'B'}
async function mixTo(to){if(mixBusy||!['A','B'].includes(to))return false;const from=to==='A'?'B':'A';if(!hasSource(to)){status('MIX • אין שיר ב-DECK '+to);return false}mixBusy=true;try{const start=from==='A'?100:0,end=to==='A'?100:0;setCross(start,true);try{window.AFDSpotifyState?.setLevel?.(to,0)}catch(e){}status('MIX • מפעיל DECK '+to+' בשקט...');if(!await startDeck(to)){status('MIX • DECK '+to+' לא התחיל לנגן');return false}await sleep(220);const dur=5600,t0=performance.now();await new Promise(resolve=>{const tick=()=>{if(!mixBusy)return resolve();const p=Math.min(1,(performance.now()-t0)/dur),s=p*p*(3-2*p),x=start+(end-start)*s;setCross(x,false);if(p>=1){setCross(end,true);resolve()}else setTimeout(tick,45)};tick()});status('MIX • '+from+' → '+to+' הושלם');return true}finally{mixBusy=false}}
async function doMix(){const from=activeDeck();return mixTo(from==='A'?'B':'A')}
function syncUi(){const d=D();if(!d)return;let s=d.getElementById('afdSync195Style');if(!s){s=d.createElement('style');s.id='afdSync195Style';d.head.appendChild(s)}s.textContent=`.transport{grid-template-columns:minmax(58px,1.05fr) minmax(48px,.88fr) minmax(66px,1.05fr) minmax(46px,.75fr) minmax(105px,1.7fr)!important;grid-template-rows:30px 30px!important;column-gap:5px!important;row-gap:7px!important;min-height:67px!important}.transport>.afdPlay175{grid-column:1!important;grid-row:1/3!important;height:67px!important}.transport>.afdPause175{grid-column:2!important;grid-row:1/3!important;height:67px!important}.transport>.afdStop175{grid-column:3!important;grid-row:1!important;height:30px!important;min-height:30px!important}.transport>.afdSync195{grid-column:3!important;grid-row:2!important;height:30px!important;min-height:30px!important;margin-top:0!important;border-radius:5px!important;border:1px solid #9972d2!important;background:linear-gradient(#7950b4,#341e52)!important;color:#fff!important;font-size:10px!important;font-weight:1000!important}.deckB .transport>.afdSync195{border-color:#49a9dc!important;background:linear-gradient(#3189b8,#123f5d)!important}.transport>.afdEject175{grid-column:4!important;grid-row:1/3!important;height:67px!important}.transport>.afdPitchInline175{grid-column:5!important;grid-row:1/3!important;height:67px!important}.transport>.afdSync175,.transport>.afdSync190,.transport>.sync[data-act="sync"]{display:none!important}`;
 for(const k of ['A','B']){const t=d.querySelector('.deck'+k+' .transport');if(!t)continue;let b=d.getElementById('afdSync195'+k);if(!b){b=d.createElement('button');b.id='afdSync195'+k;b.className='afdSync195';b.textContent='SYNC';b.onclick=e=>{e.preventDefault();e.stopPropagation();syncDeck(k)};t.appendChild(b)}}}
function bind(k){const d=D(),v=media(k),p=d?.getElementById('pitch'+k),ui=d?.querySelector('#afdPitchInline'+k+' input');if(v&&!v.dataset.afd195){v.dataset.afd195='1';v.addEventListener('ratechange',()=>{paint(k);follow()})}for(const x of [p,ui])if(x&&!x.dataset.afd195){x.dataset.afd195='1';x.addEventListener('input',()=>{if(!programPitch&&locks[k]){locks[k]=null;const e=bpmEl(k);if(e)delete e.dataset.afdSync195}paint(k)},true)}}
function ownMix(){const d=D(),old=d?.getElementById('afdMixBtn');if(!old||old.dataset.afd195)return;if(old.parentNode){const b=old.cloneNode(true);b.dataset.afd195='1';b.onclick=null;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();doMix()},true);old.replaceWith(b)}}
window.addEventListener('afd-local-preload',e=>{const k=e.detail?.deck;if(k!=='A'&&k!=='B')return;meta[k]=e.detail?.item||null;jobs[k]++;info[k]=null;locks[k]=null;resetBpm(k,'…')});
window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(k!=='A'&&k!=='B')return;meta[k]=e.detail?.item||window.AFDLocalDeckMeta?.[k]||null;jobs[k]++;info[k]=null;locks[k]=null;resetBpm(k,'…');setTimeout(()=>analyze(k,meta[k]),350)});
window.addEventListener('afd-deck-eject',e=>{const k=e.detail?.deck;if(k!=='A'&&k!=='B')return;jobs[k]++;info[k]=null;meta[k]=null;locks[k]=null;resetBpm(k,'—')});
function refresh(){syncUi();ownMix();for(const k of ['A','B']){bpmEl(k);bind(k);paint(k)}follow()}
window.__afdCore195={refresh,analyze,syncDeck,mixTo,doMix,eff,getInfo:k=>info[k]};frame()?.addEventListener('load',()=>setTimeout(refresh,250));refresh();setTimeout(refresh,750);setInterval(refresh,400);
})();