(()=>{
if(window.__afdWin194){window.__afdWin194.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const clean=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const HIST='afdPlaybackHistory194v1';let hist={},histDay=null,ytLoaded={A:null,B:null},lastPlay={A:'',B:''},dragIndex=null,busy=false,nextIndex=0;
try{const x=JSON.parse(localStorage.getItem(HIST)||'{}');if(x&&typeof x==='object')hist=x}catch(e){}
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD UI 194]',t)}
function q(){return window.__afdWin170?.queue||[]}
function dayKey(ts){const d=new Date(ts);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dayLabel(x){try{return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(x+'T12:00:00'))}catch(e){return x}}
function saveHist(){try{const out={};for(const d of Object.keys(hist).sort().slice(-180))out[d]=(hist[d]||[]).slice(-1500);hist=out;localStorage.setItem(HIST,JSON.stringify(hist))}catch(e){}}
function source(k){const sp=window.AFDSpotifyState?.getLoaded?.(k);if(sp)return{source:'Spotify',item:sp,name:sp.name||'Spotify'};if(ytLoaded[k])return{source:'YouTube',item:ytLoaded[k],name:ytLoaded[k].title||ytLoaded[k].name||'YouTube'};const m=window.AFDLocalDeckMeta?.[k];if(m?.name)return{source:'Local',item:{...m},name:m.name};return null}
function playing(k){const d=D(),v=d?.getElementById('vid'+k);return!!((v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||window.AFDYouTubeState?.isPlaying?.(k)||window.AFDSpotifyState?.isPlaying?.(k))}
function record(k){if(!playing(k))return;const s=source(k);if(!s)return;const id=s.source+':'+(s.item?.path||s.item?.id||s.item?.uri||s.name);if(lastPlay[k]===id)return;lastPlay[k]=id;const now=Date.now(),day=dayKey(now),arr=hist[day]||(hist[day]=[]);arr.push({ts:now,time:new Date(now).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}),deck:k,source:s.source,name:s.name,item:s.item});saveHist();if(isHistory())renderHistory()}
function oldDays(){const out={};for(const key of ['afdPlaybackHistory192v1','afdPlaybackHistory177v3'])try{const x=JSON.parse(localStorage.getItem(key)||'{}');if(x&&typeof x==='object')for(const d of Object.keys(x))out[d]=[...(out[d]||[]),...(x[d]||[])]}catch(e){}return out}
function merged(day){const a=(hist[day]||[]).slice(),o=oldDays()[day]||[];for(const x of o){if(!a.some(n=>n.name===x.name&&Math.abs((n.ts||0)-(x.ts||0))<2500))a.push(x)}return a.sort((a,b)=>(a.ts||0)-(b.ts||0))}
function days(){return[...new Set([...Object.keys(hist),...Object.keys(oldDays())])].filter(x=>merged(x).length).sort().reverse()}
function isHistory(){return!!D()?.querySelector('#afdFolders170 [data-cat="history"].active')}
function historyQueueItem(x,day){const n={key:'h194:'+(x.ts||Date.now())+':'+Math.random().toString(36).slice(2),name:x.name||'Track',folder:'History '+day,kind:x.source==='YouTube'?'video':'music',afdHistorySource:x.source,afdHistoryItem:x.item||null};if(x.source==='Local')n.path=x.item?.path||x.path||'';return n}
function pushQueue(it){if(!it)return false;q().push(it);renderQueueSoon();return true}
function renderQueueSoon(){setTimeout(()=>{window.__afdWin170?.refresh?.();setTimeout(()=>{decorateQueue();if(isHistory())renderHistory()},40)},0)}
async function loadEntry(deck,x){if(!x||!['A','B'].includes(deck))return false;try{if(x.source==='Local'){const it={...(x.item||{}),name:x.item?.name||x.name,path:x.item?.path||x.path||'',key:x.item?.key||('hist:'+x.ts)};return await window.AFDWindowsLoadItem?.(deck,it)}if(x.source==='YouTube'){const it=x.item||{};if(!it.id&&!it.videoId)throw Error('אין מזהה YouTube שמור');return await window.AFDYouTubeState?.load?.(deck,{id:it.id||it.videoId,title:it.title||x.name,thumb:it.thumb||''})}if(x.source==='Spotify'){const it=x.item||{};if(!it.id&&!it.uri)throw Error('אין מזהה Spotify שמור');window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck,item:it}}));return true}}catch(e){status('LOAD ERROR • '+(e?.message||e));return false}return false}
async function loadQueueItem(deck,it){if(it?.afdHistorySource)return loadEntry(deck,{source:it.afdHistorySource,item:it.afdHistoryItem,name:it.name,path:it.path});return await window.AFDWindowsLoadItem?.(deck,it)}
function activeDeck(){const d=D(),c=Number(d?.getElementById('cross')?.value??50),a=playing('A'),b=playing('B');if(a&&!b)return'A';if(b&&!a)return'B';return c>=50?'A':'B'}
async function mixItem(i){if(busy)return;const arr=q(),it=arr[i];if(!it)return;busy=true;try{window.__afdWin170?.stopAuto?.();const from=activeDeck(),to=from==='A'?'B':'A';status('SIDEVIEW • טוען '+it.name+' ל-DECK '+to);const ok=await loadQueueItem(to,it);if(ok===false)return;await new Promise(r=>setTimeout(r,180));if(typeof window.__afdCore195?.mixTo==='function')await window.__afdCore195.mixTo(to);else if(typeof window.__afdWin188?.doMix==='function')await window.__afdWin188.doMix();nextIndex=Math.min(arr.length,i+1)}finally{busy=false}}
function move(from,to){const arr=q();if(from===to||from<0||to<0||from>=arr.length||to>=arr.length)return;const [x]=arr.splice(from,1);arr.splice(to,0,x);nextIndex=to;renderQueueSoon();status('SIDEVIEW • הסדר עודכן')}
function decorateQueue(){const d=D(),host=d?.getElementById('afdQueue170');if(!d||!host)return;let s=d.getElementById('afdSide194Style');if(!s){s=d.createElement('style');s.id='afdSide194Style';d.head.appendChild(s)}s.textContent=`.afdQueue170{overflow:auto!important;min-height:105px!important}.afdQ170{grid-template-columns:22px 18px minmax(0,1fr) 28px 28px 24px!important}.afdQ170 .afdDrag194{display:grid;place-items:center;cursor:grab;font-size:13px;color:#bdc7d2}.afdQ170.afdDragOn194{opacity:.55;outline:1px solid #a76dff}.afdQ170.afdDrop194{box-shadow:inset 0 2px #b978ff}.afdStartNext194{background:linear-gradient(#846025,#402a0d)!important;border-color:#b58a42!important}`;
 const ctl=d.querySelector('.afdAutoCtl170');if(ctl&&!d.getElementById('afdStartNext194')){const b=d.createElement('button');b.id='afdStartNext194';b.className='afdStartNext194';b.textContent='▶ START NEXT';b.title='הפעל ומקסס את השיר הבא ב-Side View';b.onclick=e=>{e.preventDefault();if(q().length)mixItem(Math.min(nextIndex,q().length-1))};ctl.insertBefore(b,ctl.children[1]||null)}
 host.querySelectorAll('.afdQ170').forEach(r=>{const i=Number(r.dataset.i);if(!Number.isInteger(i))return;if(!r.querySelector('.afdDrag194')){const h=d.createElement('span');h.className='afdDrag194';h.textContent='☰';r.firstElementChild?.insertAdjacentElement('afterend',h)}r.draggable=true;if(r.dataset.afd194)return;r.dataset.afd194='1';r.addEventListener('click',e=>{if(e.target.closest('button'))return;nextIndex=i;host.querySelectorAll('.afdQ170').forEach(x=>x.style.outline='');r.style.outline='1px solid #7b5aa5'});r.addEventListener('dblclick',e=>{if(e.target.closest('button'))return;e.preventDefault();e.stopPropagation();mixItem(Number(r.dataset.i))},true);r.addEventListener('dragstart',e=>{if(e.target.closest('button')){e.preventDefault();return}dragIndex=Number(r.dataset.i);r.classList.add('afdDragOn194');e.dataTransfer.effectAllowed='move';try{e.dataTransfer.setData('text/x-afd-queue',String(dragIndex))}catch(x){}},true);r.addEventListener('dragover',e=>{if(dragIndex==null)return;e.preventDefault();e.dataTransfer.dropEffect='move';r.classList.add('afdDrop194')},true);r.addEventListener('dragleave',()=>r.classList.remove('afdDrop194'),true);r.addEventListener('drop',e=>{if(dragIndex==null)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const to=Number(r.dataset.i),from=dragIndex;dragIndex=null;move(from,to)},true);r.addEventListener('dragend',()=>{dragIndex=null;host.querySelectorAll('.afdQ170').forEach(x=>x.classList.remove('afdDragOn194','afdDrop194'))},true)})}
function findLocal(key){return(window.__afdWin170?.items||[]).find(x=>x.key===key)||null}
function captureLibrary(){const d=D();if(!d||d.documentElement.dataset.afdLib194)return;d.documentElement.dataset.afdLib194='1';d.addEventListener('click',e=>{const h=e.target?.closest?.('#afdFolders170 [data-cat="history"]');if(h){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();d.querySelectorAll('#afdFolders170 .afdFolder170').forEach(x=>x.classList.remove('active'));h.classList.add('active');histDay=null;renderHistory();return}const side=e.target?.closest?.('.afdLocalRow170 [data-side]');if(side){const row=side.closest('.afdLocalRow170'),it=findLocal(row?.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();pushQueue({...it});status('SIDEVIEW • נוסף '+it.name)}return}const b=e.target?.closest?.('.afdLocalRow170 [data-a]');if(b){const row=b.closest('.afdLocalRow170'),it=findLocal(row?.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.AFDWindowsLoadItem?.(b.dataset.a,it)}return}},true);d.addEventListener('dblclick',e=>{const row=e.target?.closest?.('.afdLocalRow170');if(!row)return;const it=findLocal(row.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.AFDWindowsLoadItem?.('A',it)}},true);for(const k of ['A','B']){const root=d.querySelector('.deck'+k);if(!root||root.dataset.afdDrop194)continue;root.dataset.afdDrop194='1';root.addEventListener('drop',e=>{const key=e.dataTransfer?.getData('application/x-afd-local-key')||e.dataTransfer?.getData('text/plain'),it=findLocal(key);if(!it)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.AFDWindowsLoadItem?.(k,it)},true)}}
function renderHistory(){const d=D(),host=d?.getElementById('afdTracks170');if(!d||!host||!isHistory())return;let s=d.getElementById('afdHist194Style');if(!s){s=d.createElement('style');s.id='afdHist194Style';d.head.appendChild(s);s.textContent=`.afdHist194Day,.afdHist194Row{display:grid;gap:6px;align-items:center;border-bottom:1px solid #252c34}.afdHist194Day{grid-template-columns:34px minmax(0,1fr) 150px;padding:9px;cursor:pointer}.afdHist194Row{grid-template-columns:48px minmax(0,1fr) 92px 34px 34px 52px;padding:6px;direction:ltr}.afdHist194Row b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdHist194Row button{height:24px!important;font-size:7px!important}.afdHist194Head{display:flex;gap:7px;align-items:center;padding:7px;position:sticky;top:0;background:#151b22;z-index:4}.afdHist194Head b{flex:1;text-align:center}`}
 if(histDay){const arr=merged(histDay);host.innerHTML='<div class="afdHist194Head"><button id="h194back">◀ תאריכים</button><b>'+clean(dayLabel(histDay))+'</b><button id="h194all">＋ כל היום ל-SIDEVIEW</button></div>'+arr.map((x,i)=>'<div class="afdHist194Row" data-i="'+i+'"><time>'+clean(x.time||'')+'</time><b>'+clean(x.name||'Track')+'</b><small>'+clean(x.source||'')+' • '+clean(x.deck||'')+'</small><button data-d="A">A</button><button data-d="B">B</button><button data-side>＋SIDE</button></div>').join('');d.getElementById('h194back').onclick=()=>{histDay=null;renderHistory()};d.getElementById('h194all').onclick=()=>{for(const x of arr)pushQueue(historyQueueItem(x,histDay));setTimeout(renderHistory,80)};host.querySelectorAll('.afdHist194Row').forEach(r=>{const x=arr[Number(r.dataset.i)];r.querySelectorAll('[data-d]').forEach(b=>b.onclick=e=>{e.stopPropagation();loadEntry(b.dataset.d,x)});r.querySelector('[data-side]').onclick=e=>{e.stopPropagation();pushQueue(historyQueueItem(x,histDay))};r.querySelector('b').ondblclick=()=>loadEntry('A',x)});return}
 const ds=days();host.innerHTML=ds.length?ds.map(day=>{const a=merged(day);return'<div class="afdHist194Day" data-day="'+day+'"><span>🕘</span><b>'+clean(dayLabel(day))+'</b><small>'+a.length+' שירים</small></div>'}).join(''):'<div class="afdEmpty170">אין עדיין היסטוריית השמעות.</div>';host.querySelectorAll('.afdHist194Day').forEach(r=>r.onclick=()=>{histDay=r.dataset.day;renderHistory()})}
function layout(){const f=frame(),d=D();if(!f||!d)return;document.documentElement.style.overflowY='auto';document.body.style.overflowY='auto';const browser=d.querySelector('.browser'),lib=d.querySelector('.library');if(browser)browser.style.setProperty('display','block','important');if(lib){lib.style.setProperty('display','grid','important');lib.style.setProperty('min-height','250px','important')}const h=Math.ceil(d.documentElement.scrollHeight||d.body.scrollHeight||720);f.style.height=Math.max(720,Math.min(1180,h+8))+'px'}
window.addEventListener('afd-youtube-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')ytLoaded[k]={id:e.detail?.id||e.detail?.videoId||'',title:e.detail?.title||e.detail?.name||'YouTube',thumb:e.detail?.thumb||''}});window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')ytLoaded[k]=null});window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')ytLoaded[k]=null});window.addEventListener('afd-deck-eject',e=>{const k=e.detail?.deck;if(k==='A'||k==='B'){ytLoaded[k]=null;lastPlay[k]=''}});
function refresh(){captureLibrary();decorateQueue();layout()}
window.__afdWin194={refresh,renderHistory,mixItem,move,pushQueue,loadQueueItem};frame()?.addEventListener('load',()=>setTimeout(refresh,250));window.addEventListener('resize',()=>{clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,120)});document.addEventListener('fullscreenchange',()=>setTimeout(layout,180));refresh();setTimeout(refresh,700);setInterval(()=>{record('A');record('B');decorateQueue()},500);setInterval(layout,1500);
})();