(()=>{
if(window.__afd217){window.__afd217.refresh();return}
window.__afd217Active=true;
const F=()=>document.getElementById('console');
const D=()=>{try{return F()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return F()?.contentWindow||null}catch(e){return null}};
const C=()=>window.__afdCore206;
let dragItem=null,boundInner=null;
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD 217]',t)}
function spWrap(i){if(!i)return null;const id=String(i.id||i.uri||'');return id?{key:'sp217:'+id,name:String(i.name||'Spotify'),folder:'Spotify',kind:'music',afdSpotifyItem:i}:null}
function ytWrap(i){const id=String(i?.id||i?.videoId||'');return id?{key:'yt217:'+id,name:String(i?.title||'YouTube'),folder:'YouTube',kind:'video',afdYouTubeItem:{id,title:String(i?.title||'YouTube'),channel:String(i?.channel||''),thumb:String(i?.thumb||'')}}:null}
function rowData(row){const n=Number(row?.dataset.i);if(!Number.isInteger(n))return null;if(row.matches('#afdYTInlineResults .afdYTListRow[data-i]'))return ytWrap(window.AFDYouTubeState?.getItem?.(n)||window.AFDYouTubeState?.getItems?.()?.[n]);if(row.matches('#afdSP196 [data-i]'))return spWrap(window.__afdSpotify196?.getItems?.()?.[n]);return null}
function addSide(x){if(!x)return false;const core=C();if(!core?.addQueue){status('SIDE VIEW ERROR • מנוע הרשימה לא זמין');return false}const before=Array.isArray(core.queue)?core.queue.length:0,ok=core.addQueue(x),after=Array.isArray(core.queue)?core.queue.length:before;if(ok===false||after<=before){status('SIDE VIEW ERROR • השיר לא נוסף');return false}window.__afd212?.renderSide?.(true);window.__afd216?.refresh?.();status((x.afdYouTubeItem?'YOUTUBE':'SPOTIFY')+' • נוסף ל-SIDE VIEW');return true}
function normalizeButtons(){
 document.querySelectorAll('#afdSP196 [data-i]').forEach(row=>{row.querySelectorAll('[data-d]').forEach(b=>b.remove());let b=row.querySelector('[data-side215],[data-side217]');if(!b){b=document.createElement('button');(row.querySelector('.sp196acts')||row).appendChild(b)}b.dataset.side215='spotify';b.dataset.side217='spotify';b.textContent='SIDE +';b.title='הוסף ל-Side View';row.draggable=true});
 document.querySelectorAll('#afdYTInlineResults .afdYTListRow[data-i]').forEach(row=>{row.querySelectorAll('[data-d]').forEach(b=>b.remove());let b=row.querySelector('[data-side215],[data-side217]');if(!b){b=document.createElement('button');row.appendChild(b)}b.dataset.side215='youtube';b.dataset.side217='youtube';b.textContent='SIDE +';b.title='הוסף ל-Side View';row.draggable=true})
}
function pack(x){try{return JSON.stringify(x)}catch(e){return''}}
function unpack(dt){let raw='';try{raw=dt?.getData?.('application/x-afd217-online-json')||dt?.getData?.('application/x-afd216-online-json')||''}catch(e){}if(!raw)try{const t=dt?.getData?.('text/plain')||'';if(t.startsWith('AFD217:'))raw=t.slice(7);else if(t.startsWith('AFD216:'))raw=t.slice(7)}catch(e){}if(raw)try{return JSON.parse(raw)}catch(e){}return dragItem}
function bindOuter(){if(document.documentElement.dataset.afd217outer)return;document.documentElement.dataset.afd217outer='1';document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-side217]');if(!b)return;const row=b.closest?.('#afdYTInlineResults .afdYTListRow[data-i],#afdSP196 [data-i]');if(!row)return;const item=rowData(row);if(!item){status('SIDE VIEW ERROR • לא נמצאו פרטי השיר');return}e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addSide(item)},true);document.addEventListener('dragstart',e=>{const row=e.target?.closest?.('#afdYTInlineResults .afdYTListRow[data-i],#afdSP196 [data-i]');if(!row)return;const item=rowData(row);if(!item){status('DRAG ERROR • לא נמצאו פרטי השיר');return}dragItem=item;const raw=pack(item);try{e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-afd217-online-json',raw);e.dataTransfer.setData('text/plain','AFD217:'+raw)}catch(x){}},true);document.addEventListener('dragend',()=>setTimeout(()=>{dragItem=null},450),true)}
function bindInner(){const w=W();if(!w||!w.document||boundInner===w)return;boundInner=w;const sel='.deckA,.deckB,#afd212side,#afd208side,#afdQueue170,.sideview';w.addEventListener('dragover',e=>{const item=unpack(e.dataTransfer);if(!item||!e.target?.closest?.(sel))return;e.preventDefault();try{e.dataTransfer.dropEffect='copy'}catch(x){}},true);w.addEventListener('drop',e=>{const item=unpack(e.dataTransfer);if(!item)return;const deck=e.target?.closest?.('.deckA,.deckB'),side=e.target?.closest?.('#afd212side,#afd208side,#afdQueue170,.sideview');if(!deck&&!side)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();dragItem=null;if(side){addSide(item);return}const k=deck.classList.contains('deckA')?'A':'B',loader=window.__afdUnified215?.loadDeck||window.__afd215?.loadDeck;if(loader)loader(k,item)},true)}
function css(){let s=document.getElementById('afd217css');if(!s){s=document.createElement('style');s.id='afd217css';document.head.appendChild(s)}s.textContent=`#afdSP196 [data-d]{display:none!important}#afdSP196 [data-side215],#afdSP196 [data-side217]{display:block!important;width:100%!important;height:28px!important;font-size:8px!important;font-weight:900!important}#afdYTInlineResults [data-side215],#afdYTInlineResults [data-side217]{display:block!important;height:28px!important;font-size:8px!important;font-weight:900!important}`}
function refresh(){window.__afd217Active=true;css();normalizeButtons();bindOuter();bindInner()}
window.__afd217={refresh,addSide};F()?.addEventListener('load',()=>setTimeout(()=>{boundInner=null;refresh()},750));refresh();setInterval(refresh,700);
})();
