(()=>{
if(window.__afdSpotify191){window.__afdSpotify191.refresh();return;}
const $=id=>document.getElementById(id),CID='d1b255796dbd444995e8f6e29d4ce2cd';
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let query='',offset=0,total=0,items=[],busy=false,view=localStorage.getItem('afdSpotifyView191')||'grid';
const token=()=>sessionStorage.getItem('afdSPToken')||localStorage.getItem('afdSPAccess169')||'';
const rawFetch=(...a)=>(window.__afdSpotifyOriginalFetch189||window.fetch)(...a);
const redirect=()=>location.origin+location.pathname;
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const rand=(n=64)=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return b64(a)};
const sha=s=>crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));
function status(t){const e=$('status');if(e)e.textContent=t;console.log('[AFD Spotify FULL 191]',t)}
function style(){let s=$('afdSP191Style');if(s)return;s=document.createElement('style');s.id='afdSP191Style';s.textContent=`
#online{position:relative!important;overflow:hidden!important}#afdSP191Panel{position:absolute;inset:0;z-index:80;background:#05070a;display:none;flex-direction:column;min-height:0;direction:ltr}.afdSP191Top{flex:0 0 auto;display:grid;grid-template-columns:minmax(220px,1fr) 90px 86px 86px;gap:7px;padding:8px;border-bottom:1px solid #303944;background:linear-gradient(#1c232b,#0b0e12)}.afdSP191Top input{height:34px!important;border:1px solid #4b5661;border-radius:5px;background:#05070a;color:#fff;padding:0 10px}.afdSP191Top button{height:34px!important;border:1px solid #5b6570;border-radius:5px;background:linear-gradient(#3c4650,#171c22);color:#fff;font-weight:900;font-size:9px}.afdSP191Top .active{border-color:#1ed760!important;background:linear-gradient(#1f8f4e,#0c3d24)!important}.afdSP191Info{padding:5px 10px;font-size:9px;color:#aab5c0;border-bottom:1px solid #20262d;direction:rtl}.afdSP191Body{flex:1;min-height:0;overflow:auto;padding:9px}.afdSP191Grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(155px,1fr));gap:9px}.afdSP191Card{border:1px solid #303943;border-radius:7px;background:linear-gradient(#171d24,#090c10);padding:7px;min-width:0}.afdSP191Card img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:5px;background:#111}.afdSP191Card b,.afdSP191Card span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdSP191Card b{font-size:10px;margin-top:6px}.afdSP191Card span{font-size:8px;color:#9aa6b2;margin:3px 0 7px}.afdSP191Acts{display:grid;grid-template-columns:1fr 1fr;gap:5px}.afdSP191Acts button{height:27px!important;font-size:8px!important;font-weight:1000!important;color:#fff;border:1px solid #59636e;border-radius:4px}.afdSP191List{display:flex;flex-direction:column}.afdSP191Row{display:grid;grid-template-columns:56px minmax(0,1fr) 72px 72px;gap:8px;align-items:center;padding:7px;border-bottom:1px solid #202730}.afdSP191Row img{width:56px;height:56px;object-fit:cover;border-radius:5px}.afdSP191Row b,.afdSP191Row span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdSP191Row span{font-size:8px;color:#9aa6b2}.afdSP191Row button{height:30px!important;color:#fff;border:1px solid #59636e;border-radius:4px;font-size:8px;font-weight:1000}.afdSP191Pager{display:grid;grid-template-columns:100px 1fr 100px;gap:8px;align-items:center;padding:8px;border-top:1px solid #2c343d}.afdSP191Pager span{text-align:center;font-size:9px;color:#b3bec9}.afdSP191Pager button{height:32px!important;border:1px solid #58626d;border-radius:4px;background:#171c22;color:#fff;font-weight:900}.afdSP191Msg{padding:28px;text-align:center;color:#aeb9c5;font-size:11px}@media(max-width:760px){.afdSP191Top{grid-template-columns:1fr 74px 70px 70px}.afdSP191Grid{grid-template-columns:repeat(auto-fill,minmax(130px,1fr))}.afdSP191Row{grid-template-columns:48px minmax(0,1fr) 60px 60px}.afdSP191Row img{width:48px;height:48px}}
`;document.head.appendChild(s)}
function panel(){style();const online=$('online');if(!online)return null;let p=$('afdSP191Panel');if(!p){p=document.createElement('div');p.id='afdSP191Panel';p.innerHTML='<div class="afdSP191Top"><input id="afdSP191Search" placeholder="חפש שיר או אמן ב-Spotify"><button id="afdSP191Go">🔎 חיפוש</button><button id="afdSP191Grid">▦ GRID</button><button id="afdSP191List">☰ LIST</button></div><div id="afdSP191Info" class="afdSP191Info">Spotify Search</div><div id="afdSP191Body" class="afdSP191Body"><div class="afdSP191Msg">חפש שיר או אמן ב‑Spotify</div></div><div id="afdSP191Pager" class="afdSP191Pager"></div>';online.appendChild(p);p.querySelector('#afdSP191Go').onclick=()=>search(p.querySelector('#afdSP191Search').value,0);p.querySelector('#afdSP191Search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search(e.target.value,0)}});p.querySelector('#afdSP191Grid').onclick=()=>setView('grid');p.querySelector('#afdSP191List').onclick=()=>setView('list')}return p}
function openPanel(q=''){const p=panel();if(!p)return;p.style.display='flex';if(q)p.querySelector('#afdSP191Search').value=q;setView(view)}
function closePanel(){const p=$('afdSP191Panel');if(p)p.style.display='none'}
function setView(v){view=v==='list'?'list':'grid';localStorage.setItem('afdSpotifyView191',view);const p=panel();if(!p)return;p.querySelector('#afdSP191Grid')?.classList.toggle('active',view==='grid');p.querySelector('#afdSP191List')?.classList.toggle('active',view==='list');render()}
async function login(q){sessionStorage.setItem('afdSPPendingQ191',q||'');const verifier=rand(64),state='afd168_'+rand(18);sessionStorage.setItem('afdSPVerifier168',verifier);sessionStorage.setItem('afdSPState168',state);sessionStorage.setItem('afdSPAuthBusy168','1');const challenge=b64(await sha(verifier)),u=new URL('https://accounts.spotify.com/authorize');u.search=new URLSearchParams({client_id:CID,response_type:'code',redirect_uri:redirect(),code_challenge_method:'S256',code_challenge:challenge,state,scope:'streaming user-read-email user-read-private user-modify-playback-state user-read-playback-state playlist-read-private playlist-read-collaborative'});status('Spotify • פותח חלון התחברות…');location.href=u.toString()}
async function api(q,off){const t=token();if(!t)throw Error('SPOTIFY_LOGIN');const u=new URL('https://api.spotify.com/v1/search');u.searchParams.set('q',q);u.searchParams.set('type','track');u.searchParams.set('limit','10');u.searchParams.set('offset',String(clampOffset(off)));let r=await rawFetch(u.toString(),{headers:{Authorization:'Bearer '+t}});if(r.status===401){sessionStorage.removeItem('afdSPToken');throw Error('SPOTIFY_LOGIN')}const j=await r.json().catch(()=>({}));if(!r.ok){const msg=j?.error?.message||('Spotify HTTP '+r.status),reason=j?.error?.reason||j?.reason||'';throw Error(reason?msg+' ('+reason+')':msg)}return j}
function clampOffset(n){n=Math.floor(Number(n)||0);return Math.max(0,Math.min(1000,n))}
function render(){const p=panel();if(!p||p.style.display==='none')return;const body=p.querySelector('#afdSP191Body'),pager=p.querySelector('#afdSP191Pager'),inf=p.querySelector('#afdSP191Info');p.querySelector('#afdSP191Grid')?.classList.toggle('active',view==='grid');p.querySelector('#afdSP191List')?.classList.toggle('active',view==='list');if(inf)inf.textContent=query?'Spotify • '+total+' תוצאות • מציג '+(items.length?offset+1:0)+'–'+Math.min(total,offset+items.length):'Spotify Search';if(!items.length){body.innerHTML='<div class="afdSP191Msg">'+(query?'לא נמצאו תוצאות':'חפש שיר או אמן ב‑Spotify')+'</div>';pager.innerHTML='';return}const card=(it,n)=>'<div class="afdSP191Card" data-i="'+n+'"><img src="'+esc(it.album?.images?.[1]?.url||it.album?.images?.[0]?.url||'')+'"><b>'+esc(it.name)+'</b><span>'+esc((it.artists||[]).map(a=>a.name).join(', '))+'</span><div class="afdSP191Acts"><button data-d="A" style="background:#43235f">LOAD A</button><button data-d="B" style="background:#15506a">LOAD B</button></div></div>';const row=(it,n)=>'<div class="afdSP191Row" data-i="'+n+'"><img src="'+esc(it.album?.images?.[2]?.url||it.album?.images?.[1]?.url||it.album?.images?.[0]?.url||'')+'"><div><b>'+esc(it.name)+'</b><span>'+esc((it.artists||[]).map(a=>a.name).join(', '))+' • '+esc(it.album?.name||'')+'</span></div><button data-d="A" style="background:#43235f">LOAD A</button><button data-d="B" style="background:#15506a">LOAD B</button></div>';body.innerHTML='<div class="'+(view==='grid'?'afdSP191Grid':'afdSP191List')+'">'+items.map(view==='grid'?card:row).join('')+'</div>';body.querySelectorAll('[data-i]').forEach(el=>el.querySelectorAll('[data-d]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const it=items[+el.dataset.i];window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:b.dataset.d,item:it}}))}));const prev=offset>0,next=offset+items.length<total&&offset<1000;pager.innerHTML='<button id="afdSP191Prev" '+(!prev?'disabled':'')+'>◀ הקודם</button><span>עמוד '+(Math.floor(offset/10)+1)+'</span><button id="afdSP191Next" '+(!next?'disabled':'')+'>הבא ▶</button>';$('afdSP191Prev')?.addEventListener('click',()=>search(query,Math.max(0,offset-10)));$('afdSP191Next')?.addEventListener('click',()=>search(query,offset+10))}
async function search(q,off=0){q=String(q||'').trim();if(!q||busy)return;busy=true;query=q;offset=clampOffset(off);openPanel(q);const p=panel();p.querySelector('#afdSP191Body').innerHTML='<div class="afdSP191Msg">מחפש ב‑Spotify…</div>';p.querySelector('#afdSP191Pager').innerHTML='';try{const j=await api(q,offset),t=j.tracks||{};items=Array.isArray(t.items)?t.items:[];total=Number(t.total)||0;render();status('Spotify • נמצאו '+total+' תוצאות')}catch(e){if(e.message==='SPOTIFY_LOGIN'){await login(q);return}items=[];p.querySelector('#afdSP191Body').innerHTML='<div class="afdSP191Msg" style="color:#ffaaaa">'+esc(e.message)+'</div>';status('Spotify ERROR • '+e.message)}finally{busy=false}}
function claim(){let b=$('spBtn'),i=$('spSearch');if(!b||!i)return;if(b.dataset.afd191!=='1'){const n=b.cloneNode(true);n.id='spBtn';n.textContent='חיפוש Spotify';n.onclick=null;n.removeAttribute('onclick');['afd191','afd189','afd189bound','afd187','afd187bound','win167','win168','afd84','afd84v2','afd83','afdSP103','bound166','bound167','bound168'].forEach(k=>n.dataset[k]='1');b.replaceWith(n);b=n;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();search(i.value,0)},true);i.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();search(i.value,0)}},true)}const home=$('afdOnlineHome184');if(home&&!home.dataset.afd191){home.dataset.afd191='1';home.addEventListener('click',()=>closePanel(),true)}}
function resume(){const q=sessionStorage.getItem('afdSPPendingQ191')||'';if(q&&token()&&!busy){sessionStorage.removeItem('afdSPPendingQ191');const i=$('spSearch');if(i)i.value=q;search(q,0)}}
function refresh(){claim();panel();resume()}
window.__afdSpotify191={refresh,search,openPanel,closePanel,setView};refresh();setTimeout(refresh,350);setInterval(refresh,700);
})();