(()=>{
if(window.__afdWin175V144){window.__afdWin175V144.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD TRANSPORT 175.4]',t)}
function isPlaying(deck){const d=D(),v=d?.getElementById('vid'+deck),native=!!(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended),yt=!!window.AFDYouTubeState?.isPlaying?.(deck),sp=!!window.AFDSpotifyState?.isPlaying?.(deck);return native||yt||sp}
function hasMedia(deck){const d=D(),v=d?.getElementById('vid'+deck);return!!((v&&(v.currentSrc||v.src))||d?.getElementById('ytDeck'+deck)||d?.getElementById('afdSP105Deck'+deck))}
function clearNative(deck){const d=D(),v=d?.getElementById('vid'+deck),m=d?.getElementById('master'+deck);for(const x of [v,m]){if(!x)continue;try{x.pause()}catch(e){}try{x.removeAttribute('src');x.load()}catch(e){}x.style.display='none'}const post=d?.getElementById('post'+deck);if(post)post.style.display='grid';const title=d?.getElementById('title'+deck);if(title)title.textContent='Drop a track';const time=d?.getElementById('time'+deck);if(time)time.textContent='00:00';const remain=d?.getElementById('remain'+deck);if(remain)remain.textContent='-00:00';const bpm=d?.getElementById('bpm'+deck);if(bpm){bpm.textContent='—';delete bpm.dataset.afdBaseBpm;delete bpm.dataset.afdEffectiveBpm}const logo=d?.getElementById('masterLogo');if(logo){const anyYT=!!(d.getElementById('ytDeckA')||d.getElementById('ytDeckB')),anyVideo=[d.getElementById('vidA'),d.getElementById('vidB')].some(x=>x&&(x.currentSrc||x.src));if(!anyYT&&!anyVideo)logo.style.display='grid'}}
function eject(deck){if(isPlaying(deck)){status('DECK '+deck+' • עצור את השיר לפני EJECT');return false}if(!hasMedia(deck)){status('DECK '+deck+' • הדק כבר ריק');return true}try{window.AFDWindowsLoadState?.cancel?.(deck)}catch(e){}try{window.AFDYouTubeState?.clear?.(deck,null)}catch(e){}try{window.AFDSpotifyState?.clear?.(deck)}catch(e){}clearNative(deck);try{window.__afdWin184?.setTone?.(deck,0,false)}catch(e){}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[deck]=null;window.dispatchEvent(new CustomEvent('afd-deck-eject',{detail:{deck}}));status('DECK '+deck+' • EJECT • הדק ריק');return true}
function makeEject(deck){const d=D(),b=d.createElement('button');b.id='afdEject'+deck;b.className='afdEject175';b.innerHTML='<b>⏏</b><small>EJECT</small>';b.title='הוצא שיר מה-Deck כשהוא ב-STOP';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();eject(deck)});return b}
function pitchInput(deck){const d=D();return d?.getElementById('pitch'+deck)||d?.querySelector('.deck'+deck+' .pitch input')||null}
function effectiveBpm(deck){const d=D(),e=d?.getElementById('bpm'+deck),p=pitchInput(deck);if(!e||!p)return;const pct=Number(p.value)||0;let base=Number(e.dataset.afdBaseBpm||0);const shown=parseFloat(e.textContent);if(!(base>20)&&Number.isFinite(shown)&&shown>20){base=shown/(1+pct/100);if(base>20)e.dataset.afdBaseBpm=String(base)}if(!(base>20))return;const eff=base*(1+pct/100);e.dataset.afdEffectiveBpm=String(eff);e.textContent=eff.toFixed(1)}
function makePitch(deck){const d=D(),wrap=d.createElement('div');wrap.id='afdPitchInline'+deck;wrap.className='afdPitchInline175';wrap.innerHTML='<small>PITCH</small><input type="range" min="-10" max="10" step="0.1"><b id="afdPitchInlineRead'+deck+'">0.0%</b>';const ui=wrap.querySelector('input'),orig=pitchInput(deck);if(orig){ui.min=orig.min||'-10';ui.max=orig.max||'10';ui.step=orig.step||'0.1';ui.value=orig.value||'0'}const push=()=>{const o=pitchInput(deck);if(!o)return;o.value=ui.value;o.dispatchEvent(new Event('input',{bubbles:true}));o.dispatchEvent(new Event('change',{bubbles:true}));syncPitch(deck)};ui.addEventListener('input',push);ui.addEventListener('change',push);return wrap}
function syncPitch(deck){const d=D(),o=pitchInput(deck),ui=d?.querySelector('#afdPitchInline'+deck+' input'),r=d?.getElementById('afdPitchInlineRead'+deck);if(!o||!ui||!r)return;const v=Number(o.value)||0;if(d.activeElement!==ui)ui.value=String(v);r.textContent=(v>0?'+':'')+v.toFixed(1)+'%';effectiveBpm(deck)}
function findBtn(t,re){return[...t.querySelectorAll('button')].find(b=>re.test((b.textContent||'').trim()))||null}
function arrange(deck){const d=D(),root=d?.querySelector('.deck'+deck),t=root?.querySelector('.transport');if(!root||!t)return;const play=t.querySelector('[data-act="play"],.play,.afdPlay148')||findBtn(t,/PLAY/i),pause=t.querySelector('.afdPause109,.afdPause148')||findBtn(t,/PAUSE/i),stop=t.querySelector('.afdStop109,.afdStop148')||findBtn(t,/STOP/i),sync=t.querySelector('.afdSync148,.sync,[data-act="sync"]')||findBtn(t,/SYNC/i);t.querySelectorAll('.afdStopStack175').forEach(stack=>{[...stack.children].forEach(x=>t.insertBefore(x,stack));stack.remove()});let ej=d.getElementById('afdEject'+deck);if(!ej)ej=makeEject(deck);let pw=d.getElementById('afdPitchInline'+deck);if(!pw)pw=makePitch(deck);const origWrap=pitchInput(deck)?.closest('.pitch');if(origWrap)origWrap.classList.add('afdOrigPitchHidden175');[play,pause,stop,ej,pw,sync].forEach(x=>{if(x)t.appendChild(x)});if(play)play.classList.add('afdPlay175');if(pause)pause.classList.add('afdPause175');if(stop)stop.classList.add('afdStop175');if(sync)sync.classList.add('afdSync175');syncPitch(deck)}
function style(){const d=D();if(!d?.head)return;let s=d.getElementById('afdEjectStyle175');if(!s){s=d.createElement('style');s.id='afdEjectStyle175';d.head.appendChild(s)}s.textContent=`
.lower{grid-template-columns:minmax(0,1fr) 88px!important;gap:5px!important;align-items:center!important}.jog{width:84px!important;height:84px!important}.jog:after{inset:25px!important}.afdOrigPitchHidden175{display:none!important}
.transport{display:grid!important;grid-template-columns:minmax(58px,1.08fr) minmax(48px,.9fr) minmax(48px,.9fr) minmax(46px,.78fr) minmax(82px,1.45fr) minmax(58px,1.05fr)!important;gap:4px!important;align-items:stretch!important}.transport>*{grid-column:auto!important;grid-row:1!important;min-width:0!important}.transport button{min-height:46px!important;height:46px!important}.transport>.afdPlay175{grid-column:1!important}.transport>.afdPause175{grid-column:2!important}.transport>.afdStop175{grid-column:3!important}.transport>.afdEject175{grid-column:4!important}.transport>.afdPitchInline175{grid-column:5!important}.transport>.afdSync175{grid-column:6!important}
.afdEject175{width:100%!important;height:46px!important;border:1px solid #737d88;border-radius:5px!important;background:linear-gradient(#3d4650,#15191f 62%,#090b0e);color:#fff;padding:2px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important;box-shadow:inset 0 1px #ffffff55,0 3px #000}.afdEject175 b{font-size:15px;line-height:1}.afdEject175 small{font-size:5px;font-weight:1000}.afdEject175:active{filter:brightness(1.3)}
.afdPitchInline175{height:46px!important;display:grid!important;grid-template-columns:1fr auto!important;grid-template-rows:12px 1fr!important;column-gap:4px!important;align-items:center!important;padding:2px 5px!important;border:1px solid #4e5965;border-radius:5px;background:#090c10;color:#aeb8c4}.afdPitchInline175 small{grid-column:1;font-size:6px;font-weight:900}.afdPitchInline175 b{grid-column:2;grid-row:1;font-size:7px;color:#eadcff;font-variant-numeric:tabular-nums}.afdPitchInline175 input{grid-column:1/-1;grid-row:2;width:100%!important;height:20px!important;margin:0!important;writing-mode:horizontal-tb!important;direction:ltr!important;accent-color:#9b5cff}
@media(max-width:1050px){.transport{grid-template-columns:minmax(52px,1fr) minmax(44px,.82fr) minmax(44px,.82fr) minmax(42px,.72fr) minmax(70px,1.3fr) minmax(52px,1fr)!important;gap:2px!important}.transport button{font-size:8px!important}.afdPitchInline175{padding:2px 3px!important}.lower{grid-template-columns:minmax(0,1fr) 76px!important}.jog{width:72px!important;height:72px!important}}
`}
function refresh(){style();arrange('A');arrange('B')}
const api={refresh,eject,isPlaying,syncPitch,effectiveBpm};window.__afdWin175V144=api;window.__afdWin175=api;frame()?.addEventListener('load',()=>setTimeout(refresh,160));refresh();setTimeout(refresh,600);setInterval(refresh,500);
})();