(()=>{
if(window.__afdWin175){window.__afdWin175.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD EJECT 175]',t)}
function isPlaying(deck){const d=D(),v=d?.getElementById('vid'+deck),native=!!(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended),yt=!!window.AFDYouTubeState?.isPlaying?.(deck),sp=!!window.AFDSpotifyState?.isPlaying?.(deck);return native||yt||sp}
function hasMedia(deck){const d=D(),v=d?.getElementById('vid'+deck);return!!((v&&(v.currentSrc||v.src))||d?.getElementById('ytDeck'+deck)||d?.getElementById('afdSP105Deck'+deck))}
function clearNative(deck){const d=D(),v=d?.getElementById('vid'+deck),m=d?.getElementById('master'+deck);for(const x of [v,m]){if(!x)continue;try{x.pause()}catch(e){}try{x.removeAttribute('src');x.load()}catch(e){}x.style.display='none';delete x.dataset.afdBridge174;delete x.dataset.afdBridge177}const post=d?.getElementById('post'+deck);if(post)post.style.display='grid';const title=d?.getElementById('title'+deck);if(title)title.textContent='Drop a track';const time=d?.getElementById('time'+deck);if(time)time.textContent='00:00';const dur=d?.getElementById('dur'+deck);if(dur)dur.textContent='00:00';const bpm=d?.getElementById('bpm'+deck);if(bpm)bpm.textContent='--.--';const logo=d?.getElementById('masterLogo');if(logo){const anyYT=!!(d.getElementById('ytDeckA')||d.getElementById('ytDeckB')),anyVideo=[d.getElementById('vidA'),d.getElementById('vidB')].some(x=>x&&(x.currentSrc||x.src));if(!anyYT&&!anyVideo)logo.style.display='grid'}}
function eject(deck){if(isPlaying(deck)){status('DECK '+deck+' • עצור את השיר לפני EJECT');return false}if(!hasMedia(deck)){status('DECK '+deck+' • הדק כבר ריק');return true}try{window.AFDYouTubeState?.clear?.(deck,null)}catch(e){}try{window.AFDSpotifyState?.clear?.(deck)}catch(e){}clearNative(deck);try{window.__afdWin176?.setTone?.(deck,0,false)}catch(e){}window.dispatchEvent(new CustomEvent('afd-deck-eject',{detail:{deck}}));status('DECK '+deck+' • EJECT • הדק ריק');return true}
function addButton(deck){const d=D(),root=d?.querySelector('.deck'+deck),pitch=root?.querySelector('.pitch'),lower=pitch?.parentElement;if(!pitch||!lower)return;let b=d.getElementById('afdEject'+deck);if(!b){b=d.createElement('button');b.id='afdEject'+deck;b.className='afdEject175';b.innerHTML='<b>⏏</b><small>EJECT</small>';b.title='הוצא שיר מה-Deck כשהוא לא מנגן';lower.insertBefore(b,pitch);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();eject(deck)})}}
function style(){const d=D();if(!d?.head)return;let s=d.getElementById('afdEjectStyle175');if(!s){s=d.createElement('style');s.id='afdEjectStyle175';d.head.appendChild(s)}s.textContent='.lower{grid-template-columns:minmax(0,1fr) 100px 46px 72px!important}.afdEject175{width:42px;height:48px;align-self:center;justify-self:center;border:1px solid #7d8792;border-radius:6px;background:linear-gradient(#424b56,#171c22 58%,#090b0e);color:#fff;display:grid;place-items:center;padding:2px!important;box-shadow:inset 0 1px #ffffff66,0 3px 5px #000}.afdEject175 b{font-size:19px;line-height:18px}.afdEject175 small{font-size:6px;font-weight:900;letter-spacing:.4px}.afdEject175:active{transform:translateY(1px);filter:brightness(1.25)}'}
function refresh(){style();addButton('A');addButton('B')}
window.__afdWin175={refresh,eject,isPlaying};frame()?.addEventListener('load',()=>setTimeout(refresh,120));refresh();setTimeout(refresh,500);setInterval(refresh,1200);
})();