(()=>{
if(window.__afdWin175V142){window.__afdWin175V142.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD EJECT/PITCH 175.2]',t)}
function isPlaying(deck){const d=D(),v=d?.getElementById('vid'+deck),native=!!(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended),yt=!!window.AFDYouTubeState?.isPlaying?.(deck),sp=!!window.AFDSpotifyState?.isPlaying?.(deck);return native||yt||sp}
function hasMedia(deck){const d=D(),v=d?.getElementById('vid'+deck);return!!((v&&(v.currentSrc||v.src))||d?.getElementById('ytDeck'+deck)||d?.getElementById('afdSP105Deck'+deck))}
function clearNative(deck){const d=D(),v=d?.getElementById('vid'+deck),m=d?.getElementById('master'+deck);for(const x of [v,m]){if(!x)continue;try{x.pause()}catch(e){}try{x.removeAttribute('src');x.load()}catch(e){}x.style.display='none'}const post=d?.getElementById('post'+deck);if(post)post.style.display='grid';const title=d?.getElementById('title'+deck);if(title)title.textContent='Drop a track';const time=d?.getElementById('time'+deck);if(time)time.textContent='00:00';const remain=d?.getElementById('remain'+deck);if(remain)remain.textContent='-00:00';const bpm=d?.getElementById('bpm'+deck);if(bpm)bpm.textContent='—';const logo=d?.getElementById('masterLogo');if(logo){const anyYT=!!(d.getElementById('ytDeckA')||d.getElementById('ytDeckB')),anyVideo=[d.getElementById('vidA'),d.getElementById('vidB')].some(x=>x&&(x.currentSrc||x.src));if(!anyYT&&!anyVideo)logo.style.display='grid'}}
function eject(deck){if(isPlaying(deck)){status('DECK '+deck+' • עצור את השיר לפני EJECT');return false}if(!hasMedia(deck)){status('DECK '+deck+' • הדק כבר ריק');return true}try{window.AFDWindowsLoadState?.cancel?.(deck)}catch(e){}try{window.AFDYouTubeState?.clear?.(deck,null)}catch(e){}try{window.AFDSpotifyState?.clear?.(deck)}catch(e){}clearNative(deck);try{window.__afdWin184?.setTone?.(deck,0,false)}catch(e){}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[deck]=null;window.dispatchEvent(new CustomEvent('afd-deck-eject',{detail:{deck}}));status('DECK '+deck+' • EJECT • הדק ריק');return true}
function makeEject(deck){const d=D(),b=d.createElement('button');b.id='afdEject'+deck;b.className='afdEject175';b.innerHTML='<b>⏏</b><small>EJECT</small>';b.title='הוצא שיר מה-Deck כשהוא ב-STOP';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();eject(deck)});return b}
function arrange(deck){const d=D(),root=d?.querySelector('.deck'+deck),t=root?.querySelector('.transport');if(!root||!t)return;const stop=t.querySelector('.afdStop109,.afdStop148')||[...t.querySelectorAll('button')].find(b=>/STOP/i.test(b.textContent));const sync=t.querySelector('.afdSync148,.sync,[data-act="sync"]');const pitch=root.querySelector('.pitch');if(stop){let stack=t.querySelector('.afdStopStack175');if(!stack){stack=d.createElement('div');stack.className='afdStopStack175';stop.parentElement?.insertBefore(stack,stop);stack.appendChild(stop)}else if(stop.parentElement!==stack)stack.insertBefore(stop,stack.firstChild);let ej=d.getElementById('afdEject'+deck);if(!ej)ej=makeEject(deck);if(ej.parentElement!==stack)stack.appendChild(ej)}if(pitch){pitch.classList.add('afdPitchTransport175');if(pitch.parentElement!==t){if(sync&&sync.parentElement===t)t.insertBefore(pitch,sync);else t.appendChild(pitch)}}}
function style(){const d=D();if(!d?.head)return;let s=d.getElementById('afdEjectStyle175');if(!s){s=d.createElement('style');s.id='afdEjectStyle175';d.head.appendChild(s)}s.textContent=`
.lower{grid-template-columns:minmax(0,1fr) 88px!important;gap:5px!important;align-items:center!important}.jog{width:84px!important;height:84px!important}.jog:after{inset:25px!important}
.transport{display:grid!important;grid-template-columns:minmax(66px,1.15fr) minmax(54px,.9fr) minmax(56px,.9fr) minmax(74px,1fr) minmax(66px,1fr)!important;gap:4px!important;align-items:stretch!important}.transport>.afdPlay148,.transport>[data-act="play"]{grid-column:1!important}.transport>.afdPause148{grid-column:2!important}.transport>.afdStopStack175{grid-column:3!important}.transport>.afdPitchTransport175{grid-column:4!important}.transport>.afdSync148,.transport>.sync,.transport>[data-act="sync"]{grid-column:5!important}
.afdStopStack175{display:grid!important;grid-template-rows:29px 17px!important;gap:2px!important;min-width:0!important}.afdStopStack175>.afdStop109,.afdStopStack175>.afdStop148,.afdStopStack175>button:not(.afdEject175){grid-column:auto!important;width:100%!important;height:29px!important;min-height:29px!important;padding:0 3px!important;font-size:9px!important}.afdEject175{width:100%!important;height:17px!important;min-height:17px!important;border:1px solid #737d88;border-radius:4px!important;background:linear-gradient(#3d4650,#15191f);color:#fff;padding:0 2px!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:3px!important;box-shadow:inset 0 1px #ffffff44}.afdEject175 b{font-size:10px;line-height:1}.afdEject175 small{font-size:5px;font-weight:1000}.afdEject175:active{filter:brightness(1.3)}
.afdPitchTransport175{height:48px!important;min-width:0!important;display:flex!important;flex-direction:column!important;justify-content:center!important;align-items:center!important;gap:1px!important;margin:0!important;padding:2px 3px!important;border:1px solid #4e5965;border-radius:5px;background:#0a0d11;color:#9da8b4;font-size:6px!important}.afdPitchTransport175 input{writing-mode:horizontal-tb!important;direction:ltr!important;width:100%!important;max-width:76px!important;height:18px!important;margin:0!important;accent-color:#9b5cff}
@media(max-width:900px){.lower{grid-template-columns:minmax(0,1fr) 76px!important}.jog{width:72px!important;height:72px!important}.transport{grid-template-columns:minmax(54px,1fr) minmax(46px,.8fr) minmax(48px,.85fr) minmax(60px,.9fr) minmax(54px,1fr)!important;gap:2px!important}.afdPitchTransport175{padding:2px!important}}
`}
function refresh(){style();arrange('A');arrange('B')}
const api={refresh,eject,isPlaying};window.__afdWin175V142=api;window.__afdWin175=api;frame()?.addEventListener('load',()=>setTimeout(refresh,160));refresh();setTimeout(refresh,600);setInterval(refresh,1200);
})();