(()=>{
if(window.__afdRescue202){window.__afdRescue202.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return frame()?.contentWindow||null}catch(e){return null}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const extOf=x=>{const n=String(x?.name||x?.path||'').toLowerCase(),m=n.match(/\.([a-z0-9]+)$/);return m?m[1]:''};
const VIDEO=new Set('mp4 m4v mov webm ogv avi wmv asf mkv mpg mpeg m2v ts mts m2ts vob flv f4v 3gp 3g2 rm rmvb divx dv'.split(' '));
const AUDIO=new Set('mp3 wav wave m4a aac flac ogg oga opus wma aiff aif ape ac3 dts amr mka mp2'.split(' '));
const HIST_KEY='afdRescueHistory202',FAV_KEY='afdRescueFav202',PL_KEY='afdRescuePlaylists202';
let items=[],itemMap=new Map(),queue=[],viewItems=[],active='all',search='',nextIndex=0,busy=false,dragIndex=null,renderLock=false;
let loaded={A:null,B:null},playState={A:false,B:false},history={},playlists={},favs=new Set();
try{history=JSON.parse(localStorage.getItem(HIST_KEY)||'{}')||{}}catch(e){history={}}
try{playlists=JSON.parse(localStorage.getItem(PL_KEY)||'{}')||{}}catch(e){playlists={}}
try{favs=new Set(JSON.parse(localStorage.getItem(FAV_KEY)||'[]'))}catch(e){favs=new Set()}
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD RESCUE 202]',t)}
function keyOf(f){return(f?.webkitRelativePath||f?.name||'')+'|'+(f?.size||0)+'|'+(f?.lastModified||0)}
function folderOf(f){const p=String(f?.webkitRelativePath||'');return p.includes('/')?p.split('/').slice(0,-1).join('/'):'Files'}
function kindOf(x){const e=extOf(x),t=String(x?.type||'');if(VIDEO.has(e)||t.startsWith('video/'))return'video';return'music'}
function mediaFile(f){const e=extOf(f),t=String(f?.type||'');return t.startsWith('audio/')||t.startsWith('video/')||VIDEO.has(e)||AUDIO.has(e)}
function saveFav(){try{localStorage.setItem(FAV_KEY,JSON.stringify([...favs]))}catch(e){}}
function saveHist(){try{const days=Object.keys(history).sort().slice(-180),o={};for(const d of days)o[d]=(history[d]||[]).slice(-1000);history=o;localStorage.setItem(HIST_KEY,JSON.stringify(history))}catch(e){}}
function savePL(){try{localStorage.setItem(PL_KEY,JSON.stringify(playlists))}catch(e){}}
function localDay(ts=Date.now()){const d=new Date(ts);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function dayLabel(day){try{return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(day+'T12:00:00'))}catch(e){return day}}
function normalizeLocal(f){const key=keyOf(f);return{__source:'local',key,file:f,name:f.name,folder:folderOf(f),kind:kindOf(f)}}
function ingest(list){let n=0;for(const f of [...(list||[])]){if(!mediaFile(f))continue;const k=keyOf(f);if(itemMap.has(k))continue;const it=normalizeLocal(f);itemMap.set(k,it);items.push(it);n++}if(n){status('LOCAL • נוספו '+n+' קבצים');renderLibrary()}return n}
function qCopy(it){return{...it,_q202:'q'+Date.now()+Math.random().toString(36).slice(2)}}
function titleOf(it){return String(it?.name||it?.afdHistoryItem?.name||'Track')}
function sourceOf(it){return it?.__source||it?.afdHistorySource?.toLowerCase?.()||'local'}
function addQueue(it){if(!it)return false;queue.push(qCopy(it));renderQueue();status('SIDE VIEW • '+queue.length+' שירים');return true}
function removeQueue(i){if(i<0||i>=queue.length)return;queue.splice(i,1);if(nextIndex>=queue.length)nextIndex=Math.max(0,queue.length-1);renderQueue()}
function moveQueue(from,to){if(from===to||from<0||to<0||from>=queue.length||to>=queue.length)return;const [x]=queue.splice(from,1);queue.splice(to,0,x);if(nextIndex===from)nextIndex=to;renderQueue();status('SIDE VIEW • הסדר עודכן')}
function browser(){return D()?.querySelector('.browser')||null}
function installOuterLayout(){let s=document.getElementById('afdRescueOuter202');if(!s){s=document.createElement('style');s.id='afdRescueOuter202';document.head.appendChild(s)}s.textContent=`.dock>.toolbar,.dock>.tabs,.dock>.tools{display:none!important}.dock>.view{margin:0!important;height:100%!important;min-height:0!important;border:0!important}.dock #local,.dock #automix,.dock #settings{display:none!important}.dock #online{display:grid!important;grid-template-columns:1fr 1fr!important;height:100%!important;min-height:0!important;padding:8px!important;gap:8px!important}.dock #online>.card{min-width:0!important}.dock #online>.card:nth-child(3){display:none!important}#afdRescueBadge202{position:fixed;right:8px;top:7px;z-index:2147483647;background:#07110a;border:1px solid #4bd86f;color:#bfffcf;border-radius:5px;padding:4px 8px;font:900 9px Arial;pointer-events:none}`;let b=document.getElementById('afdRescueBadge202');if(!b){b=document.createElement('div');b.id='afdRescueBadge202';b.textContent='RESCUE CORE 1.5.2';document.body.appendChild(b)}const online=document.getElementById('online');if(online)online.style.setProperty('display','grid','important')}
function installBrowser(){const d=D(),b=browser();if(!d||!b)return false;let st=d.getElementById('afdRescueStyle202');if(!st){st=d.createElement('style');st.id='afdRescueStyle202';d.head.appendChild(st)}st.textContent=`.browser{display:block!important;visibility:visible!important;opacity:1!important;margin-top:8px!important}.browserTop{height:40px!important;display:flex!important;gap:6px!important}.browserTop button{height:29px!important}.library{height:270px!important;display:grid!important;grid-template-columns:185px minmax(0,1fr) 330px!important;min-height:220px!important}.afdR202Folders{padding:7px;border-right:1px solid #343b44;overflow:auto}.afdR202Cat{padding:6px 7px;border-radius:4px;font-size:8px;cursor:pointer}.afdR202Cat.on{background:#43286b;color:#fff}.afdR202Tracks{overflow:auto;min-width:0}.afdR202Head,.afdR202Row{display:grid;grid-template-columns:30px minmax(150px,1.7fr) minmax(85px,1fr) 32px 32px 48px 28px;gap:4px;align-items:center;direction:ltr}.afdR202Head{position:sticky;top:0;z-index:3;padding:5px 6px;background:#181e26;color:#8f9aa7;font-size:7px}.afdR202Row{padding:5px 6px;border-bottom:1px solid #20262e;font-size:8px;cursor:grab}.afdR202Row b,.afdR202Row span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdR202Row button,.afdR202Q button,.afdR202Ctl button{height:23px!important;padding:0 4px!important;font-size:7px!important;border:1px solid #525d68;border-radius:3px;background:#171c22;color:#fff}.afdR202Side{border-left:1px solid #343b44;padding:7px;display:flex;flex-direction:column;min-width:0}.afdR202Ctl{display:grid;grid-template-columns:1fr 1fr 1fr;gap:4px;margin-bottom:5px}.afdR202Ctl .save{grid-column:1/-1}.afdR202Queue{flex:1;min-height:0;overflow:auto;border:1px dashed #46505c;border-radius:4px;padding:3px}.afdR202Q{display:grid;grid-template-columns:20px 20px minmax(0,1fr) 25px 25px 23px;gap:4px;align-items:center;padding:5px;border-bottom:1px solid #20262d;font-size:8px}.afdR202Q b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdR202Grip{font-size:14px;cursor:ns-resize;touch-action:none;text-align:center;color:#d4bdff}.afdR202Empty{padding:18px;text-align:center;color:#7f8a98;font-size:9px;line-height:1.6}.afdR202HistDay,.afdR202PL{padding:8px;border-bottom:1px solid #252c34;cursor:pointer}.afdR202HistDay:hover,.afdR202PL:hover{background:#2a2037}.afdR202HistTrack{display:grid;grid-template-columns:52px minmax(0,1fr) 30px 30px 48px;gap:5px;align-items:center;padding:6px;border-bottom:1px solid #222933}.afdR202HistTrack time{font-size:7px;color:#9ca7b2}.afdR202HistTrack b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdR202Fav.on{color:#ffd75a}.afdR202Search{flex:1;min-width:150px;height:29px;background:#06080c;border:1px solid #3e4650;border-radius:4px;color:#fff;padding:0 8px}`;
 const top=b.querySelector('.browserTop');const lib=b.querySelector('.library');if(!top||!lib)return false;top.innerHTML='<button id="afdR202Folder">📁 OPEN FOLDER</button><button id="afdR202Files">＋ FILES</button><input id="afdR202Search" class="afdR202Search" placeholder="Search local library..."><button id="afdR202Online">🌐 ONLINE</button>';lib.innerHTML='<div id="afdR202Folders" class="afdR202Folders"></div><div id="afdR202Tracks" class="afdR202Tracks"></div><div class="afdR202Side"><h4 style="margin:0 0 5px;font-size:9px">SIDE VIEW</h4><div class="afdR202Ctl"><button id="afdR202Start">▶ START</button><button id="afdR202Next">▶ NEXT</button><button id="afdR202Stop">■ AUTO STOP</button><button id="afdR202Save" class="save">💾 SAVE PLAYLIST</button></div><div id="afdR202Queue" class="afdR202Queue"></div></div>';
 const c=d.getElementById('cross');if(c)c.oninput=null;renderLibrary();renderQueue();return true}
function foldersHtml(){const folders=[...new Set(items.map(x=>x.folder))].sort((a,b)=>a.localeCompare(b));const defs=[['all','LOCAL / ALL'],['music','MUSIC'],['video','MUSIC VIDEO'],['favorites','★ FAVORITES'],['playlists','PLAYLISTS'],['history','HISTORY']];return defs.map(([k,n])=>'<div class="afdR202Cat '+(active===k?'on':'')+'" data-cat="'+k+'">'+n+'</div>').join('')+(folders.length?'<div style="font-size:7px;color:#798491;margin:9px 5px 3px">COMPUTER FOLDERS</div>'+folders.map(f=>'<div class="afdR202Cat '+(active==='folder:'+f?'on':'')+'" data-folder="'+esc(f)+'">📁 '+esc(f)+'</div>').join(''):'')}
function filtered(){let a=items;if(active==='music')a=a.filter(x=>x.kind==='music');else if(active==='video')a=a.filter(x=>x.kind==='video');else if(active==='favorites')a=a.filter(x=>favs.has(x.key));else if(active.startsWith('folder:'))a=a.filter(x=>x.folder===active.slice(7));if(search){const q=search.toLowerCase();a=a.filter(x=>(x.name+' '+x.folder).toLowerCase().includes(q))}return a}
function renderHistory(){const d=D(),h=d?.getElementById('afdR202Tracks');if(!h)return;const chosen=h.dataset.day||'';if(chosen){const arr=(history[chosen]||[]).slice().sort((a,b)=>a.ts-b.ts);viewItems=arr.map(x=>x.item).filter(Boolean);h.innerHTML='<div style="padding:7px"><button id="afdR202HistBack">◀ תאריכים</button> <b>'+esc(dayLabel(chosen))+'</b></div>'+arr.map((x,i)=>'<div class="afdR202HistTrack" data-hi="'+i+'"><time>'+esc(x.time||'')+'</time><b>'+esc(titleOf(x.item))+'</b><button data-ha="A">A</button><button data-ha="B">B</button><button data-hs="1">＋SIDE</button></div>').join('')||'<div class="afdR202Empty">אין השמעות ביום הזה.</div>';return}const days=Object.keys(history).filter(x=>(history[x]||[]).length).sort().reverse();h.innerHTML=days.length?days.map(day=>'<div class="afdR202HistDay" data-day="'+day+'"><b>'+esc(dayLabel(day))+'</b><small style="display:block;color:#8c98a5">'+(history[day]||[]).length+' השמעות</small></div>').join(''):'<div class="afdR202Empty">אין עדיין היסטוריה.</div>'}
function renderPlaylists(){const h=D()?.getElementById('afdR202Tracks');if(!h)return;const names=Object.keys(playlists).sort((a,b)=>a.localeCompare(b));h.innerHTML=names.length?names.map(n=>'<div class="afdR202PL" data-pl="'+esc(n)+'"><b>♫ '+esc(n)+'</b><small style="display:block;color:#8c98a5">'+(playlists[n]?.tracks?.length||0)+' שירים • דאבל קליק ל-SIDE VIEW</small></div>').join(''):'<div class="afdR202Empty">אין פלייליסטים שמורים.</div>'}
function renderLibrary(){const d=D();if(!d)return;const f=d.getElementById('afdR202Folders'),h=d.getElementById('afdR202Tracks');if(!f||!h)return;f.innerHTML=foldersHtml();if(active==='history'){renderHistory();return}if(active==='playlists'){renderPlaylists();return}viewItems=filtered();h.innerHTML='<div class="afdR202Head"><span>#</span><span>NAME</span><span>FOLDER</span><span>A</span><span>B</span><span>＋SIDE</span><span>★</span></div>'+(viewItems.length?viewItems.map((it,i)=>'<div class="afdR202Row" draggable="true" data-vi="'+i+'"><span>'+String(i+1).padStart(2,'0')+'</span><b title="'+esc(it.name)+'">'+esc(it.name)+'</b><span>'+esc(it.folder)+'</span><button data-la="A">A</button><button data-la="B">B</button><button data-side="1">＋SIDE</button><button data-fav="1" class="afdR202Fav '+(favs.has(it.key)?'on':'')+'">★</button></div>').join(''):'<div class="afdR202Empty">פתח תיקייה או הוסף קבצים.</div>')}
function renderQueue(){const h=D()?.getElementById('afdR202Queue');if(!h)return;renderLock=true;h.innerHTML=queue.length?queue.map((it,i)=>'<div class="afdR202Q" data-qi="'+i+'"><span class="afdR202Grip">☰</span><span>'+(i+1)+'</span><b title="דאבל קליק = MIX עכשיו">'+esc(titleOf(it))+'</b><button data-qa="A">A</button><button data-qa="B">B</button><button data-rm="1">×</button></div>').join(''):'<div class="afdR202Empty">הוסף לכאן כמה שירים שתרצה.</div>';renderLock=false}
function sourceReady(k){const d=D(),v=d?.getElementById('vid'+k);return!!(window.AFDSpotifyState?.has?.(k)||window.AFDYouTubeState?.isLoaded?.(k)||d?.getElementById('ytDeck'+k)||(v&&(v.currentSrc||v.src)))}
function playing(k){const d=D(),v=d?.getElementById('vid'+k);return!!(window.AFDSpotifyState?.isPlaying?.(k)||window.AFDYouTubeState?.isPlaying?.(k)||(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended))}
function activeDeck(){const a=playing('A'),b=playing('B');if(a&&!b)return'A';if(b&&!a)return'B';return Number(D()?.getElementById('cross')?.value??50)>=50?'A':'B'}
async function waitSource(k,ms=12000){const end=performance.now()+ms;while(performance.now()<end){if(sourceReady(k))return true;await sleep(70)}return sourceReady(k)}
async function waitPlaying(k,ms=9000){const end=performance.now()+ms;while(performance.now()<end){if(playing(k))return true;await sleep(70)}return playing(k)}
function historyItem(it){if(!it)return null;const s=sourceOf(it);if(s==='spotify')return{__source:'spotify',id:it.id,uri:it.uri,name:it.name,artists:it.artists,album:it.album,duration_ms:it.duration_ms};if(s==='youtube')return{__source:'youtube',id:it.id||it.videoId,name:it.name||it.title,title:it.title||it.name,thumb:it.thumb||''};return{__source:'local',key:it.key||'',path:it.path||'',name:it.name||'Track',folder:it.folder||'History',kind:it.kind||'music'}}
function record(k){const it=loaded[k];if(!it)return;const day=localDay(),arr=history[day]||(history[day]=[]),key=sourceOf(it)+'|'+titleOf(it)+'|'+(it.path||it.id||it.uri||it.key||'');const last=arr[arr.length-1];if(last&&last.deck===k&&last.key===key&&Date.now()-last.ts<15000)return;arr.push({ts:Date.now(),time:new Date().toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}),deck:k,key,item:historyItem(it)});saveHist();if(active==='history')renderLibrary()}
async function loadLocal(k,it){if(!it)return false;status('LOAD • '+titleOf(it)+' → DECK '+k+'…');try{window.AFDSpotifyState?.clear?.(k);window.AFDYouTubeState?.clear?.(k)}catch(e){}let ok=false;try{if(typeof window.AFDWindowsLoadItem==='function')ok=(await window.AFDWindowsLoadItem(k,it))!==false}catch(e){status('WINDOWS LOAD ERROR • '+(e?.message||e))}if(!ok&&it.file&&typeof W()?.load==='function'){try{W().load(k,it.file);const v=D()?.getElementById('vid'+k);if(v)v.volume=1;window.dispatchEvent(new CustomEvent('afd-local-load',{detail:{deck:k,item:it,rescue202:true}}));ok=true}catch(e){status('NATIVE LOAD ERROR • '+(e?.message||e))}}if(ok){loaded[k]={...it,__source:'local'};status('LOADED • '+titleOf(it)+' → DECK '+k)}return ok}
async function loadSpotify(k,it){if(!it)return false;window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:k,item:it}}));const end=performance.now()+3000;while(performance.now()<end&&!window.AFDSpotifyState?.has?.(k))await sleep(60);const ok=!!window.AFDSpotifyState?.has?.(k);if(ok){loaded[k]={...it,__source:'spotify'};status('SPOTIFY LOADED • '+titleOf(it)+' → DECK '+k)}return ok}
async function loadYouTube(k,it){if(!it)return false;const y={...it,id:it.id||it.videoId,title:it.title||it.name||'YouTube'};const ok=(await window.AFDYouTubeState?.load?.(k,y))!==false;if(ok)loaded[k]={...y,__source:'youtube',name:y.title};return ok}
async function loadAny(k,it){const s=sourceOf(it);if(s==='spotify')return loadSpotify(k,it);if(s==='youtube')return loadYouTube(k,it);return loadLocal(k,it)}
async function startDeck(k){if(playing(k))return true;if(window.AFDSpotifyState?.has?.(k)){window.AFDSpotifyState.setLevel?.(k,k==='A'?(Number(D()?.getElementById('cross')?.value||0)/100):(1-Number(D()?.getElementById('cross')?.value||0)/100));window.AFDSpotifyState.play?.(k);return waitPlaying(k)}if(window.AFDYouTubeState?.isLoaded?.(k)){try{window.AFDYouTubeState.play?.(k)}catch(e){}return waitPlaying(k)}const v=D()?.getElementById('vid'+k);if(v&&(v.currentSrc||v.src)){try{v.volume=1;await v.play()}catch(e){}return waitPlaying(k,3000)}return false}
async function mixTo(k){if(window.__afdCore195?.mixTo)return window.__afdCore195.mixTo(k);if(window.__afdWin184?.startMix){window.__afdWin184.startMix();return true}return false}
async function startFirst(){if(!queue.length){status('SIDE VIEW • הרשימה ריקה');return false}busy=true;try{const it=queue[0];const c=D()?.getElementById('cross');if(c){c.value='100';c.dispatchEvent(new Event('input',{bubbles:true}))}if(!(await loadAny('A',it)))return false;if(!(await waitSource('A')))return false;const ok=await startDeck('A');if(ok){nextIndex=queue.length>1?1:0;status('SIDE VIEW • START • '+titleOf(it))}return ok}finally{busy=false}}
async function mixQueue(i){if(busy||!queue[i])return false;busy=true;try{const to=activeDeck()==='A'?'B':'A',it=queue[i];status('SIDE VIEW • מכין '+titleOf(it)+' ל-DECK '+to);if(!(await loadAny(to,it)))return false;if(!(await waitSource(to)))return false;nextIndex=queue.length?(i+1)%queue.length:0;return await mixTo(to)}finally{busy=false}}
async function startNext(){if(busy)return false;if(!queue.length){status('SIDE VIEW • הרשימה ריקה');return false}if(!playing('A')&&!playing('B'))return startFirst();return mixQueue(clamp(nextIndex,0,queue.length-1))}
async function savePlaylist(){if(!queue.length){status('PLAYLIST • SIDE VIEW ריק');return}const bridge=window.afdDesktopMedia;if(!bridge?.savePlaylist){status('PLAYLIST • שמירה זמינה ב-Windows בלבד');return}const tracks=[];for(const it of queue){if(sourceOf(it)!=='local')continue;let p=it.path||'';if(!p&&it.key&&bridge.getPath)try{p=String(await bridge.getPath(it.key)||'')}catch(e){}if(p)tracks.push({path:p,name:it.name,folder:it.folder||'Saved Playlist',kind:it.kind||'music'})}if(!tracks.length){status('PLAYLIST • אין קבצים מקומיים לשמירה');return}try{const r=await bridge.savePlaylist({defaultName:'AFD Playlist',tracks});if(!r||r.canceled)return;playlists[r.name]={path:r.filePath,tracks:r.tracks||tracks};savePL();status('PLAYLIST SAVED • '+r.name);if(active==='playlists')renderLibrary()}catch(e){status('PLAYLIST ERROR • '+(e?.message||e))}}
function restoreTrack(x){return{__source:'local',key:'saved:'+x.path,path:x.path,name:x.name||String(x.path).split(/[\\/]/).pop(),folder:x.folder||'Saved Playlist',kind:x.kind||'music'}}
async function openPlaylist(name){const p=playlists[name];if(!p)return;let tr=p.tracks||[];if(p.path&&window.afdDesktopMedia?.readPlaylist)try{const r=await window.afdDesktopMedia.readPlaylist(p.path);if(r?.tracks?.length)tr=r.tracks}catch(e){}queue=tr.map(restoreTrack);nextIndex=0;renderQueue();status('PLAYLIST • '+name+' → SIDE VIEW')}
function bindOuter(){if(document.documentElement.dataset.afdRescueOuter202)return;document.documentElement.dataset.afdRescueOuter202='1';document.addEventListener('click',e=>{const id=e.target?.id;if(id==='folderBtn'||id==='filesBtn'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const inp=document.getElementById(id==='folderBtn'?'folderInput':'filesInput');if(inp){inp.value='';inp.click()}return}},true);document.addEventListener('change',e=>{const id=e.target?.id;if((id==='folderInput'||id==='filesInput')&&e.target.files?.length){ingest(e.target.files);e.stopPropagation();e.stopImmediatePropagation();setTimeout(()=>{try{e.target.value=''}catch(x){}},0)}},true);window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')loaded[k]={...(e.detail?.item||{}),__source:'local'}});window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k==='A'||k==='B')loaded[k]={...(e.detail?.item||{}),__source:'spotify'}})}
function bindInner(){const d=D();if(!d||d.documentElement.dataset.afdRescue202)return;d.documentElement.dataset.afdRescue202='1';d.addEventListener('click',e=>{const cat=e.target?.closest?.('[data-cat]');if(cat){active=cat.dataset.cat;const h=d.getElementById('afdR202Tracks');if(h)delete h.dataset.day;renderLibrary();return}const fold=e.target?.closest?.('[data-folder]');if(fold){active='folder:'+fold.dataset.folder;renderLibrary();return}if(e.target?.closest?.('#afdR202Folder')){document.getElementById('folderInput')?.click();return}if(e.target?.closest?.('#afdR202Files')){document.getElementById('filesInput')?.click();return}if(e.target?.closest?.('#afdR202Online')){const on=document.getElementById('online');if(on)on.scrollIntoView({behavior:'smooth',block:'nearest'});return}if(e.target?.closest?.('#afdR202Start')){e.preventDefault();startFirst();return}if(e.target?.closest?.('#afdR202Next')){e.preventDefault();startNext();return}if(e.target?.closest?.('#afdR202Stop')){busy=false;status('SIDE VIEW • AUTO STOP • השיר ממשיך');return}if(e.target?.closest?.('#afdR202Save')){savePlaylist();return}const r=e.target?.closest?.('.afdR202Row');if(r){const it=viewItems[Number(r.dataset.vi)];if(!it)return;const b=e.target.closest('[data-la]');if(b){e.preventDefault();e.stopImmediatePropagation();loadLocal(b.dataset.la,it);return}if(e.target.closest('[data-side]')){e.preventDefault();e.stopImmediatePropagation();addQueue(it);return}if(e.target.closest('[data-fav]')){favs.has(it.key)?favs.delete(it.key):favs.add(it.key);saveFav();renderLibrary();return}}const q=e.target?.closest?.('.afdR202Q');if(q){const i=Number(q.dataset.qi),b=e.target.closest('[data-qa]');if(b){loadAny(b.dataset.qa,queue[i]);return}if(e.target.closest('[data-rm]')){removeQueue(i);return}}const day=e.target?.closest?.('.afdR202HistDay');if(day){const h=d.getElementById('afdR202Tracks');h.dataset.day=day.dataset.day;renderHistory();return}if(e.target?.closest?.('#afdR202HistBack')){const h=d.getElementById('afdR202Tracks');delete h.dataset.day;renderHistory();return}const ht=e.target?.closest?.('.afdR202HistTrack');if(ht){const day=d.getElementById('afdR202Tracks')?.dataset.day,rec=(history[day]||[])[Number(ht.dataset.hi)],it=rec?.item;if(!it)return;const b=e.target.closest('[data-ha]');if(b){loadAny(b.dataset.ha,it);return}if(e.target.closest('[data-hs]')){addQueue(it);return}}},true);
 d.addEventListener('input',e=>{if(e.target?.id==='afdR202Search'){search=String(e.target.value||'');renderLibrary()}},true);
 d.addEventListener('dblclick',e=>{const r=e.target?.closest?.('.afdR202Row');if(r){const it=viewItems[Number(r.dataset.vi)];if(it){e.preventDefault();loadLocal('A',it)}return}const q=e.target?.closest?.('.afdR202Q b');if(q){e.preventDefault();mixQueue(Number(q.closest('.afdR202Q').dataset.qi));return}const pl=e.target?.closest?.('.afdR202PL');if(pl){e.preventDefault();openPlaylist(pl.dataset.pl)}},true);
 d.addEventListener('dragstart',e=>{const r=e.target?.closest?.('.afdR202Row');if(!r)return;const it=viewItems[Number(r.dataset.vi)];if(!it)return;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-afd-rescue-key',it.key)},true);
 d.addEventListener('dragover',e=>{if(e.target?.closest?.('.deckA,.deckB')){const t=[...(e.dataTransfer?.types||[])];if(t.includes('application/x-afd-rescue-key')||t.includes('application/x-afd-spotify-item')){e.preventDefault();e.dataTransfer.dropEffect='copy'}}},true);
 d.addEventListener('drop',e=>{const root=e.target?.closest?.('.deckA,.deckB');if(!root)return;const k=root.classList.contains('deckA')?'A':'B',sp=e.dataTransfer?.getData('application/x-afd-spotify-item');if(sp){e.preventDefault();e.stopImmediatePropagation();try{loadSpotify(k,JSON.parse(sp))}catch(x){}return}const key=e.dataTransfer?.getData('application/x-afd-rescue-key'),it=itemMap.get(key);if(it){e.preventDefault();e.stopImmediatePropagation();loadLocal(k,it)}},true);
 d.addEventListener('pointerdown',e=>{const g=e.target?.closest?.('.afdR202Grip');if(g){e.preventDefault();dragIndex=Number(g.closest('.afdR202Q').dataset.qi)}},true);d.addEventListener('pointermove',e=>{if(dragIndex==null)return;const q=d.elementFromPoint(e.clientX,e.clientY)?.closest?.('.afdR202Q');if(!q)return;const to=Number(q.dataset.qi);if(Number.isInteger(to)&&to!==dragIndex){const from=dragIndex;moveQueue(from,to);dragIndex=to}},true);const end=()=>{dragIndex=null};d.addEventListener('pointerup',end,true);d.addEventListener('pointercancel',end,true);
 for(const k of ['A','B']){const v=d.getElementById('vid'+k);if(v&&!v.dataset.afdHist202){v.dataset.afdHist202='1';v.addEventListener('play',()=>record(k))}}
}
function spotifyUiGuard(){const p=document.getElementById('afdSP196');if(p){p.style.setProperty('display',p.style.display==='none'?'none':'flex','important');p.querySelectorAll('[data-d]').forEach(b=>{b.style.setProperty('display','block','important');b.style.setProperty('visibility','visible','important');b.style.setProperty('opacity','1','important')})}}
function watchPlaying(){for(const k of ['A','B']){const now=playing(k);if(now&&!playState[k])record(k);playState[k]=now}}
function refresh(){installOuterLayout();installBrowser();bindOuter();bindInner();spotifyUiGuard();try{window.__afdCore195?.refresh?.();window.__afdSpotify196?.refresh?.()}catch(e){}status('RESCUE CORE 1.5.2 READY')}
window.__afdRescue202={refresh,ingest,loadAny,loadLocal,addQueue,startFirst,startNext,mixQueue,get queue(){return queue},get items(){return items}};
frame()?.addEventListener('load',()=>setTimeout(refresh,180));refresh();setTimeout(refresh,650);setInterval(()=>{if(!D()?.getElementById('afdR202Tracks'))installBrowser();bindInner();spotifyUiGuard();watchPlaying()},700);
})();