(()=>{
if(window.__afd210){window.__afd210.refresh();return;}
const VERSION='__AFD_VERSION__',F=()=>document.getElementById('console'),D=()=>{try{return F()?.contentDocument||null}catch(e){return null}},W=()=>{try{return F()?.contentWindow||null}catch(e){return null}},C=()=>window.__afdCore206,$=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const P1='afdSavedPlaylists208',P2='afdSavedPlaylists210';let bw=null,source={A:null,B:null},ytItem={A:null,B:null},keyWant={A:0,B:0},lastClock={A:'',B:''},lastPlaylistSig='',playlistName='';
const store=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')||{}}catch(e){return{}}},put=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}},queue=()=>Array.isArray(C()?.queue)?C().queue:[],status=t=>{const s=$('status');if(s)s.textContent=t;console.log('[AFD 210]',t)},fmt=n=>{n=Math.max(0,Math.floor(Number(n)||0));const h=Math.floor(n/3600),m=Math.floor((n%3600)/60),s=n%60;return(h?String(h).padStart(2,'0')+':':'')+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')};
function migrate(){if(localStorage.getItem('afdP210Migrated'))return;const n=store(P2),old=store(P1);if(!Object.keys(n).length)for(const[k,v]of Object.entries(old))if(v&&(v.path||v.items?.length))n[k]=v;put(P2,n);localStorage.setItem('afdP210Migrated','1')}
function qname(x){return String(x?.name||x?.afdHistoryItem?.name||x?.afdSpotifyItem?.name||x?.afdYouTubeItem?.title||'Track')}
function itemPath(x){let p=String(x?.path||x?.afdHistoryItem?.path||'');if(p)return p;try{return String(window.afdDesktopMedia?.getPath?.(x?.key||x?.afdHistoryItem?.key||'')||'')}catch(e){return''}}
function ser(x){if(x?.afdHistorySource==='Spotify'||x?.afdSpotifyItem)return{t:'sp',n:qname(x),i:x.afdHistoryItem||x.afdSpotifyItem};if(x?.afdHistorySource==='YouTube'||x?.afdYouTubeItem)return{t:'yt',n:qname(x),i:x.afdHistoryItem||x.afdYouTubeItem};return{t:'lo',n:qname(x),p:itemPath(x),k:String(x?.key||''),f:String(x?.folder||'Playlist'),d:String(x?.kind||'music')}}
function de(x){if(x?.t==='sp')return{key:'pl210:sp:'+(x.i?.id||x.i?.uri||Math.random()),name:x.n||x.i?.name||'Spotify',folder:'Playlist',kind:'music',afdSpotifyItem:x.i};if(x?.t==='yt')return{key:'pl210:yt:'+(x.i?.id||Math.random()),name:x.n||x.i?.title||'YouTube',folder:'Playlist',kind:'video',afdYouTubeItem:{id:x.i?.id||x.i?.videoId,title:x.i?.title||x.n||'YouTube',thumb:x.i?.thumb||''}};if(x?.t==='lo')return{key:x.k||'pl210:'+x.p,path:x.p||'',name:x.n||'Track',folder:x.f||'Playlist',kind:x.d||'music'};return null}
async function saveManual(){const q=queue();if(!q.length){status('PLAYLIST • SIDE VIEW ריק');return}const all=q.map(ser).filter(x=>x.t!=='lo'||x.p);if(!all.length){status('PLAYLIST • אין שירים שאפשר לשמור');return}const tracks=all.filter(x=>x.t==='lo').map(x=>({path:x.p,name:x.n,folder:x.f,kind:x.d}));const bridge=window.afdDesktopMedia;if(!bridge?.savePlaylist){status('PLAYLIST SAVE ERROR • מנוע השמירה של Windows לא זמין');return}try{const r=await bridge.savePlaylist({defaultName:'AFD Playlist',items:all,tracks});if(!r||r.canceled)return;const reg=store(P2),name=String(r.name||'AFD Playlist');reg[name]={name,path:String(r.filePath||''),items:Array.isArray(r.items)?r.items:all,savedAt:Date.now()};put(P2,reg);playlistName='';lastPlaylistSig='';renderPlaylist(true);status('PLAYLIST SAVED • '+name+' • '+all.length+' שירים')}catch(e){status('PLAYLIST SAVE ERROR • '+(e?.message||e))}}
async function savedItems(name){const e=store(P2)[name];if(!e)return[];let a=Array.isArray(e.items)?e.items:[];if(e.path&&window.afdDesktopMedia?.readPlaylist)try{const r=await window.afdDesktopMedia.readPlaylist(e.path);if(r?.items?.length){a=r.items;e.items=a;put(P2,{...store(P2),[name]:e})}}catch(x){status('PLAYLIST • לא ניתן לקרוא את הקובץ '+name)}return a.map(de).filter(Boolean)}
function activePlaylist(){return!!D()?.querySelector('#afdFolders170 [data-cat="playlist"].active')}
function playState(k){const d=D(),v=d?.getElementById('vid'+k);return!!((v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||window.AFDSpotifyState?.isPlaying?.(k)||window.AFDYouTubeState?.isPlaying?.(k))}
function freeDeck(){const a=playState('A'),b=playState('B');if(a&&!b)return'B';if(b&&!a)return'A';if(!a&&!b)return'A';return Number(D()?.getElementById('cross')?.value??50)>=50?'B':'A'}
async function load(k,x){if(!x)return false;try{return(await C()?.loadAny?.(k,x))!==false}catch(e){status('LOAD ERROR • '+(e?.message||e));return false}}
function playlistHost(){const d=D(),tracks=d?.querySelector('.browser .tracks');if(!tracks)return null;let h=d.getElementById('afd210playlist');if(!h){h=d.createElement('div');h.id='afd210playlist';tracks.appendChild(h)}return h}
async function renderPlaylist(force=false){const d=D(),h=playlistHost();if(!d||!h)return;const on=activePlaylist();d.documentElement.classList.toggle('afd210Playlist',on);h.style.display=on?'block':'none';if(!on)return;const reg=store(P2),sig=playlistName+'|'+Object.keys(reg).sort().map(k=>k+':'+(reg[k]?.savedAt||'')).join('|');if(!force&&sig===lastPlaylistSig)return;lastPlaylistSig=sig;if(!playlistName){const names=Object.keys(reg).sort((a,b)=>a.localeCompare(b));h.__items=[];h.innerHTML=names.length?'<div class="p210hint">PLAYLISTS • רק רשימות ששמרת עם SAVE</div>'+names.map(n=>'<div class="p210folder" data-pl="'+E(n)+'"><b>♫ '+E(n)+'</b><small>'+((reg[n]?.items?.length)||0)+' שירים</small><button>פתח</button></div>').join(''):'<div class="p210empty">אין פלייליסטים שמורים.<br>הוסף שירים ל-SIDE VIEW ולחץ SAVE.</div>';return}h.innerHTML='<div class="p210head"><button data-back>◀ פלייליסטים</button><b>'+E(playlistName)+'</b><button data-all>＋ הכל ל-SIDE</button></div><div class="p210empty">טוען…</div>';const a=await savedItems(playlistName);h.__items=a;h.innerHTML='<div class="p210head"><button data-back>◀ פלייליסטים</button><b>'+E(playlistName)+'</b><button data-all>＋ הכל ל-SIDE</button></div>'+(a.length?a.map((x,i)=>'<div class="p210row" draggable="true" data-i="'+i+'"><span>'+String(i+1).padStart(2,'0')+'</span><b title="דאבל-קליק = טען לדק הפנוי">'+E(qname(x))+'</b><small>'+E(x.folder||'Playlist')+'</small><button data-d="A">A</button><button data-d="B">B</button><button data-side>＋SIDE</button></div>').join(''):'<div class="p210empty">הפלייליסט ריק</div>')}
function addSide(x){if(!x)return;C()?.addQueue?.(x);}
function prepareSpotify(k,it){try{window.AFDYouTubeState?.clear?.(k)}catch(e){}const d=D(),v=d?.getElementById('vid'+k);if(v){try{v.pause();v.removeAttribute('src');v.load()}catch(e){}v.style.display='none'}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[k]=null;source[k]={type:'spotify',item:it||null};setTimeout(()=>paintSource(k),30)}
function prepareYouTube(k){try{window.AFDSpotifyState?.clear?.(k)}catch(e){}const d=D(),v=d?.getElementById('vid'+k);if(v){try{v.pause();v.removeAttribute('src');v.load()}catch(e){}v.style.display='none'}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[k]=null;d?.getElementById('afdSP105Deck'+k)?.remove();source[k]={type:'youtube',item:ytItem[k]};}
function paintSource(k){const d=D();if(!d)return;const sp=window.AFDSpotifyState?.getLoaded?.(k);if(sp){source[k]={type:'spotify',item:sp};let h=d.getElementById('afdSP105Deck'+k),screen=d.getElementById('vid'+k)?.closest('.screen')||d.querySelector('.deck'+k+' .screen');if(!h&&screen){h=d.createElement('div');h.id='afdSP105Deck'+k;screen.appendChild(h);h.innerHTML='<div><img style="width:140px;max-width:75%;border-radius:8px"><div data-n style="font-weight:900;margin-top:7px"></div><div data-a style="font-size:10px;color:#aeb7c1"></div></div>'}if(h){h.style.cssText='position:absolute;inset:0;z-index:46;background:#07090c;display:flex;align-items:center;justify-content:center;text-align:center;padding:12px;color:white;pointer-events:none';const im=h.querySelector('img');if(im)im.src=sp.album?.images?.[0]?.url||'';const n=h.querySelector('[data-n]');if(n)n.textContent=sp.name||'Spotify';const a=h.querySelector('[data-a]');if(a)a.textContent=(sp.artists||[]).map(x=>x.name).join(', ')}const t=d.getElementById('title'+k);if(t)t.textContent=sp.name||'Spotify';return}if(source[k]?.type==='youtube'||d.getElementById('ytDeck'+k)){const h=d.getElementById('ytDeck'+k);if(h){h.style.setProperty('display','grid','important');h.style.setProperty('z-index','47','important')}d.getElementById('afdSP105Deck'+k)?.remove();const t=d.getElementById('title'+k),it=ytItem[k];if(t&&it?.title)t.textContent=it.title}}
function paintClock(k){const d=D();if(!d)return;let cur=0,dur=0,type='';if(window.AFDSpotifyState?.has?.(k)){const t=window.AFDSpotifyState?.getTime?.(k)||{};cur=+t.current||0;dur=+t.duration||0;type='sp'}else if(source[k]?.type==='youtube'||d.getElementById('ytDeck'+k)){const t=window.AFDYouTubeState?.getTime?.(k)||{};cur=+t.current||0;dur=+t.duration||0;type='yt'}else return;const sig=type+'|'+Math.floor(cur*4)+'|'+Math.floor(dur);if(sig===lastClock[k])return;lastClock[k]=sig;const a=d.getElementById('time'+k),b=d.getElementById('remain'+k),r=d.getElementById('seek'+k);if(a)a.textContent=fmt(cur);if(b)b.textContent='-'+fmt(Math.max(0,dur-cur));if(r&&dur>0)r.value=String(Math.max(0,Math.min(1000,cur/dur*1000)))}
function youtubeApi(){const s=window.AFDYouTubeState,d=D();if(!s||!d)return;if(!s.isLoaded)s.isLoaded=k=>!!d.getElementById('ytDeck'+k);if(!s.play)s.play=k=>{const b=d.querySelector('.deck'+k+' [data-act="play"],.deck'+k+' .transport .play');if(b){b.click();return true}return false};if(!s.pause)s.pause=k=>{try{window.dispatchEvent(new CustomEvent('afd-deck-transport',{detail:{deck:k,action:'pause'}}));return true}catch(e){return false}}}
function wmpCapture(e){const input=e.target;if(input?.tagName!=='INPUT'||input?.type!=='file'||!input.files?.length)return;const api=window.__afdWin170;if(!api?.items)return;let n=0;for(const f of input.files){if(!/\.wmp$/i.test(f.name||''))continue;const key=(f.webkitRelativePath||f.name)+'|'+f.size+'|'+f.lastModified;if(api.items.some(x=>x.key===key))continue;const p=f.webkitRelativePath||'',folder=p.includes('/')?p.split('/').slice(0,-1).join('/'):'Files';api.items.push({key,file:f,name:f.name,folder,kind:'video'});n++}if(n)setTimeout(()=>api.refresh?.(),0)}
function keyCapture(e){const b=e.target?.closest?.('.afdDeckKey206 button[data-k]');if(!b)return;const box=b.closest('.afdDeckKey206'),k=box?.id?.endsWith('A')?'A':box?.id?.endsWith('B')?'B':'';if(!k)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const delta=Number(b.dataset.k)||0;keyWant[k]=Math.max(-12,Math.min(12,(Number(window.__afdWin184?.getTone?.(k))||keyWant[k]||0)+delta));const read=box.querySelector('strong');if(read)read.textContent=(keyWant[k]>0?'+':'')+keyWant[k];Promise.resolve(window.__afdWin184?.setTone?.(k,keyWant[k])).then(()=>setTimeout(()=>{const got=Number(window.__afdWin184?.getTone?.(k))||0;if(got!==keyWant[k])window.__afdWin184?.setTone?.(k,keyWant[k])},350)).catch(()=>{})}
function bindOuter(){if(document.documentElement.dataset.afd210)return;document.documentElement.dataset.afd210='1';document.addEventListener('change',wmpCapture,true);window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k)prepareSpotify(k,e.detail?.item||null)},true);window.addEventListener('afd-youtube-load',e=>{const k=e.detail?.deck;if(!k)return;ytItem[k]={id:e.detail?.id||e.detail?.videoId||'',title:e.detail?.title||'YouTube',thumb:e.detail?.thumb||''};source[k]={type:'youtube',item:ytItem[k]};setTimeout(()=>paintSource(k),20)},true);window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(k){source[k]={type:'local',item:e.detail?.item||null};keyWant[k]=0;lastClock[k]=''}},true);window.addEventListener('afd-online-drag-load',e=>{if(e.detail?.source==='youtube'&&e.detail?.deck)prepareYouTube(e.detail.deck)},true);window.addEventListener('afd-online-drag-load-confirmed',e=>{if(e.detail?.source==='youtube'&&e.detail?.deck)prepareYouTube(e.detail.deck)},true);document.addEventListener('pointerdown',e=>{const b=e.target?.closest?.('#afdYTInlineResults [data-d]');if(b)prepareYouTube(b.dataset.d)},true)}
function bindInner(){const w=W(),d=D();if(!w||!d||bw===w)return;bw=w;w.addEventListener('click',e=>{keyCapture(e);const t=e.target,side=t?.closest?.('#afd208side');if(side){const a=t.closest?.('[data-a]');if(a){const x=a.dataset.a;if(x==='save'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();saveManual();return}if(x==='clear'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();C()?.clearQueue?.();return}}const r=t.closest?.('.srow');if(r){const i=Number(r.dataset.i);if(t.closest?.('[data-up]')){e.preventDefault();e.stopImmediatePropagation();C()?.moveQueue?.(i,Math.max(0,i-1));return}if(t.closest?.('[data-down]')){e.preventDefault();e.stopImmediatePropagation();C()?.moveQueue?.(i,Math.min(queue().length-1,i+1));return}if(t.closest?.('[data-rm]')){e.preventDefault();e.stopImmediatePropagation();C()?.removeQueue?.(i);return}}}const h=t?.closest?.('#afd210playlist');if(h){const folder=t.closest('.p210folder');if(folder){playlistName=folder.dataset.pl;lastPlaylistSig='';renderPlaylist(true);return}if(t.closest('[data-back]')){playlistName='';lastPlaylistSig='';renderPlaylist(true);return}if(t.closest('[data-all]')){for(const x of h.__items||[])addSide(x);return}const r=t.closest('.p210row');if(r){const x=(h.__items||[])[+r.dataset.i],b=t.closest('[data-d]');if(b)load(b.dataset.d,x);else if(t.closest('[data-side]'))addSide(x);return}}},true);w.addEventListener('dblclick',e=>{const r=e.target?.closest?.('#afd208side .srow');if(r&&!e.target.closest('button')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const i=Number(r.dataset.i),mix=playState('A')||playState('B');C()?.playIndex?.(i,{mix});return}const p=e.target?.closest?.('#afd210playlist .p210row');if(p&&!e.target.closest('button')){const x=(d.getElementById('afd210playlist').__items||[])[+p.dataset.i];load(freeDeck(),x)}},true);d.addEventListener('click',e=>{const b=e.target?.closest?.('#afdFolders170 [data-cat="playlist"]');if(b){playlistName='';lastPlaylistSig='';setTimeout(()=>renderPlaylist(true),30)}},true)}
function css(){const d=D();if(!d?.head)return;let s=d.getElementById('afd210css');if(!s){s=d.createElement('style');s.id='afd210css';d.head.appendChild(s)}s.textContent=`html.afd210Playlist #afd208content{display:none!important}#afd210playlist{position:absolute;inset:0;z-index:214;background:#070a0e;overflow:auto}.p210hint,.p210head{position:sticky;top:0;z-index:3;padding:8px;background:#171d25;border-bottom:1px solid #343c47}.p210head{display:grid;grid-template-columns:100px 1fr 120px;gap:5px;align-items:center}.p210head b{text-align:center}.p210folder{display:grid;grid-template-columns:1fr 110px 55px;gap:6px;align-items:center;padding:9px;border-bottom:1px solid #20262d}.p210row{display:grid;grid-template-columns:28px minmax(130px,1fr) 120px 32px 32px 52px;gap:4px;align-items:center;padding:6px;border-bottom:1px solid #20262d;cursor:grab}.p210row b,.p210folder b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.p210row small,.p210folder small{font-size:8px;color:#9aa6b2}.p210row button,.p210folder button,.p210head button{height:25px!important;font-size:7px!important}.p210empty{padding:22px;text-align:center;color:#8995a2}#afd208side .srow [data-load],#afd208side .srow [data-play]{display:none!important}#afd208side .srow{grid-template-columns:18px minmax(0,1fr) 22px 22px 22px!important}#afd208side .srow b{cursor:pointer}#afdDeckKey206A button,#afdDeckKey206B button{cursor:pointer}`}
function refresh(){migrate();youtubeApi();bindOuter();bindInner();css();renderPlaylist();paintSource('A');paintSource('B')}
window.__afd210={refresh,saveManual,renderPlaylist};F()?.addEventListener('load',()=>setTimeout(()=>{bw=null;refresh()},500));refresh();setInterval(refresh,1200);setInterval(()=>{paintClock('A');paintClock('B')},250);
})();
