(()=>{
if(window.__afdWin201){window.__afdWin201.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return frame()?.contentWindow||null}catch(e){return null}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
let queue=[],nextIndex=0,busy=false,mixBusy=false,dragIndex=null,rendering=false,observer=null;
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD CORE 201]',t)}
function badge(){let b=document.getElementById('afdCoreBadge201');if(!b){b=document.createElement('div');b.id='afdCoreBadge201';b.textContent='CORE 1.5.1';b.style.cssText='position:fixed;right:8px;top:7px;z-index:2147483647;background:#0d1117;border:1px solid #7a56a8;color:#e8d8ff;border-radius:5px;padding:3px 7px;font:800 9px Arial;pointer-events:none;opacity:.9';document.body.appendChild(b)}}
function items(){return Array.from(window.__afdWin170?.items||[])}
function findItem(key){return items().find(x=>String(x?.key)===String(key))||null}
function deckMedia(k){return D()?.getElementById('vid'+k)||null}
function hasSP(k){return!!window.AFDSpotifyState?.has?.(k)}
function hasYT(k){return!!window.AFDYouTubeState?.isLoaded?.(k)||!!D()?.getElementById('ytDeck'+k)}
function hasLocal(k){const v=deckMedia(k);return!!(v&&(v.currentSrc||v.src))&&!hasSP(k)&&!hasYT(k)}
function hasSource(k){return hasSP(k)||hasYT(k)||!!(deckMedia(k)?.currentSrc||deckMedia(k)?.src)}
function isPlaying(k){const v=deckMedia(k);return!!(v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||!!window.AFDSpotifyState?.isPlaying?.(k)||!!window.AFDYouTubeState?.isPlaying?.(k)}
function activeDeck(){const a=isPlaying('A'),b=isPlaying('B');if(a&&!b)return'A';if(b&&!a)return'B';const x=Number(D()?.getElementById('cross')?.value??50);return x>=50?'A':'B'}
function crossValueFor(k){return k==='A'?100:0}
function applyLevels(x){x=clamp(Number(x)||0,0,100);try{window.AFDSpotifyState?.setLevel?.('A',x/100);window.AFDSpotifyState?.setLevel?.('B',1-x/100)}catch(e){}try{window.AFDYouTubeState?.applyCross?.(x)}catch(e){}}
function setCross(x,finish=false){x=clamp(Number(x)||0,0,100);const d=D(),c=d?.getElementById('cross');if(c){c.value=String(x);c.dispatchEvent(new Event('input',{bubbles:true}));if(finish)c.dispatchEvent(new Event('change',{bubbles:true}))}applyLevels(x)}
async function waitSource(k,ms=12000){const end=performance.now()+ms;while(performance.now()<end){if(hasSource(k))return true;await sleep(80)}return hasSource(k)}
async function waitPlaying(k,ms=9000){const end=performance.now()+ms;while(performance.now()<end){if(isPlaying(k))return true;await sleep(80)}return isPlaying(k)}
async function loadLocal(k,it){if(!it)return false;status('LOAD • '+(it.name||'Track')+' → DECK '+k+'…');try{window.AFDSpotifyState?.clear?.(k)}catch(e){}try{window.AFDYouTubeState?.clear?.(k)}catch(e){}
 try{if(typeof window.AFDWindowsLoadItem==='function'){const ok=await window.AFDWindowsLoadItem(k,it);if(ok){status('LOADED • '+(it.name||'Track')+' → DECK '+k);return true}}}catch(e){status('WINDOWS LOAD ERROR • '+(e?.message||e))}
 try{if(it.file&&typeof W()?.load==='function'){W().load(k,it.file);window.dispatchEvent(new CustomEvent('afd-local-load',{detail:{deck:k,item:it,afd201Fallback:true}}));status('LOADED NATIVE • '+(it.name||'Track')+' → DECK '+k);return true}}catch(e){status('NATIVE LOAD ERROR • '+(e?.message||e))}
 return false}
async function loadSpotify(k,it){if(!it)return false;status('SPOTIFY • '+(it.name||'Track')+' → DECK '+k);window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:k,item:it}}));const end=performance.now()+2500;while(performance.now()<end){if(window.AFDSpotifyState?.has?.(k))return true;await sleep(60)}return!!window.AFDSpotifyState?.has?.(k)}
async function loadAny(k,it){if(!it)return false;if(it.__source==='spotify'||it.afdSpotifyItem||it.spotifyItem)return loadSpotify(k,it.afdSpotifyItem||it.spotifyItem||it);if(it.afdHistorySource==='Spotify')return loadSpotify(k,it.afdHistoryItem||it);if(it.afdHistorySource==='Local')return loadLocal(k,{...(it.afdHistoryItem||{}),key:it.afdHistoryItem?.key||it.key,path:it.afdHistoryItem?.path||it.path,name:it.afdHistoryItem?.name||it.name,kind:it.afdHistoryItem?.kind||it.kind});if(it.afdYouTubeItem||it.youtubeItem||it.afdHistorySource==='YouTube'){const y=it.afdYouTubeItem||it.youtubeItem||it.afdHistoryItem||it;return (await window.AFDYouTubeState?.load?.(k,y))!==false}return loadLocal(k,it)}
async function startDeck(k){if(isPlaying(k))return true;if(hasSP(k)){window.AFDSpotifyState?.setLevel?.(k,0);window.AFDSpotifyState?.play?.(k);return waitPlaying(k,9000)}if(hasLocal(k)){const v=deckMedia(k);try{v.volume=0;await v.play()}catch(e){}if(await waitPlaying(k,2500))return true}const d=D(),btn=d?.querySelector('.deck'+k+' .transport .play,.deck'+k+' [data-act="play"]');if(btn){btn.click();return waitPlaying(k,9000)}return false}
async function mixTo(k,duration=5600){if(mixBusy)return false;const from=k==='A'?'B':'A';if(!hasSource(k)){status('MIX • אין מקור ב-DECK '+k);return false}mixBusy=true;try{const start=crossValueFor(from),target=crossValueFor(k);setCross(start,true);if(hasSP(k))window.AFDSpotifyState?.setLevel?.(k,0);else{const v=deckMedia(k);if(v)try{v.volume=0}catch(e){}}
 status('MIX • מפעיל DECK '+k+' בשקט…');if(!(await startDeck(k))){status('MIX • DECK '+k+' לא התחיל');return false}await sleep(180);const win=W()||window,t0=performance.now();await new Promise(resolve=>{const tick=t=>{const p=Math.min(1,(t-t0)/duration),q=p*p*(3-2*p),x=start+(target-start)*q;setCross(x,false);if(p<1)win.requestAnimationFrame(tick);else{setCross(target,true);resolve()}};win.requestAnimationFrame(tick)});status('MIX • '+from+' → '+k+' הושלם');return true}finally{mixBusy=false}}
function qClone(it){return{...it,_q201:'q'+Date.now()+Math.random().toString(36).slice(2)}}
function addQueue(it){if(!it)return false;queue.push(qClone(it));renderQueue();status('SIDE VIEW • '+queue.length+' שירים');return true}
function moveQueue(from,to){if(from===to||from<0||to<0||from>=queue.length||to>=queue.length)return;const [x]=queue.splice(from,1);queue.splice(to,0,x);if(nextIndex===from)nextIndex=to;renderQueue()}
function removeQueue(i){if(i<0||i>=queue.length)return;queue.splice(i,1);if(nextIndex>=queue.length)nextIndex=Math.max(0,queue.length-1);renderQueue()}
function renderQueue(){const d=D(),h=d?.getElementById('afdQueue170');if(!h)return;rendering=true;h.dataset.afdOwner='201';h.innerHTML=queue.length?queue.map((it,i)=>'<div class="afdQ201" data-i="'+i+'"><span class="afdGrip201" title="גרור לשינוי סדר">☰</span><span>'+(i+1)+'</span><b>'+esc(it.name||it.afdHistoryItem?.name||'Track')+'</b><button data-load="A">A</button><button data-load="B">B</button><button data-up="1">▲</button><button data-down="1">▼</button><button data-rm="1">×</button></div>').join(''):'<div class="afdEmpty201">SIDE VIEW ריק • הוסף שירים מהספרייה</div>';rendering=false}
async function startFirst(){if(!queue.length){status('SIDE VIEW • הרשימה ריקה');return false}const it=queue[0];setCross(100,true);if(!(await loadAny('A',it)))return false;if(!(await waitSource('A',12000)))return false;const ok=await startDeck('A');if(ok){setCross(100,true);nextIndex=queue.length>1?1:0;status('SIDE VIEW • START • '+(it.name||'Track'))}return ok}
async function mixQueue(i){if(busy||!queue[i])return false;busy=true;try{const to=activeDeck()==='A'?'B':'A',it=queue[i];status('SIDE VIEW • מכין '+(it.name||'Track')+' ל-DECK '+to);if(!(await loadAny(to,it)))return false;if(!(await waitSource(to,12000)))return false;nextIndex=queue.length?(i+1)%queue.length:0;return await mixTo(to)}finally{busy=false}}
async function startNext(){if(!queue.length){status('SIDE VIEW • הרשימה ריקה');return false}if(!isPlaying('A')&&!isPlaying('B'))return startFirst();return mixQueue(clamp(nextIndex,0,queue.length-1))}
function style(){const d=D();if(!d)return;let s=d.getElementById('afd201Style');if(!s){s=d.createElement('style');s.id='afd201Style';d.head.appendChild(s)}s.textContent=`#afdQueue170{overflow:auto!important}.afdQ201{display:grid!important;grid-template-columns:24px 22px minmax(0,1fr) 28px 28px 24px 24px 24px!important;gap:4px;align-items:center;padding:5px;border-bottom:1px solid #222a33;font-size:8px}.afdQ201 b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdQ201 button{height:23px!important;padding:0!important;font-size:7px!important}.afdGrip201{cursor:ns-resize;touch-action:none;user-select:none;text-align:center;font-size:15px;color:#d6c0ff}.afdEmpty201{padding:18px;text-align:center;color:#8d99a6}.afdSync195{margin-top:7px!important}#afdSP196{z-index:2147482000!important}#afdSP196 .sp196acts{display:grid!important;grid-template-columns:1fr 1fr!important}#afdSP196 [data-d]{display:block!important;visibility:visible!important;opacity:1!important}`}
function bindDoc(){const d=D();if(!d||d.documentElement.dataset.afdCore201)return;d.documentElement.dataset.afdCore201='1';
 d.addEventListener('click',e=>{const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(row){const it=findItem(row.dataset.key);const side=e.target.closest('[data-side]');const b=e.target.closest('[data-a]');if(side&&it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();addQueue(it);return}if(b&&it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadLocal(b.dataset.a,it);return}}
 const qr=e.target?.closest?.('#afdQueue170 .afdQ201');if(qr){const i=Number(qr.dataset.i);if(e.target.closest('[data-load]')){e.preventDefault();e.stopImmediatePropagation();loadAny(e.target.closest('[data-load]').dataset.load,queue[i]);return}if(e.target.closest('[data-rm]')){e.preventDefault();e.stopImmediatePropagation();removeQueue(i);return}if(e.target.closest('[data-up]')){e.preventDefault();e.stopImmediatePropagation();moveQueue(i,Math.max(0,i-1));return}if(e.target.closest('[data-down]')){e.preventDefault();e.stopImmediatePropagation();moveQueue(i,Math.min(queue.length-1,i+1));return}}
 const start=e.target?.closest?.('#afdAutoStart170,#afdStartNext194');if(start){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();startNext();return}},true);
 d.addEventListener('dblclick',e=>{const q=e.target?.closest?.('#afdQueue170 .afdQ201 b');if(q){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();mixQueue(Number(q.closest('.afdQ201').dataset.i));return}const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(row){const it=findItem(row.dataset.key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadLocal('A',it)}}},true);
 d.addEventListener('dragstart',e=>{const row=e.target?.closest?.('#afdTracks170 .afdLocalRow170');if(!row)return;const it=findItem(row.dataset.key);if(!it)return;e.dataTransfer.effectAllowed='copy';e.dataTransfer.setData('application/x-afd-local-key',it.key)},true);
 d.addEventListener('dragover',e=>{if(e.target?.closest?.('.deckA,.deckB')){const t=[...(e.dataTransfer?.types||[])];if(t.includes('application/x-afd-local-key')||t.includes('application/x-afd-spotify-item')){e.preventDefault();e.dataTransfer.dropEffect='copy'}}},true);
 d.addEventListener('drop',e=>{const root=e.target?.closest?.('.deckA,.deckB');if(!root)return;const k=root.classList.contains('deckA')?'A':'B';const sp=e.dataTransfer?.getData('application/x-afd-spotify-item');if(sp){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{loadSpotify(k,JSON.parse(sp))}catch(x){}return}const key=e.dataTransfer?.getData('application/x-afd-local-key');const it=findItem(key);if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadLocal(k,it)}},true);
 d.addEventListener('pointerdown',e=>{const g=e.target?.closest?.('#afdQueue170 .afdGrip201');if(!g)return;e.preventDefault();dragIndex=Number(g.closest('.afdQ201').dataset.i)},true);
 d.addEventListener('pointermove',e=>{if(dragIndex==null)return;const hit=d.elementFromPoint(e.clientX,e.clientY)?.closest?.('#afdQueue170 .afdQ201');if(!hit)return;const to=Number(hit.dataset.i);if(Number.isInteger(to)&&to!==dragIndex){const from=dragIndex;moveQueue(from,to);dragIndex=to}},true);
 const end=()=>{dragIndex=null};d.addEventListener('pointerup',end,true);d.addEventListener('pointercancel',end,true);
 const host=d.getElementById('afdQueue170');if(host){observer?.disconnect?.();observer=new MutationObserver(()=>{if(rendering)return;if(!host.querySelector('.afdQ201')&&queue.length)setTimeout(renderQueue,0)});observer.observe(host,{childList:true,subtree:true})}}
function bindOuter(){if(document.documentElement.dataset.afdOuter201)return;document.documentElement.dataset.afdOuter201='1';document.addEventListener('click',e=>{const b=e.target?.closest?.('#spBtn');if(!b)return;const q=String(document.getElementById('spSearch')?.value||'').trim();if(q&&window.__afdSpotify196?.search){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.__afdSpotify196.search(q,0)}},true);document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target?.id==='spSearch'&&window.__afdSpotify196?.search){const q=String(e.target.value||'').trim();if(q){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.__afdSpotify196.search(q,0)}}},true)}
function refresh(){badge();style();bindDoc();bindOuter();renderQueue();try{window.__afdSpotify196?.refresh?.()}catch(e){}status('AFD CORE 1.5.1 READY')}
window.__afdWin201={refresh,addQueue,renderQueue,startNext,startFirst,mixQueue,loadAny,loadLocal,mixTo,get queue(){return queue}};
frame()?.addEventListener('load',()=>setTimeout(refresh,250));refresh();setTimeout(refresh,700);setInterval(()=>{style();bindDoc();if(!D()?.querySelector('#afdQueue170 .afdQ201')&&queue.length)renderQueue()},1000);
})();