(()=>{
if(window.__afdWin177V143){window.__afdWin177V143.refresh();return;}
const frame=()=>document.getElementById('console');
const D=()=>{try{return frame()?.contentDocument||null}catch(e){return null}};
const clean=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const PL_KEY='afdSavedPlaylistFiles177',HIST_KEY='afdPlaybackHistory177v3';
const VIDEO=new Set('mp4 m4v mov webm ogv avi wmv asf mkv mpg mpeg m2v ts mts m2ts vob flv f4v 3gp 3g2 rm rmvb divx dv'.split(' '));
const AUDIO=new Set('mp3 wav wave m4a aac flac ogg oga opus wma aiff aif ape ac3 dts amr mka mp2'.split(' '));
const PREWARM=new Set('wmv asf mov avi mkv'.split(' '));
let playlists={},history={},historyDate=null,prewarmBusy=false;const prewarmed=new Set(),histState={A:{was:false,id:'',rearm:true},B:{was:false,id:'',rearm:true}};
try{const x=JSON.parse(localStorage.getItem(PL_KEY)||'{}');if(x&&typeof x==='object')playlists=x}catch(e){}
try{const x=JSON.parse(localStorage.getItem(HIST_KEY)||'{}');if(x&&typeof x==='object')history=x}catch(e){}
const extOf=x=>{const n=String(x?.name||x?.path||'').toLowerCase(),m=n.match(/\.([a-z0-9]+)$/);return m?m[1]:''};
const isMedia=f=>VIDEO.has(extOf(f))||AUDIO.has(extOf(f));
const kindOf=x=>VIDEO.has(extOf(x))?'video':'music';
const keyOf=f=>(f.webkitRelativePath||f.name)+'|'+f.size+'|'+f.lastModified;
const folderOf=f=>{const p=f.webkitRelativePath||'';return p.includes('/')?p.split('/').slice(0,-1).join('/'):'Files'};
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD PLAYLIST/HISTORY 177.3]',t)}
function saveRegistry(){try{localStorage.setItem(PL_KEY,JSON.stringify(playlists))}catch(e){}}
function saveHistory(){try{const days=Object.keys(history).sort().slice(-180),trim={};for(const d of days)trim[d]=(history[d]||[]).slice(-1000);history=trim;localStorage.setItem(HIST_KEY,JSON.stringify(history))}catch(e){}}
function broadenInputs(){['folderInput','filesInput'].forEach(id=>document.getElementById(id)?.removeAttribute('accept'));D()?.getElementById('file')?.removeAttribute('accept')}
function captureAllMedia(e){const input=e.target;if(input?.tagName!=='INPUT'||input?.type!=='file'||!input.files?.length)return;const api=window.__afdWin170;if(!api?.items)return;let n=0;[...input.files].forEach(f=>{if(!isMedia(f))return;const k=keyOf(f);if(api.items.some(x=>x.key===k))return;api.items.push({key:k,file:f,folder:folderOf(f),name:f.name,kind:kindOf(f)});n++});if(n)setTimeout(()=>{api.refresh();status('LOCAL LIBRARY • נוספו '+n+' קבצי מדיה');schedulePrewarm()},0)}
if(!window.__afdCaptureMedia177){window.__afdCaptureMedia177=true;document.addEventListener('change',captureAllMedia,true)}
async function loadItem(deck,it){if(!it)return false;if(typeof window.AFDWindowsLoadItem==='function')return window.AFDWindowsLoadItem(deck,it);const w=frame()?.contentWindow;if(!w||typeof w.load!=='function'||!it.file)return false;w.load(deck,it.file);window.dispatchEvent(new CustomEvent('afd-local-load',{detail:{deck,item:it}}));return true}
function installSideDrag(d){if(!d||d.documentElement.dataset.afdSideDrag177v3)return;d.documentElement.dataset.afdSideDrag177v3='1';d.addEventListener('drop',e=>{const root=e.target?.closest?.('.deckA,.deckB');if(!root)return;const raw=e.dataTransfer?.getData('application/x-afd-q-index');if(raw===''||raw==null)return;const i=Number(raw),q=window.__afdWin170?.queue||[],it=q[i];if(!Number.isInteger(i)||!it)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadItem(root.classList.contains('deckB')?'B':'A',it).catch(x=>status('LOAD ERROR • '+x.message))},true)}
async function pathFor(it){let p=it.path||'';const bridge=window.afdDesktopMedia;if(!p&&bridge?.getPath)try{p=await bridge.getPath(it.key)}catch(e){}return p}
async function saveCurrentPlaylist(){const q=window.__afdWin170?.queue||[];if(!q.length){status('PLAYLIST • אין שירים ב-SIDEVIEW');return}const bridge=window.afdDesktopMedia;if(!bridge?.savePlaylist){status('PLAYLIST • שמירה לקובץ זמינה ב-Windows בלבד');return}const tracks=[];for(const it of q){const p=await pathFor(it);if(!p)continue;tracks.push({path:p,name:it.name||p.split(/[\\/]/).pop(),folder:it.folder||'Saved Playlist',kind:it.kind||kindOf(it)})}if(!tracks.length){status('PLAYLIST • לא נמצאו נתיבי קבצים לשמירה');return}try{const res=await bridge.savePlaylist({defaultName:'AFD Playlist',tracks});if(!res||res.canceled)return;playlists[res.name]={name:res.name,path:res.filePath,tracks:res.tracks||tracks};saveRegistry();renderPlaylistBrowser();status('PLAYLIST SAVED • '+res.name+' • '+tracks.length+' שירים')}catch(e){status('PLAYLIST ERROR • '+(e?.message||e))}}
function restoreItem(x){const kind=x.kind==='video'||VIDEO.has(extOf(x))?'video':'music',mime=kind==='video'?'video/mp4':'audio/mpeg',f=new File([],x.name||'Track',{type:mime,lastModified:0});return{key:'saved:'+x.path,file:f,path:x.path,name:x.name||'Track',folder:x.folder||'Saved Playlist',kind}}
async function loadPlaylist(name){let entry=playlists[name];if(!entry)return;let tracks=Array.isArray(entry)?entry:entry.tracks||[];if(entry.path&&window.afdDesktopMedia?.readPlaylist){try{const fresh=await window.afdDesktopMedia.readPlaylist(entry.path);if(fresh?.tracks?.length){tracks=fresh.tracks;entry={...entry,name:fresh.name||name,tracks};playlists[name]=entry;saveRegistry()}}catch(e){status('PLAYLIST ERROR • לא ניתן לפתוח '+name);return}}if(!tracks.length){status('PLAYLIST • '+name+' ריק');return}const api=window.__afdWin170,q=api?.queue;if(!q)return;q.splice(0,q.length,...tracks.map(restoreItem));api.refresh();setTimeout(renderPlaylistBrowser,60);status('PLAYLIST • '+name+' • נטען ל-SIDEVIEW • אפשר START MIX')}
function activeCat(name){const d=D(),cat=d?.querySelector('#afdFolders170 [data-cat="'+name+'"]');return!!cat?.classList.contains('active')}
function renderPlaylistBrowser(){const d=D(),host=d?.getElementById('afdTracks170');if(!d||!host||!activeCat('playlist'))return;const names=Object.keys(playlists).sort((a,b)=>a.localeCompare(b));host.innerHTML=names.length?'<div class="afdSavedPLHint177">PLAYLISTS SAVED • לחץ פעמיים על שם פלייליסט כדי לטעון ל-SIDEVIEW</div>'+names.map(n=>'<div class="afdSavedPLRow177" data-pl="'+clean(n)+'"><span>♫</span><b>'+clean(n)+'</b></div>').join(''):'<div class="afdEmpty170">אין עדיין פלייליסטים שמורים.<br>הוסף שירים ל-SIDEVIEW ולחץ SAVE.</div>';host.querySelectorAll('.afdSavedPLRow177').forEach(r=>{r.addEventListener('click',()=>host.querySelectorAll('.afdSavedPLRow177').forEach(x=>x.classList.toggle('selected',x===r)));r.addEventListener('dblclick',e=>{e.preventDefault();loadPlaylist(r.dataset.pl)})})}
function bindPlaylistCategory(d){if(!d||d.documentElement.dataset.afdPlaylistCat177v3)return;d.documentElement.dataset.afdPlaylistCat177v3='1';d.addEventListener('click',e=>{if(e.target?.closest?.('#afdFolders170 [data-cat="playlist"]'))setTimeout(renderPlaylistBrowser,20);if(e.target?.closest?.('#afdFolders170 [data-cat="history"]')){historyDate=null;setTimeout(renderHistoryBrowser,20)}},true)}
function installPlaylistUI(d){const tabs=d?.querySelector('.afdSideTabs170');if(!tabs)return;let b=d.getElementById('afdSavePlaylist174')||d.getElementById('afdSavePlaylist177');if(b&&!b.dataset.afd177v3){const n=b.cloneNode(true);b.replaceWith(n);b=n}if(!b){b=d.createElement('button');b.id='afdSavePlaylist177';tabs.appendChild(b)}if(!b.dataset.afd177v3){b.dataset.afd177v3='1';b.textContent='💾 SAVE';b.title='שמור את SIDEVIEW כקובץ Playlist במחשב';b.addEventListener('click',saveCurrentPlaylist)}}
function patchRows(d){d?.querySelectorAll('.afdLocalRow170 [data-side]').forEach(b=>{b.textContent='＋SIDEVIEW';b.title='הוסף ל-Side View / Automix'});d?.querySelectorAll('.afdQ170').forEach(r=>{if(r.dataset.afdDrag177v3)return;r.dataset.afdDrag177v3='1';r.addEventListener('dragstart',e=>{const i=Number(r.dataset.i),it=window.__afdWin170?.queue?.[i];if(it)e.dataTransfer.setData('application/x-afd-local-key',it.key||'')},true)})}
function localDay(ts){const d=new Date(ts),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day}
function sourceInfo(k){const d=D(),title=(d?.getElementById('title'+k)?.textContent||'').trim(),yt=d?.getElementById('ytDeck'+k),sp=d?.getElementById('afdSP105Deck'+k),meta=window.AFDLocalDeckMeta?.[k]||null;if(yt)return{source:'YouTube',name:title||'YouTube',id:'yt:'+String(yt.src||title),path:'',kind:'video'};if(sp)return{source:'Spotify',name:title||'Spotify',id:'sp:'+String(sp.dataset?.trackId||sp.src||title),path:'',kind:'music'};const v=d?.getElementById('vid'+k),src=String(v?.currentSrc||v?.src||'');return{source:'Local',name:meta?.name||title||'Local Track',id:'local:'+String(meta?.path||meta?.key||src||title),path:meta?.path||'',kind:meta?.kind||'music'}}
function deckPlaying(k){const d=D(),v=d?.getElementById('vid'+k);return!!((v&&(v.currentSrc||v.src)&&!v.paused&&!v.ended)||window.AFDYouTubeState?.isPlaying?.(k)||window.AFDSpotifyState?.isPlaying?.(k))}
function recordPlay(k){const inf=sourceInfo(k);if(!inf.id||!inf.name||/Drop a track/i.test(inf.name))return;const now=Date.now(),day=localDay(now),arr=history[day]||(history[day]=[]);arr.push({ts:now,time:new Date(now).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}),deck:k,name:inf.name,source:inf.source,path:inf.path,kind:inf.kind});saveHistory();histState[k].id=inf.id;histState[k].rearm=false;if(activeCat('history'))renderHistoryBrowser();status('HISTORY • '+inf.name+' • נשמר '+day)}
function watchHistory(){const d=D();if(!d)return;for(const k of ['A','B']){const s=histState[k],now=deckPlaying(k),inf=sourceInfo(k),v=d.getElementById('vid'+k);if(now&&!s.was){const atStart=!!(v&&(v.currentSrc||v.src)&&(Number(v.currentTime)||0)<1.5);if(s.id!==inf.id||s.rearm||atStart)recordPlay(k)}if(!now&&s.was&&v&&(v.ended||(Number(v.currentTime)||0)<.25))s.rearm=true;if(inf.id&&s.id&&inf.id!==s.id)s.rearm=true;s.was=now}}
function bindHistoryTransport(d){for(const k of ['A','B']){const root=d?.querySelector('.deck'+k),stop=root?[...root.querySelectorAll('.transport button')].find(b=>/STOP/i.test(b.textContent||'')):null;if(stop&&!stop.dataset.afdHist177){stop.dataset.afdHist177='1';stop.addEventListener('click',()=>{setTimeout(()=>{histState[k].rearm=true;histState[k].was=false},20)},true)}}}
function dayLabel(day){try{return new Intl.DateTimeFormat('he-IL',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(day+'T12:00:00'))}catch(e){return day}}
function renderHistoryBrowser(){const d=D(),host=d?.getElementById('afdTracks170');if(!d||!host||!activeCat('history'))return;if(historyDate){const arr=(history[historyDate]||[]).slice().sort((a,b)=>a.ts-b.ts);host.innerHTML='<div class="afdHistHead177"><button id="afdHistBack177">◀ תאריכים</button><b>'+clean(dayLabel(historyDate))+'</b><span>'+arr.length+' השמעות</span></div>'+(arr.length?arr.map((x,i)=>'<div class="afdHistTrack177"><span>'+String(i+1).padStart(2,'0')+'</span><time>'+clean(x.time||'')+'</time><b>'+clean(x.name)+'</b><small>Deck '+clean(x.deck)+' • '+clean(x.source)+'</small></div>').join(''):'<div class="afdEmpty170">אין השמעות ביום הזה.</div>');d.getElementById('afdHistBack177').onclick=()=>{historyDate=null;renderHistoryBrowser()};return}const days=Object.keys(history).filter(x=>(history[x]||[]).length).sort().reverse();host.innerHTML=days.length?'<div class="afdSavedPLHint177">HISTORY • בחר תאריך כדי לראות את רשימת ההשמעות</div>'+days.map(day=>{const a=history[day]||[],first=a[0]?.time||'',last=a[a.length-1]?.time||'';return'<div class="afdHistDay177" data-day="'+day+'"><span>🕘</span><b>'+clean(dayLabel(day))+'</b><small>'+a.length+' שירים • '+clean(first)+(last&&last!==first?'–'+clean(last):'')+'</small></div>'}).join(''):'<div class="afdEmpty170">אין עדיין היסטוריית השמעות.<br>ברגע שתנגן שיר הוא יישמר כאן לפי תאריך.</div>';host.querySelectorAll('.afdHistDay177').forEach(r=>r.onclick=()=>{historyDate=r.dataset.day;renderHistoryBrowser()})}
function schedulePrewarm(){setTimeout(prewarmNext,900)}
async function prewarmNext(){if(prewarmBusy||!window.afdDesktopMedia)return;const items=window.__afdWin170?.items||[],it=items.find(x=>PREWARM.has(extOf(x))&&!prewarmed.has(x.key));if(!it)return;prewarmed.add(it.key);prewarmBusy=true;try{const meta={key:it.key,path:it.path||'',name:it.name||'',kind:it.kind||kindOf(it),force:false};it.path?await window.afdDesktopMedia.preparePath(meta):await window.afdDesktopMedia.prepare(meta);console.log('[AFD PREWARM]',it.name)}catch(e){console.warn('[AFD PREWARM]',it.name,e)}finally{prewarmBusy=false;setTimeout(prewarmNext,250)}}
function style(d){if(!d?.head)return;d.querySelector('.afdSavedWrap177')?.remove();let s=d.getElementById('afdPlaylistStyle177v3');if(!s){s=d.createElement('style');s.id='afdPlaylistStyle177v3';d.head.appendChild(s)}s.textContent='.afdDeckStrip131{display:none!important}.afdSavedWrap174,.afdSavedWrap177{display:none!important}.afdSideTabs170{grid-template-columns:1fr auto auto!important}.afdSavedPLHint177{position:sticky;top:0;z-index:3;padding:8px 10px;background:#171d25;border-bottom:1px solid #343c47;color:#aeb9c6;font-size:8px;font-weight:900}.afdSavedPLRow177{display:grid;grid-template-columns:28px minmax(0,1fr);gap:8px;align-items:center;padding:10px 12px;border-bottom:1px solid #20262d;font-size:10px;cursor:default}.afdSavedPLRow177:hover,.afdHistDay177:hover{background:#171d25}.afdSavedPLRow177.selected{background:#3b2858;color:#fff}.afdSavedPLRow177 b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px}.afdHistDay177{display:grid;grid-template-columns:30px minmax(0,1fr) 190px;gap:8px;align-items:center;padding:11px 12px;border-bottom:1px solid #20262d;cursor:pointer}.afdHistDay177 b{font-size:11px}.afdHistDay177 small{font-size:8px;color:#96a2af;text-align:right}.afdHistHead177{position:sticky;top:0;z-index:4;display:grid;grid-template-columns:85px minmax(0,1fr) 90px;gap:8px;align-items:center;padding:7px;background:#151b22;border-bottom:1px solid #343c47}.afdHistHead177 button{height:27px}.afdHistHead177 b{font-size:10px}.afdHistHead177 span{font-size:8px;color:#9ba7b4;text-align:right}.afdHistTrack177{display:grid;grid-template-columns:30px 55px minmax(0,1fr) 150px;gap:8px;align-items:center;padding:8px 10px;border-bottom:1px solid #20262d}.afdHistTrack177 time{font-size:9px;color:#d7c4f4}.afdHistTrack177 b{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.afdHistTrack177 small{font-size:8px;color:#929eaa}'}
function refresh(){broadenInputs();const d=D();if(!d)return;style(d);installSideDrag(d);bindPlaylistCategory(d);installPlaylistUI(d);patchRows(d);bindHistoryTransport(d);if(activeCat('playlist'))renderPlaylistBrowser();else if(activeCat('history'))renderHistoryBrowser();schedulePrewarm()}
window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(['A','B'].includes(k)){histState[k].rearm=true;histState[k].was=false}});window.addEventListener('afd-deck-eject',e=>{const k=e.detail?.deck;if(['A','B'].includes(k)){histState[k]={was:false,id:'',rearm:true}}});
const api={refresh,saveCurrentPlaylist,loadPlaylist,renderPlaylistBrowser,renderHistoryBrowser,history};window.__afdWin177V143=api;window.__afdWin177=api;frame()?.addEventListener('load',()=>setTimeout(refresh,220));refresh();setTimeout(refresh,700);setInterval(()=>{refresh();watchHistory()},650);
})();