(()=>{
if(window.__afd213){window.__afd213.refresh();return}
window.__afd213Active=true;
const VERSION='__AFD_VERSION__';
const F=()=>document.getElementById('console');
const D=()=>{try{return F()?.contentDocument||null}catch(e){return null}};
const W=()=>{try{return F()?.contentWindow||null}catch(e){return null}};
const C=()=>window.__afdCore206;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const owner={A:'',B:''},chain={A:Promise.resolve(),B:Promise.resolve()},internal={A:false,B:false};
const bpmBase={A:0,B:0},pitchPct={A:0,B:0},bpmToken={A:0,B:0};
let boundWindow=null;
function status(t){const e=document.getElementById('status');if(e)e.textContent=t;console.log('[AFD 213]',t)}
function deckVideo(k){return D()?.getElementById('vid'+k)||null}
function deckMaster(k){return D()?.getElementById('master'+k)||null}
function nameOf(x){return String(x?.name||x?.afdSpotifyItem?.name||x?.afdYouTubeItem?.title||x?.afdHistoryItem?.name||'Track')}
function typeOf(x){if(!x)return'';if(x.afdHistorySource==='Spotify'||x.afdSpotifyItem||x.spotifyItem||x.__source==='spotify')return'spotify';if(x.afdHistorySource==='YouTube'||x.afdYouTubeItem||x.youtubeItem)return'youtube';return'local'}
function payload(x,t=typeOf(x)){if(t==='spotify')return x.afdHistoryItem||x.afdSpotifyItem||x.spotifyItem||x;if(t==='youtube'){const i=x.afdHistoryItem||x.afdYouTubeItem||x.youtubeItem||x;return{id:i.id||i.videoId||'',title:i.title||x.name||'YouTube',channel:i.channel||'',thumb:i.thumb||''}}if(x.afdHistorySource==='Local')return{...(x.afdHistoryItem||{}),path:x.afdHistoryItem?.path||x.path||'',key:x.afdHistoryItem?.key||x.key||'',name:x.afdHistoryItem?.name||x.name||'Track',folder:x.afdHistoryItem?.folder||x.folder||'',kind:x.afdHistoryItem?.kind||x.kind||'music'};return x}
function inferOwner(k){if(window.AFDSpotifyState?.has?.(k))return'spotify';if(window.AFDYouTubeState?.isLoaded?.(k)||D()?.getElementById('ytDeck'+k))return'youtube';const v=deckVideo(k);if(window.AFDLocalDeckMeta?.[k]||(v&&(v.currentSrc||v.src)))return'local';return''}
async function clearSpotify(k){const s=window.AFDSpotifyState;try{if(s?.has?.(k)){if(s.stopNow)await Promise.race([Promise.resolve(s.stopNow(k)),sleep(900)]);else if(s.pauseNow)await Promise.resolve(s.pauseNow(k));else s.pause?.(k);s.clear?.(k)}}catch(e){}D()?.getElementById('afdSP105Deck'+k)?.remove()}
function clearYouTube(k){const s=window.AFDYouTubeState;try{s?.stop?.(k)}catch(e){}try{s?.clear?.(k)}catch(e){}const d=D();d?.getElementById('ytDeck'+k)?.remove();const m=d?.getElementById('ytMaster'+k);if(m)m.style.display='none'}
function clearLocal(k){const v=deckVideo(k),m=deckMaster(k);if(v){try{v.pause()}catch(e){}try{v.removeAttribute('src');v.load()}catch(e){}v.style.display='none'}if(m){try{m.pause()}catch(e){}try{m.removeAttribute('src');m.load()}catch(e){}m.style.display='none'}if(window.AFDLocalDeckMeta)window.AFDLocalDeckMeta[k]=null}
async function clearOthers(k,keep){if(keep!=='spotify')await clearSpotify(k);if(keep!=='youtube')clearYouTube(k);if(keep!=='local')clearLocal(k)}
function serial(k,fn){if(!['A','B'].includes(k))return Promise.resolve(false);chain[k]=chain[k].catch(()=>{}).then(fn);return chain[k]}
function waitFor(fn,ms=7000){return new Promise(async resolve=>{const end=performance.now()+ms;while(performance.now()<end){try{if(fn())return resolve(true)}catch(e){}await sleep(70)}resolve(false)})}
async function doSpotify(k,x){const i=payload(x,'spotify');if(!i?.id&&!i?.uri)return false;owner[k]='loading';await clearOthers(k,'spotify');internal[k]=true;try{window.dispatchEvent(new CustomEvent('afd-spotify-load',{detail:{deck:k,item:i,afd213:true}}))}finally{internal[k]=false}const ok=await waitFor(()=>window.AFDSpotifyState?.has?.(k),4500);owner[k]=ok?'spotify':'';if(ok){resetBpmOnline(k);status('SPOTIFY • '+(i.name||'Track')+' → DECK '+k)}else status('SPOTIFY ERROR • לא נטען ל-DECK '+k);return ok}
async function doYouTube(k,x){const i=payload(x,'youtube');if(!i?.id)return false;owner[k]='loading';await clearOthers(k,'youtube');internal[k]=true;let ok=false;try{ok=(await window.AFDYouTubeState?.load?.(k,i))!==false}catch(e){status('YOUTUBE ERROR • '+(e?.message||e))}finally{internal[k]=false}if(ok)ok=await waitFor(()=>window.AFDYouTubeState?.isLoaded?.(k)||!!D()?.getElementById('ytDeck'+k),5500);owner[k]=ok?'youtube':'';if(ok){resetBpmOnline(k);status('YOUTUBE • '+(i.title||'Track')+' → DECK '+k)}else status('YOUTUBE ERROR • לא נטען ל-DECK '+k);return ok}
async function doLocal(k,x){const i=payload(x,'local');owner[k]='loading';await clearOthers(k,'local');internal[k]=true;let ok=false;try{if(typeof window.AFDWindowsLoadItem==='function')ok=!!(await window.AFDWindowsLoadItem(k,i));if(!ok&&i?.file&&typeof W()?.load==='function'){W().load(k,i.file);ok=await waitFor(()=>!!(deckVideo(k)?.currentSrc||deckVideo(k)?.src),2500)}}catch(e){status('LOCAL ERROR • '+(e?.message||e))}finally{internal[k]=false}if(ok){await clearSpotify(k);clearYouTube(k);owner[k]='local';pitchPct[k]=0;setPitchUI(k,0,false);scheduleBpm(k,i);status('LOCAL • '+nameOf(i)+' → DECK '+k)}else owner[k]='';return ok}
function loadDeck(k,x){const t=typeOf(x);return serial(k,()=>t==='spotify'?doSpotify(k,x):t==='youtube'?doYouTube(k,x):doLocal(k,x))}
function loadSpotify(k,x){return serial(k,()=>doSpotify(k,x))}
function loadYouTube(k,x){return serial(k,()=>doYouTube(k,x))}
function loadLocal(k,x){return serial(k,()=>doLocal(k,x))}
function bpmEl(k){const d=D(),root=d?.querySelector('.deck'+k+' .bpm');if(!root)return null;let e=d.getElementById('bpm'+k)||root.querySelector('strong');if(e&&!e.id)e.id='bpm'+k;return e}
function pitchRead(k){const d=D(),p=d?.querySelector('.deck'+k+' .pitch');if(!p)return null;let r=d.getElementById('afdPitchRead213'+k);if(!r){r=d.createElement('b');r.id='afdPitchRead213'+k;r.className='afdPitchRead213';p.prepend(r)}return r}
function updateBpm(k){const e=bpmEl(k);if(!e)return;const b=Number(bpmBase[k])||0;if(!b){e.textContent='--';e.dataset.afdBaseBpm='';return}e.dataset.afdBaseBpm=String(b);e.textContent=(b*(1+pitchPct[k]/100)).toFixed(1)}
function setPitchUI(k,p,apply=true){p=clamp(Number(p)||0,-16,16);pitchPct[k]=p;const d=D(),s=d?.getElementById('pitch'+k),r=pitchRead(k);if(s&&Number(s.value)!==p)s.value=String(p);if(r)r.textContent=(p>=0?'+':'')+p.toFixed(1)+'%';if(apply){const rate=1+p/100,v=deckVideo(k),m=deckMaster(k);if(v){try{v.preservesPitch=true;v.webkitPreservesPitch=true;v.mozPreservesPitch=true}catch(e){}v.playbackRate=rate}if(m&&(m.currentSrc||m.src))m.playbackRate=rate}updateBpm(k)}
function resetBpmOnline(k){bpmToken[k]++;bpmBase[k]=0;pitchPct[k]=0;setPitchUI(k,0,false);updateBpm(k)}
function localIdentity(i){return String(i?.path||i?.key||i?.name||'')}
function scheduleBpm(k,i){const token=++bpmToken[k],id=localIdentity(i);bpmBase[k]=0;updateBpm(k);const run=async()=>{if(token!==bpmToken[k]||owner[k]!=='local')return;const b=window.afdDesktopMedia;try{let r=null;if(i?.path&&b?.analyzeBpmPath)r=await b.analyzeBpmPath(i);else if(i?.key&&b?.analyzeBpm)r=await b.analyzeBpm(i);if(token!==bpmToken[k]||owner[k]!=='local'||localIdentity(window.AFDLocalDeckMeta?.[k]||i)!==id)return;const n=Number(r?.bpm)||0;if(n>30&&n<300){bpmBase[k]=n;updateBpm(k);status('BPM • DECK '+k+' • '+n.toFixed(1))}}catch(e){if(token===bpmToken[k]){bpmBase[k]=0;updateBpm(k)}}};const idle=()=>('requestIdleCallback'in window?requestIdleCallback(()=>run(),{timeout:5000}):setTimeout(run,1800));setTimeout(idle,900)}
function keyDeck(target){const b=target?.closest?.('.afdDeckKeySide184 button[data-d],.afdDeckKey206 button[data-k]');if(!b)return null;const box=b.closest('[id]'),id=box?.id||'';const k=id.endsWith('A')?'A':id.endsWith('B')?'B':'';if(!k)return null;const delta=Number(b.dataset.d??b.dataset.k)||0;return{k,delta,b}}
async function keyChange(k,delta){if((owner[k]||inferOwner(k))!=='local'){status('KEY • זמין לקבצים מקומיים בלבד');return}const api=window.__afdWin184;if(!api?.setTone){status('KEY ERROR • מנוע שינוי הטון לא זמין');return}const cur=Number(api.getTone?.(k))||0,next=clamp(cur+delta,-12,12);const ok=await api.setTone(k,next);const d=D();for(const id of ['afdDeckKeyRead'+k,'afdDeckKeyRead206'+k]){const r=d?.getElementById(id);if(r)r.textContent=(next>0?'+':'')+next}status(ok===false?'KEY ERROR • לא ניתן לעבד את הקובץ':'DECK '+k+' • KEY '+(next>0?'+':'')+next)}
function bindInner(){const w=W(),d=D();if(!w||!d||boundWindow===w)return;boundWindow=w;w.addEventListener('input',e=>{const s=e.target?.closest?.('#pitchA,#pitchB');if(!s)return;const k=s.id.endsWith('A')?'A':'B';if((owner[k]||inferOwner(k))!=='local')return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();setPitchUI(k,Number(s.value)||0,true)},true);w.addEventListener('change',e=>{const s=e.target?.closest?.('#pitchA,#pitchB');if(!s)return;const k=s.id.endsWith('A')?'A':'B';if((owner[k]||inferOwner(k))!=='local')return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();setPitchUI(k,Number(s.value)||0,true)},true);w.addEventListener('click',e=>{const x=keyDeck(e.target);if(x){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();keyChange(x.k,x.delta);return}const strong=e.target?.closest?.('.afdDeckKeySide184 strong');if(strong){const k=strong.id.endsWith('A')?'A':'B';e.preventDefault();e.stopImmediatePropagation();const api=window.__afdWin184;Promise.resolve(api?.setTone?.(k,0)).then(()=>status('DECK '+k+' • KEY 0'))}},true)}
function bindSourceEvents(){if(document.documentElement.dataset.afd213sources)return;document.documentElement.dataset.afd213sources='1';window.addEventListener('afd-local-load',e=>{const k=e.detail?.deck;if(!k||internal[k])return;owner[k]='local';pitchPct[k]=0;setPitchUI(k,0,false);scheduleBpm(k,e.detail?.item||window.AFDLocalDeckMeta?.[k]||{})},true);window.addEventListener('afd-spotify-load',e=>{const k=e.detail?.deck;if(k&&!internal[k])owner[k]='spotify'},true);window.addEventListener('afd-youtube-load',e=>{const k=e.detail?.deck;if(k&&!internal[k])owner[k]='youtube'},true)}
function bindOnlineCapture(){if(document.documentElement.dataset.afd213online)return;document.documentElement.dataset.afd213online='1';document.addEventListener('pointerdown',e=>{const y=e.target?.closest?.('#afdYTInlineResults [data-d]');if(y){const row=y.closest('[data-i]'),i=Number(row?.dataset.i),it=window.AFDYouTubeState?.getItems?.()?.[i];if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadYouTube(y.dataset.d,it)}return}const s=e.target?.closest?.('#afdSP196 [data-d]');if(s){const row=s.closest('[data-i]'),i=Number(row?.dataset.i),it=window.__afdSpotify196?.getItems?.()?.[i];if(it){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();loadSpotify(s.dataset.d,it)}}},true);document.addEventListener('click',e=>{const y=e.target?.closest?.('#afdYTInlineResults [data-d]'),s=e.target?.closest?.('#afdSP196 [data-d]');if(y||s){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}},true)}
function serialize(x){const t=typeOf(x),i=payload(x,t);if(t==='spotify')return{t:'sp',n:nameOf(x),i};if(t==='youtube')return{t:'yt',n:nameOf(x),i};let p=String(i?.path||'');if(!p)try{p=String(window.afdDesktopMedia?.getPath?.(i?.key||'')||'')}catch(e){}return{t:'lo',n:nameOf(x),p,k:String(i?.key||''),f:String(i?.folder||'Playlist'),d:String(i?.kind||'music')}}
async function saveSide(){const a=(Array.isArray(C()?.queue)?C().queue:[]).map(serialize).filter(x=>x.t!=='lo'||x.p);if(!a.length){status('PLAYLIST • אין פריטים שניתנים לשמירה');return}const bridge=window.afdDesktopMedia;const saver=bridge?.savePlaylistV213||bridge?.savePlaylist;if(!saver){status('PLAYLIST SAVE ERROR • מנוע השמירה לא זמין');return}try{const r=await saver({defaultName:'AFD Playlist',items:a});if(!r||r.canceled)return;try{const key='afdSavedPlaylists212',reg=JSON.parse(localStorage.getItem(key)||'{}')||{};reg[r.name]={name:r.name,path:r.filePath,items:r.items||a,savedAt:Date.now()};localStorage.setItem(key,JSON.stringify(reg))}catch(e){}status('PLAYLIST SAVED • '+(r.name||'Playlist')+' • '+a.length+' שירים')}catch(e){status('PLAYLIST SAVE ERROR • '+(e?.message||e))}}
function css(){const d=D();if(!d?.head)return;let s=d.getElementById('afd213css');if(!s){s=d.createElement('style');s.id='afd213css';d.head.appendChild(s)}s.textContent='.afdPitchRead213{display:block;font-size:9px;color:#d9c5ff;margin-bottom:3px;font-variant-numeric:tabular-nums}.deckB .afdPitchRead213{color:#9edcff}.bpm strong{font-variant-numeric:tabular-nums}'}
function refresh(){window.__afd213Active=true;bindSourceEvents();bindOnlineCapture();bindInner();css();for(const k of ['A','B']){bpmEl(k);pitchRead(k);if(!owner[k])owner[k]=inferOwner(k);if(owner[k]==='local')setPitchUI(k,Number(D()?.getElementById('pitch'+k)?.value)||pitchPct[k],false)}}
const api={refresh,loadDeck,loadLocal,loadSpotify,loadYouTube,saveSide,getOwner:k=>owner[k]||inferOwner(k)};
window.__afdUnified213=api;window.__afdUnified212=api;window.__afdUnified211=api;window.__afd213=api;
F()?.addEventListener('load',()=>setTimeout(()=>{boundWindow=null;refresh()},700));refresh();setInterval(refresh,1000);
})();
